### ISSUE TITLE
Drop WaitStrategy

### ISSUE THREAD

**Issue by garakelian** [LMAX-Exchange/disruptor#103]
I was wondering how difficult it would be to add a "DropWaitStrategy" -- e.g. put another way, what would the WaitStrategy.waitFor method have to return to signal the caller to drop an event?  I'm writing a StatsD client which posts events from main threads to a RingBuffer which is then consumed by a writer that sends the data via UDP packets to a StatsD server (UDP is useful for StatsD because we don't care if drop a few packets).  In my use case, if the StatsD "event queue" were full, I'd never want the main thread to block, instead I'd like it to quietly drop the event.  I'd like to get some guidance on how I could do this.

**Comment by garakelian** [comment]
Looking at the Javadoc for WaitStrategy, it appears as though I could return cursor.get()?  Or would it be dependentSequence.get()?  Not sure I understand the interaction of those two... thanks for your help.

**Comment by mikeb01** [comment]
Use the 'try' methods, like tryNext() or tryPublishEvent().  They will not block.  The tryPublishEvent methods will return false if the message could not be enqueued, tryNext will throw an InsufficientCapacityException, which you will need to trap and swallow.

**Comment by garakelian** [comment]
Thanks for your help. Much appreciated.
