### ISSUE TITLE
Support "clearing" the Disruptor

### ISSUE THREAD

**Issue by mikeb01** [LMAX-Exchange/disruptor#105]
Have a single method call that can stop all of the consumers, reset their sequence number to the cursor value of the ring buffer and restart them all.  This would only be available to users of the Disruptor class, which has a view of all of the consumers.  Should not impact performance of current fast paths and should race free.

**Comment by brimzi** [comment]
How far with this?has any anyone taken this up?

**Comment by mikeb01** [comment]
Not as yet.  The user discussion that triggered this moved in a direction where I suggested a number of other options (https://groups.google.com/d/msg/lmax-disruptor/UFBGf7gps1Q/a1oQjpWfISIJ).  I didn't get any further response so I've not pursued this feature.

**Comment by brimzi** [comment]
OK thanks

**Comment by mikeb01** [comment]
I am not going to implement this.  As preventing publication during this process becomes difficult without introducing additional performance cost.
