### ISSUE TITLE
What is causing this performance drop?

### ISSUE THREAD

**Issue by zoltanmaric** [LMAX-Exchange/disruptor#107]
Hi Disruptor team!
I'm experiencing a significant performance drop when using pipelined consumers. I've described the problem in detail on StackOverflow: http://stackoverflow.com/q/28630621/900130

Could anyone give me some guidelines on where to look for the problem?

**Comment by mjpt777** [comment]
What model of CPU are you running this on and what idle strategies are
being used?

**Comment by zoltanmaric** [comment]
The CPU is Intel(R) Core(TM) i7-2670QM CPU @ 2.20GHz. It has 4 physical/8 virtual cores.
I am running 8 RsEventHandlers in parallel.

This is my disruptor setup:

```java
Disruptor<FrameEvent> disruptor = new Disruptor<>(
                new FrameEventFactory(params),
                RING_SIZE,
                exec,
                ProducerType.SINGLE,
                new BlockingWaitStrategy()
        );
```

`RING_SIZE` is 16384, the executor is `Executors.newCachedThreadPool()`.

**Comment by mjpt777** [comment]
I think this is simply that you do not have sufficient cores to run all the
vent handlers plus the producer and any OS activity for context switching
the blocking threads.

The Disruptor does not do well when you try to run more threads than you
have cores available.

**Comment by zoltanmaric** [comment]
Really? Even if the additional thread only does a condition check? And that costs an extra 15-20% in CPU usage?

**Comment by mjpt777** [comment]
How you measured context switches with the likes of "perf stat" on Linux?

Try a simple test where by you increase the number of event processors from
1 to n. Then watch the performance fall off a cliff when the n - 1 >=
number of real cores.

**Comment by zoltanmaric** [comment]
Does this mean that if I have a process intensive task to which I assign all my virtual cores then I will see an inevitable performance drop if I assign more threads to other tasks, regardless of how lightweight they are and which concurrency framework I choose?

**Comment by mjpt777** [comment]
Basically yes. Even with the blocking strategy you will still incur
significant context switch costs. With a busy spinning strategy you will
spin until the scheduler decides to interrupt the thread when it increases
the priority of something waiting for the core.

Sounds like you need a different concurrency mechanism but it would be hard
to know which one without knowing a lot more about the problem domain.

Have you considered having less event processors and doing more work in
each? Doing tiny amounts of work is not well suited to any concurrency
model. The cost of coordination and coherence can greatly outweigh the
benefits of splitting the work across cores. You need to think of each task
being a few hundred CPU instructions worth to benefit from being run
concurrently.

**Comment by zoltanmaric** [comment]
Thank you for your help. I will test your "fall off a cliff" experiment and increase the work size per thread. It already is well over hundreds of CPU instructions. It's more in the range of thousands, or perhaps tens of thousands, but it can still be grouped so that there are less context switches.

May I suggest that you make a summary of your answers and post them on StackOverflow? Thanks.

**Comment by mjpt777** [comment]
In your case then work stealing might be a better solution with the likes
of Fork-Join Pool than the disruptor unless you have specific dependencies.
Best to experiment.

Sorry I don't really do StackOverflow.

**Comment by mikeb01** [comment]
Closing.
