### ISSUE TITLE
fix wiki typos

### ISSUE THREAD

**Issue by davidmoten** [LMAX-Exchange/disruptor#109]
https://github.com/LMAX-Exchange/disruptor/wiki/Introduction

In fact the only real difference between the 2 **is** that the Sequence 

implement all of the concurrent algorithms use**d** for fast, correct passing

More details are **available**

There is **no** specific code representation of the Event 

Cheers, thanks for the library

**Comment by mikeb01** [comment]
Fixed, thanks.
