### ISSUE TITLE
Disruptor EventHandler callback on Disruptor shutdown?

### ISSUE THREAD

**Issue by zoltanmaric** [LMAX-Exchange/disruptor#110]
I have an EventHandler that buffers data and writes it to disk when the buffer fills.

```java
@Override
public void onEvent(FrameEvent event, long sequence, boolean endOfBatch)
        throws Exception {
    ByteBuffer frame = event.getFrame();
    frame.reset();
    if (frame.remaining() > buffer.remaining()) {
        writer.writeFromMarkToLimit(buffer);
        buffer.reset();
    }
    buffer.put(frame);
}
```

I would like to get notified when the disruptor gets halted or shut down so that I can flush my buffer. How could I do this?

I saw that EventProcessor has a halt() callback, but I have no idea how to use the EventProcessor interface. I don't know what the getSequence() or the run() methods are supposed to do and I can't seem to find any examples.

**Comment by mikeb01** [comment]
Hi,

Have your implementation of the EventHandler also implement LifecycleAware and you will receive callbacks on start and stop of the thread that is running your handler.  Note that onShutdown will only be called if you the thread get a chance to exit cleanly.  This may not happen if you JVM is killed or crashes.

```Java
public class MyHandler implements EventHandler<Object>, LifecycleAware {
    public void onEvent(Object event, long sequence, boolean endOfBatch) {
        //...
    }
    public void onStart() {
        // ...
    }
    public void onShutdown() {
        // Flush your data here.
    }
}
````
