### ISSUE TITLE
ringBuffer.next ()  get repeat sequence

### ISSUE THREAD

**Issue by soenter** [LMAX-Exchange/disruptor#116]
Why multithreading concurrency ringBuffer.next () to get repeat sequence? Do you want to add synchronization lock on publish?
use 3.3.1

**Comment by soenter** [comment]
//Below is my code：
     public boolean publish(Event typeEvent){
        long sequence = ringBuffer.next();// This sequence will be repeated?
        try{
            DataEvent event = ringBuffer.get(sequence);
            event.setEvent(typeEvent);
        } finally {
            ringBuffer.publish(sequence);
            System.out.println("publish sequence : " + sequence);
        }
        return true;
    }

**Comment by mikeb01** [comment]
Sorry, I don't really understand the question that you are asking.  With regards to the code:

    long sequence = ringBuffer.next();// This sequence will be repeated?

No, the sequence will not be repeated.

**Comment by soenter** [comment]
非常谢谢你的回答，我已经找到问题原因了，生产者在多线程情况下应该配置为ProducerType.MULTI。

**Comment by soenter** [comment]
Thank you for your answer, I have found the cause of the problem, the producers multithreading should be configured ProducerType.MULTI.
