### ISSUE TITLE
Question : regarding waiting strategies

### ISSUE THREAD

**Issue by vach** [LMAX-Exchange/disruptor#117]
I'm appologizing beforehand if this is a "noob" question as i'm not yet familiar with implementation...

I don't quite understand why we cant have disruptor to notify the consumer as soon as it has something to consume? 
suppose the simplest case when we have 1 producer, once the producer thread puts new event to the ring buffer, it can trigger the consumer threads like "hey i have something for you to process" and without blocking return from that piece of code... it can also easily see non dependant consumers and trigger only those, and those in their turn will trigger the dependant ones etc...

I mean isnt it possible to avoid any buzy loops, and wouldnt that be the fastest option if the producer triggered the consumers processing? what i'm missing there...

**Comment by vach** [comment]
I mean when producer is putting an event to the ring buffer, that piece of code can determine right at that moment which consumers are to process this, so why we are not doing that but letting the consumers to detect that they have a work to do... I dont see whats making us to make a choice between cpu cycles and latency...

**Comment by mikeb01** [comment]
It's a fair question.  What you're suggesting is possible and is what the BlockingWaitStrategy does.  Unfortunately it's quite expensive as the only way to suspend and resume the execution of a thread (on most OSes) is to get the OS kernel involved.  There a few of ways to have the producer thread wake up the consumer thread.  You can use Java's synchronzied blocks with wait and notify.  E.g.
```java
private final Object mutex = new Object();

public void produce()
{
    synchronized(mutex)
    {
        mutex.notifyAll();
    }
}

public void consume()
{
    synchronized(mutex)
    {
        mutex.wait();
    }
}
```

You can use Java's Lock and Condition classes
```java
private final Lock lock = new ReentrantLock();
private final Condition condition = lock.newCondition();

public void produce()
{
    lock.lock();
    try
    {
        condition.signalAll();
    }
    finally
    {
        lock.unlock();
    }
}
```

You also explicitly suspend and resume the thread using LockSupport.  This is used internally by Condition class.  However, the Condition has some optimisations to prevent calling `LockSupport.unpark()` when it is not required, such that it is more efficient that the naive application of LockSupport.
```java
private final Thread consumerThread = // Store the consumer thread here.

public void produce()
{
    LockSupport.unpark(consumerThread);
}

public void consume()
{
    LockSupport.park();
}
```

The advantage of using a busy spin is that the wake up of thread happens in userspace and does not need coordination with the OS kernel, hence lower and more predictable latency, but at the cost of CPU cycles.

**Comment by vach** [comment]
Thanks for in dept explaination, 
FYI there is a project https://github.com/puniverse/quasar 
I havent used it yet but as far as i understand this is keeping several threads busy with serving many fibers... and uses some bytecode modification tricks to avoid expensive thread context switching...

I wonder if you've tried it? and if so what was your experience? what do you think of it?
