### ISSUE TITLE
Question regarding MultiProducerSequencer

### ISSUE THREAD

**Issue by valliman** [LMAX-Exchange/disruptor#118]
I use the LMAX disruptor 3.3.2 as part of Log4j2 async logging, lately my application started to behave strangely, logging stopped at some point and the application got unusable. After some test runs and investigation taking a flight recording, I found out that we eventually hit the following code block in the MultiProducerSequencer, which leads to the case that threads are getting parked.

*MultiProducerSequencer::next(1)* has the following loop. Could someone of you explain under what circumstances I hit this loop and cannot leave it? Thank you very much!
```java
do
{
            current = cursor.get();
            next = current + n;

            long wrapPoint = next - bufferSize;
            long cachedGatingSequence = gatingSequenceCache.get();

            if (wrapPoint > cachedGatingSequence || cachedGatingSequence > current)
            {
                long gatingSequence = Util.getMinimumSequence(gatingSequences, current);

                if (wrapPoint > gatingSequence)
                {
                    LockSupport.parkNanos(1); // TODO, should we spin based on the wait strategy?
                    continue;
                }

                gatingSequenceCache.set(gatingSequence);
            }
            else if (cursor.compareAndSet(current, next))
            {
                break;
            }
}
while (true);
```

**Comment by mikeb01** [comment]
If the consumer has stopped or become slow and the buffer fills up.  If there is no space available in the buffer then `Sequencer.next()` (both single and multi) will block until space becomes available.  We use the Disruptor in our own logger implementation.  We instead use `Sequencer.tryNext()` which will return immediately if there is no space available (throws an `InsufficientCapacityException` in that case).  We write a notification to the console (System.err) if we are unable to put log messages into the Disruptor.

We prefer to lose log messages than stall the application.
