### ISSUE TITLE
Disruptor missing events

### ISSUE THREAD

**Issue by Stabmeqt** [LMAX-Exchange/disruptor#120]
Hello. I'm trying to use a Disruptor with a Chronicle Queue, and found that Disruptor misses or repeats some events that are passed to it.

I'm doing an debug output right before disruptor publishes events
                              ObjectValueEvent event = ringBuffer.nextEvent();
                              event.setValue(data);
                              ringBuffer.publish(event);
                              System.out.println(event.getValue());

and it's fine:
event1, event2, event3, event4 and so on. All events are unique

Second output is in handler method:
             disruptorWizard.handleEventsWith(
				new EventHandler<ObjectValueEvent>()
				{
					@Override
					public void onEvent(ObjectValueEvent event,
							boolean endOfBatch) throws Exception
					{
						System.out.println(event.getValue());
					}			
				});		

and it's totally messed up - event1, event5, event9, event9, event9

The only thing, i'm thinking about, is that Chronicle reads data from it's storage and then passes it to disruptor so quickly, that disruptor can't process it. Because adding 100ms sleep before passing data to disruptor solves the issue, is inacceptable.

Can you please point me how to fix it?

**Comment by rudy2steiner** [comment]
I met the same problem when i use multi-producer/on consumer.on event handler, i got the same event repeately for some event.
