### ISSUE TITLE
ExceptionHandler isn't propagated by Disruptor to existed WorkerPool after set

### ISSUE THREAD

**Issue by Spikhalskiy** [LMAX-Exchange/disruptor#122]
ExceptionHandlers set to Disruptor after initializing WorkerPool will not be propagated to WorkerPool

```
disruptor = new Disruptor<>(Event::new, RING_SIZE, executor, ProducerType.SINGLE, new BlockingWaitStrategy());

disruptor.handleExceptionsWith(new FatalExceptionHandler());
disruptor.handleEventsWith(new Handler<Event>()).handleEventsWithWorkerPool(new AnotherHandler<Event>(), new AnotherHandler<Event>());
```

Will fail with NullPointer exception in case of exception in AnotherHandler (exception handler in WorkerPool is null), while on this code

```
disruptor = new Disruptor<>(Event::new, RING_SIZE, executor, ProducerType.SINGLE, new BlockingWaitStrategy());

disruptor.handleEventsWith(new Handler<Event>()).handleEventsWithWorkerPool(new AnotherHandler<Event>(), new AnotherHandler<Event>());
disruptor.handleExceptionsWith(new FatalExceptionHandler());
```

will handle exception correctly.
I think this code samples should lead to the same result and state.

**Comment by ajsutton** [comment]
I think there's actually two issues here:

 1. WorkerPools wind up with a null exception handler if one hasn't been explicitly set. They should default to the FatalExceptionHandler in the same way that BatchEventProcessors would
 1. handleExceptionsWith only affects handlers created *after* it is called.

The first issue is a simple fix, the second is more complex. We would have to iterate through each consumer already registered and attempt to change the exception handler on it.  For BatchEventProcessor that's possible, but WorkerPools take the exceptionHandler in the constructor and don't expose a setter (which could be changed).  There may also be completely custom EventProcessor instances added with no way to guarantee that the exception handler could be set.

Given that, it will never be possible to guarantee that handleExceptionsWith will affect every already created consumer, it's probably better to stick with it's current behaviour of never affecting any already created consumer (only new ones).  Sadly, I can't currently see a good API to both allow using different exception handlers for different consumers and avoid this potential for confusion.

**Comment by ajsutton** [comment]
I've pushed up a fix to ensure that worker pools get a default exception handler like normal handlers do using the DSL.  The default is FatalExceptionHandler which incidentally makes the two code snippets above do the same thing but only because the default happens to match what is being set - handleExceptionsWith still isn't applied to existing consumers.

I'm going to close this issue and not change handleExceptionsWith behaviour but suggestions for an API that avoids this confusion and still supports different exception handlers for different consumers are definitely welcome.

**Comment by Spikhalskiy** [comment]
> The first issue is a simple fix, the second is more complex. We would have to iterate through each consumer already registered

There is another way. When we create consumer in Disruptor's method - pass not exceptionHandler to them, but always not null ExceptionHandlerProvider which is actually a container, manager by Disruptor instance. Set exceptionHandler to disruptor will be set to this constructor in fact.

As additional, it maybe good to hold in each consumer this container with Disruptor eventHandler and own event handler to make it possible to configure overriding for specific eventProcessor if we really need this.

**Comment by ajsutton** [comment]
Yes a DelegatingExceptionHandlerProvider that exposes its own setter would allow us to change the exception handler for any consumer that's using the delegate (custom consumers would still not change as they don't get the exception handler from the Disruptor class at all but that's not unreasonable).  However it loses the ability to have some consumers use different exception handlers. For BatchEventProcessors you could get that back with handleExceptionsFor(xxx).with(exceptionHandler) but it's a nasty change of behaviour that doesn't trigger any compiler errors. handleExceptionsWith is documented to only affect handlers set up after calling it so we should ensure the method name changes at least slightly if the behaviour changes.

**Comment by Spikhalskiy** [comment]
> However it loses the ability to have some consumers use different exception handlers.

Right, so this proposal "it maybe good to hold in each consumer  own event handler to make it possible to configure overriding for specific eventProcessor if we really need this" can helps to address it. On this case we need to think about hierarchies with more that 2 levels (not only Disruptor -> Consumer, but Disruptor -> Consumer1 -> Consumer2 and we change exceptionHandler of Consumer1) if they exists.

Thanks for fixes and future work on this issue.

**Comment by mikeb01** [comment]
The main purpose of the ExceptionHandler feature is to handle exceptions that aren't handled by the application.  I think the simplest way to handle the more complex per-handle scenarios is to simply implement the exception handling logic with the onEvent method of the handler if you need to do something complex.  Use the handler specified on the Disruptor as a default behaviour.

**Comment by ajsutton** [comment]
ok, so sounds like the way forward then is to have the Disruptor class always set a wrapper as the exceptionHandler so we can change the actual implementation after creation.  I'd suggest we do that with a new method setDefaultExceptionHandler and deprecate the current handleExceptionsWith. That way people knowingly switch over to the new behaviour.

My inclination is to only allow setDefaultExceptionHandler to be called prior to start() - the same as handleEventsWith etc.  Technically we could alert each sequence to get the change to be picked up by a running processor but I think that probably falls into the "handle exceptions yourself" case.

**Comment by ajsutton** [comment]
Excuse my fighting with github's magic keywords. Pull request #125 created with the suggested changes.  Could you both take a look and confirm we're all on the same page please?

**Comment by Spikhalskiy** [comment]
I like your implementation. Left only one minor comment, will be good to make exception message more precise. Thanks.
