### ISSUE TITLE
Memory Leak unless clear the event

### ISSUE THREAD

**Issue by ricemaster** [LMAX-Exchange/disruptor#130]
I have a chain of EventHandlers and WorkHandlers trying to save defferent part of the event into defferent database tables. It looks like this

``` Java
    public void init() {
        Executor executor = Executors.newCachedThreadPool();
        EDPSEventFactory factory = new EDPSEventFactory();
        disruptor = new Disruptor<EDPSEvent>(
            factory, 
            bufferSize, 
            executor, 
            ProducerType.SINGLE, 
            new SleepingWaitStrategy());

        // Init WorkHandlersPool
        totalHandlers = SystemProperties.ThreadPoolSize();
        processOriginalRecordHandlers = new ProcessOriginalRecordHandler[totalHandlers];
        Arrays.fill(processOriginalRecordHandlers,new ProcessOriginalRecordHandler());

        disruptor
            .handleEventsWith(saveALERepor)
            .then(saveEVT,saveLocation)
            .then(saveReader)
            .thenHandleEventsWithWorkerPool(processOriginalRecordHandlers)
            .then(saveOriginalRecord)
            .then(saveCachedRecord)
             //.then(new EventGCHandler())
            ;

        disruptor.start();

        producer = new EDPSEventProducer(disruptor.getRingBuffer());
    }

    public void publishEvent(InputStream reportsXML) {
        producer.onData(XMLHelper.convertXML2ECReports(reportsXML));
    }
```

Then I have got a memory leak.
If i put another handler(`new EventGCHandler()`) at the end of the chain, to clear the Event by setting every field to NULL, then the applicaton works fine.

Is it the right way to use Disruptor, or I missed something in my code?

Thanks.

**Comment by mikeb01** [comment]
That is correct.  It is your responsibility to null out reference fields in the event, either in a separate handler at the end of the last handler in the chain.

**Comment by ricemaster** [comment]
Thanks @mikeb01 ,that's really helpful. Maybe it should be mentioned in 'Getting Started' part.

**Comment by mikeb01** [comment]
Good call, I'll make a note to update the documentation.

**Comment by javastuff-sam** [comment]
Thanks for the hint. I struggled a lot for memory issue with back to back running my program. nullifying reference fields helped. Additionally I also observed that nullifying ringbuffer on completion is also needed.

**Comment by mascanc** [comment]
Mike, did you update the Getting Start guide about the two enhancements suggested? I can't find anything.

**Comment by mikeb01** [comment]
Can you raise a separate issue on the problem that you are seeing.  I think I know what it is, but I would like to track it separately.

**Comment by mascanc** [comment]
Hi @mikeb01 , do you have an updated documentation on how to clean the resources after executing the handler? I'm facing yet again another memory leak!

**Comment by mascanc** [comment]
Found it by looking at the log4j2 source code. In the onEvent of the EventHandler, I added a method clear() which is nullifying all the fields of the Event. Method clear() of the RingBufferLogEvent.java. I would really suggest io @mikeb01  to add it in the manual, since it is a bit important for the developers!

**Comment by mikeb01** [comment]
Documentation is now on the wiki.
