### ISSUE TITLE
It is possible to Shutdown and restart a Disruptor?

### ISSUE THREAD

**Issue by joaquindiez** [LMAX-Exchange/disruptor#132]
I have been playing around with Disruptor, I have define a process but I need to reuse the Process that uses the Disruptor Object, so after doing a disruptor.shutdown() would be great to be able to do an disruptor.start() but I get an exception.

java.lang.IllegalStateException: Disruptor.start() must only be called once.    at com.lmax.disruptor.dsl.Disruptor.checkOnlyStartedOnce(Disruptor.java:493)    at com.lmax.disruptor.dsl.Disruptor.start(Disruptor.java:296)   at lt.jotun.AbstractJotun.init(AbstractJotun.java:111)  at lt.jotun.SingleJotunTask.run(SingleJotunTask.java:103)   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)  at java.lang.Thread.run(Thread.java:745) 
java.lang.IllegalStateException: Disruptor.start() must only be called once.
    at com.lmax.disruptor.dsl.Disruptor.checkOnlyStartedOnce(Disruptor.java:493)
    at com.lmax.disruptor.dsl.Disruptor.start(Disruptor.java:296)
    at lt.jotun.AbstractJotun.init(AbstractJotun.java:111)
    at lt.jotun.SingleJotunTask.run(SingleJotunTask.java:103)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by sj-jafari** [comment]
Is this feature added to Disruptor?
I also have a scenario of multiple consumers and a producer. suppose a logical error occurs in my message production procedure and I have to purge all the queued messages in disruptor, kill all handlers, reset sequence numbers and finally go for a fresh start with disruptor and handlers. 
I can't quite find my way around it.

**Comment by mikeb01** [comment]
Once you have killed off all of the handlers, currently the best (only) approach is to create a new instance of the Disruptor with a fresh ring buffer.  In a number of ways this is probably safer than trying to clear out and restart an existing Disruptor instance.  This way there is less cleanup work required therefore less that can go wrong.

**Comment by sj-jafari** [comment]
I understand the risks.
But about killing the handlers, I suppose the default way of managing threads in Disruptor is using a DeaemonThreadFactory. Executors used to be allowed but they have been announced deprecated recently (which I find it a reasonable decision according to [this issue](https://github.com/LMAX-Exchange/disruptor/issues/148)).
However, this way disruptor manages the threads internally and they are not visible to outer objects. Is there a way to access the handler threads from disruptor? 
Or should I take another approach like killing the handlers inside themselves or coming up with a custom ThreadFactory which can keep the track of threads?

Best, Jalal.

**Comment by mikeb01** [comment]
Tracking the thread via their construction from within a thread factory is a good thing to do.  You can then stop the Disruptor without waiting for events to drain by doing Disruptor.halt.  Assuming none of the threads have gone into an endless loop, you can then join all of the threads to make sure they have completed.

**Comment by grumpyjames** [comment]
We marked this as a feature request with an eye on implementing it in 4.0 or later. In reality, the development of this library is mostly driven by our needs of the project internally, and we don't have this requirement at all right now. We would consider pull requests that worked in this direction, but until we do, this issue seems redundant, and so it shall be closed.
