### ISSUE TITLE
Replace hand rolled performance testing with JMH benchmarks

### ISSUE THREAD

**Issue by nitsanw** [LMAX-Exchange/disruptor#134]
Because JMH is super fine ;-)
This is a tricky because the disruptor offers a notionally blocking API which does not sit entirely well with the way JMH works. I have some ideas and will submit as a PR if there's interest.

**Comment by mikeb01** [comment]
I've been working on some of these.  The Disruptor has both blocking and non-blocking APIs.  I'll get my versions committed soon as a starting point.

**Comment by nitsanw** [comment]
any news on this?

**Comment by mikeb01** [comment]
Sorry haven't had much of a chance to look at it.  I'll make sure what I've done so far is committed tomorrow.

**Comment by mikeb01** [comment]
I've committed the 2 multi-producer benchmarks (https://github.com/mikeb01/disruptor-benchmarks).  One is measured at the producer, the other is measured as the consumer only.  The producer measured one gives similar results to my hand-rolled version, the consumer measured is one gives very strange results.

**Comment by mikeb01** [comment]
I'm going to close this.  I'm unlikely to get the time to rework all of the performance tests and I'm reasonably confident in the results they provide.
