### ISSUE TITLE
Why not expose new Disruptor<>(RingBuffer, ExecutorService);

### ISSUE THREAD

**Issue by wenerme** [LMAX-Exchange/disruptor#135]
With a exist `RingBuffer`, I want to use the DSL to define the process, so, I want to use 
```
Disruptor<ChangeEvent> disruptor = new Disruptor<>(buffer, executor);
```

But this ctor is private, is there any reason to hide this ?

**Comment by mikeb01** [comment]
It's probably legacy.  However, I want I'm in the process of deprecating and removing the use of an Executor for starting threads and moving toward callers supplying `ThreadFactory` implementations.  Given this I could expose a `public Disruptor(RingBuffer<T> ringBuffer, ThreadFactory threadFactory)` constructor.  The caveat is that if you add any gating sequences to the `RingBuffer` before constructing the Disruptor, the can't be managed by the DSL.

**Comment by ajsutton** [comment]
I suspect most of the guarantees the Disruptor class provides become very shaky when you use a pre-configured ring buffer.

I guess the real question is - why do you have a pre-existing ring buffer?  Why not just create a Disruptor?

**Comment by wenerme** [comment]
😄,I forgot that, I will change the ringBuffer reference to Disruptor.So, the best and recommended way is use Disruptor instead of RingBuffer, Disruptor is not just a DSL.

**Comment by mikeb01** [comment]
If the DSL works for your use case, then it is the best approach.  There are some more advanced cases where it is not applicable, but over time those should migrate into the DSL as they mature.

**Comment by wenerme** [comment]
Why I want `new Disruptor<>(buffer, executor);` is because I want to use the DLS after the disruptor is started. Is this possible ?
