### ISSUE TITLE
How to bind a certain processor to a certain thread

### ISSUE THREAD

**Issue by soyvv** [LMAX-Exchange/disruptor#137]
Hi,
Is it possible to bind a certain processing task (a consumer) to a specified thread (so that the consumer will be guaranteed to run on the same thread for every data item)? Currently it seems that I don't have too much control about how the threads are created/bound besides assigning an Executor when creating a disruptor. 

The reason for this requirement is that I'm using some JNI lib which requires all the method calling be in the same thread. I would be nice to have some interface in which I can plug in some thread-dispatch-policy upon creation. 

Thanks in advance. 

Zhikai

**Comment by mikeb01** [comment]
You can use the LifecycleAware interface which will call you back when the handler first starts.  Have your EventHandler class implement that interface and do the bind within that callback.  I should have some better examples of this coming through soon.
