### ISSUE TITLE
100% CPU util in BlockingWaitStrategy.waitFor

### ISSUE THREAD

**Issue by ajayl** [LMAX-Exchange/disruptor#149]
I am running scale test on a product which uses Disruptor library. After running the test, CPU util of 1 CPU stays at 100%. Threaddump shows below thread hogging the CPU. Works fine in non-scale scenarios

Library version used is 3.3.2 and system is Ubuntu 14.04, 64-bit quad-core, 8GB RAM with Java 7

Is this a issue with the library or application code calling it? Any tips to debug further?

Before running the test:

"pool-28-thread-2" prio=10 tid=0x00007f6c9c566000 nid=0x2b38 waiting on condition [0x00007f6c7c464000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000785babe80> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
        at com.lmax.disruptor.BlockingWaitStrategy.waitFor(BlockingWaitStrategy.java:45)
        at com.lmax.disruptor.PhasedBackoffWaitStrategy.waitFor(PhasedBackoffWaitStrategy.java:102)
        at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:55)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

After running the test:

"pool-28-thread-2" prio=10 tid=0x00007f6c9c566000 nid=0x2b38 runnable [0x00007f6c7c464000]
   java.lang.Thread.State: RUNNABLE
        at com.lmax.disruptor.BlockingWaitStrategy.waitFor(BlockingWaitStrategy.java:56)
        at com.lmax.disruptor.PhasedBackoffWaitStrategy.waitFor(PhasedBackoffWaitStrategy.java:102)
        at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:55)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

**Comment by mikeb01** [comment]
You can get high CPU usage when you have dependent consumer set up with dependencies between them.  If EventHandler B depends on EventHandler A, between the point where A receives the messages and when it completes process so that B can then process it, B will busy wait.

If this is particularly problematic, i.e. the EventHandler being depended upon (i.e. A) is quite slow causing significant CPU usage, then a better approach is to have 2 disruptors such that A will receive messages from the first disruptor and publish to the second disruptor which will be listened by EventHandler B.  This may increase your end to end latency.

You'll need to make a trade off between latency and CPU usage.

**Comment by ajayl** [comment]
In my test, the CPU util stays at 100% even after the scale test is completed. The scale test loads the app for half a min. and then stops but the CPU util continues to stay at 100% forever. I am fairly new to this so will need to dig deeper to understand your comment, but can that also explain why the CPU continues to stay high?

**Comment by mikeb01** [comment]
There is probably an event that hasn't completed processing.  I would include some sort of test to make sure all of the messages have completed correctly.  Also you can inspect the sequences of the various consumers and make sure that they have process all of the messages.

**Comment by ajayl** [comment]
Thx Mike. I will debug it further on the app side. Making the issue closed

**Comment by themass** [comment]
the same problem 


   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                          
194792 www       20   0 23.873g 5.223g  22652 R 99.9  8.3  34:23.45 java                                                                                                                             
194797 www       20   0 23.873g 5.223g  22652 R 99.9  8.3  34:27.43 java                                                                                                                             
194793 www       20   0 23.873g 5.223g  22652 R 99.9  8.3  34:27.42 java                                                                                                                             
  4794 www       20   0 23.873g 5.223g  22652 R 99.9  8.3  34:27.37 java                                                                                                                             
▽94795 www       20   0 23.873g 5.223g  22652 R 99.9  8.3  34:27.35 java                                                                                                                             
194798 www       20   0 23.873g 5.223g  22652 R 99.9  8.3  34:27.34 java                                                                                                                             
194799 www       20   0 23.873g 5.223g  22652 R 99.9  8.3  34:27.32 java                                                                                                                             
194800 www       20   0 23.873g 5.223g  22652 R 99.9  8.3  34:27.33 java 


Thread 194794: (state = IN_JAVA)
 - com.lmax.disruptor.BlockingWaitStrategy.waitFor(long, com.lmax.disruptor.Sequence, com.lmax.disruptor.Sequence, com.lmax.disruptor.SequenceBarrier) @bci=92, line=56 (Compiled frame; information
may be imprecise)
 - com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(long) @bci=18, line=56 (Compiled frame)
 - com.lmax.disruptor.BatchEventProcessor.run() @bci=52, line=124 (Compiled frame)
 - java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) @bci=95, line=1145 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor$Worker.run() @bci=5, line=615 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=745 (Interpreted frame)


Thread 194793: (state = IN_JAVA)
 - com.lmax.disruptor.BlockingWaitStrategy.waitFor(long, com.lmax.disruptor.Sequence, com.lmax.disruptor.Sequence, com.lmax.disruptor.SequenceBarrier) @bci=92, line=56 (Compiled frame; information
may be imprecise)
 - com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(long) @bci=18, line=56 (Compiled frame)
 - com.lmax.disruptor.BatchEventProcessor.run() @bci=52, line=124 (Compiled frame)
 - java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) @bci=95, line=1145 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor$Worker.run() @bci=5, line=615 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=745 (Interpreted frame)


Thread 194792: (state = IN_JAVA)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.release(int) @bci=26, line=1263 (Compiled frame; information may be imprecise)
 - java.util.concurrent.locks.ReentrantLock.unlock() @bci=5, line=460 (Compiled frame)
 - com.lmax.disruptor.BlockingWaitStrategy.waitFor(long, com.lmax.disruptor.Sequence, com.lmax.disruptor.Sequence, com.lmax.disruptor.SequenceBarrier) @bci=50, line=50 (Compiled frame)
 - com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(long) @bci=18, line=56 (Compiled frame)
 - com.lmax.disruptor.BatchEventProcessor.run() @bci=52, line=124 (Compiled frame)
 - java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) @bci=95, line=1145 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor$Worker.run() @bci=5, line=615 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=745 (Interpreted frame)


Thread 194791: (state = BLOCKED)
 - sun.misc.Unsafe.park(boolean, long) @bci=0 (Compiled frame; information may be imprecise)
 - java.util.concurrent.locks.LockSupport.park(java.lang.Object) @bci=14, line=186 (Compiled frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await() @bci=42, line=2043 (Compiled frame)
 - com.lmax.disruptor.BlockingWaitStrategy.waitFor(long, com.lmax.disruptor.Sequence, com.lmax.disruptor.Sequence, com.lmax.disruptor.SequenceBarrier) @bci=38, line=45 (Compiled frame)
 - com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(long) @bci=18, line=56 (Compiled frame)
 - com.lmax.disruptor.BatchEventProcessor.run() @bci=52, line=124 (Compiled frame)
 - java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) @bci=95, line=1145 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor$Worker.run() @bci=5, line=615 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=745 (Interpreted frame)

**Comment by mikeb01** [comment]
This will be the result of an EventHandler that being depended on hasn't completed or is particularly slow.  I would ensure that you have appropriate logging set up to insure that the handler hasn't exited ab-normally.  You should also monitor the sequences of your handlers to see which ones aren't moving forward.

Also you should upgrade to the latest release, just to be safe.

**Comment by themass** [comment]
my version  is 3.3.6; and jdk 1.7.0_80-b15; linux 64 server; 
no EventHandler  depandes each other;

   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                           
  8745 www       20   0 23.914g 4.441g  23468 R 99.9  7.1  21:31.39 java                                                                                                                              
  8747 www       20   0 23.914g 4.441g  23468 R 99.9  7.1  21:31.36 java                                                                                                                              
  8748 www       20   0 23.914g 4.441g  23468 R 99.9  7.1  21:31.39 java                                                                                                                              
  8744 www       20   0 23.914g 4.441g  23468 R 99.9  7.1  21:30.83 java                                                                                                                              
  8746 www       20   0 23.914g 4.441g  23468 R 99.9  7.1  21:31.38 java                                                                                                                              
  8749 www       20   0 23.914g 4.441g  23468 R 99.9  7.1  21:31.35 java                                                                                                                              
  8750 www       20   0 23.914g 4.441g  23468 R 99.9  7.1  21:31.35 java                                                                                                                              
  8751 www       20   0 23.914g 4.441g  23468 R 99.9  7.1  21:31.35 java                                                                                                                              
  8887 www       20   0 23.914g 4.441g  23468 R 99.9  7.1  79:29.79 java                                                                                                                              
  8684 www       20   0 23.914g 4.441g  23468 S  6.2  7.1   0:00.70 java                                                                                                                              
  7641 www       20   0 23.914g 4.441g  23468 S  0.0  7.1   0:00.00 java                                                                                                                              
  7643 www       20   0 23.914g 4.441g  23468 S  0.0  7.1   0:01.61 java                                                                                                                              
  7644 www       20   0 23.914g 4.441g  23468 S  0.0  7.1   0:07.48 java                                                                                                                              
  7645 www       20   0 23.914g 4.441g  23468 S  0.0  7.1   0:07.51 java                                                                                                                              
  7647 www       20   0 23.914g 4.441g  23468 S  0.0  7.1   0:07.51 java                  

Thread 8750: (state = IN_JAVA)
 - java.util.concurrent.locks.LockSupport.unpark(java.lang.Thread) @bci=8, line=152 (Compiled frame; information may be imprecise)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.unparkSuccessor(java.util.concurrent.locks.AbstractQueuedSynchronizer$Node) @bci=80, line=662 (Compiled frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.release(int) @bci=26, line=1263 (Compiled frame)
 - java.util.concurrent.locks.ReentrantLock.unlock() @bci=5, line=460 (Compiled frame)
 - com.lmax.disruptor.BlockingWaitStrategy.waitFor(long, com.lmax.disruptor.Sequence, com.lmax.disruptor.Sequence, com.lmax.disruptor.SequenceBarrier) @bci=50, line=50 (Compiled frame)
 - com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(long) @bci=18, line=56 (Interpreted frame)
 - com.lmax.disruptor.BatchEventProcessor.run() @bci=52, line=124 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) @bci=95, line=1145 (Interpreted frame)


Thread 8749: (state = IN_JAVA)
 - com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(long) @bci=18, line=56 (Interpreted frame)
 - com.lmax.disruptor.BatchEventProcessor.run() @bci=52, line=124 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) @bci=95, line=1145 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor$Worker.run() @bci=5, line=615 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=745 (Interpreted frame)


Thread 8748: (state = IN_JAVA)
 - com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(long) @bci=18, line=56 (Interpreted frame)
 - com.lmax.disruptor.BatchEventProcessor.run() @bci=52, line=124 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) @bci=95, line=1145 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor$Worker.run() @bci=5, line=615 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=745 (Interpreted frame)


Thread 8747: (state = IN_JAVA)
 - java.util.concurrent.locks.LockSupport.unpark(java.lang.Thread) @bci=8, line=152 (Compiled frame; information may be imprecise)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.unparkSuccessor(java.util.concurrent.locks.AbstractQueuedSynchronizer$Node) @bci=80, line=662 (Compiled frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.release(int) @bci=26, line=1263 (Compiled frame)
 - java.util.concurrent.locks.ReentrantLock.unlock() @bci=5, line=460 (Compiled frame)
 - com.lmax.disruptor.BlockingWaitStrategy.waitFor(long, com.lmax.disruptor.Sequence, com.lmax.disruptor.Sequence, com.lmax.disruptor.SequenceBarrier) @bci=50, line=50 (Compiled frame)
 - com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(long) @bci=18, line=56 (Interpreted frame)
 - com.lmax.disruptor.BatchEventProcessor.run() @bci=52, line=124 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) @bci=95, line=1145 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor$Worker.run() @bci=5, line=615 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=745 (Interpreted frame)


Thread 8746: (state = IN_JAVA)
 - com.lmax.disruptor.BlockingWaitStrategy.waitFor(long, com.lmax.disruptor.Sequence, com.lmax.disruptor.Sequence, com.lmax.disruptor.SequenceBarrier) @bci=92, line=56 (Compiled frame; information m
ay be imprecise)
 - com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(long) @bci=18, line=56 (Interpreted frame)
 - com.lmax.disruptor.BatchEventProcessor.run() @bci=52, line=124 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) @bci=95, line=1145 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor$Worker.run() @bci=5, line=615 (Interpreted frame)
 - java.lang.Thread.run() @bci=11, line=745 (Interpreted frame)


Thread 8745: (state = IN_JAVA)
 - java.util.concurrent.locks.LockSupport.unpark(java.lang.Thread) @bci=8, line=152 (Compiled frame; information may be imprecise)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.unparkSuccessor(java.util.concurrent.locks.AbstractQueuedSynchronizer$Node) @bci=80, line=662 (Compiled frame)
 - java.util.concurrent.locks.AbstractQueuedSynchronizer.release(int) @bci=26, line=1263 (Compiled frame)
 - java.util.concurrent.locks.ReentrantLock.unlock() @bci=5, line=460 (Compiled frame)
 - com.lmax.disruptor.BlockingWaitStrategy.waitFor(long, com.lmax.disruptor.Sequence, com.lmax.disruptor.Sequence, com.lmax.disruptor.SequenceBarrier) @bci=50, line=50 (Compiled frame)
 - com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(long) @bci=18, line=56 (Interpreted frame)
 - com.lmax.disruptor.BatchEventProcessor.run() @bci=52, line=124 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) @bci=95, line=1145 (Interpreted frame)
 - java.util.concurrent.ThreadPoolExecutor$Worker.run() @bci=5, line=615 (Interpreted frame)
