### ISSUE TITLE
Poor performance using two Disruptors

### ISSUE THREAD

**Issue by maseev** [LMAX-Exchange/disruptor#150]
According to the tests, Disruptor is able to process a [tremendous](https://github.com/LMAX-Exchange/disruptor/wiki/Performance-Results#throughput-performance-testing) amount of data [extremely](https://github.com/LMAX-Exchange/disruptor/wiki/Performance-Results#latency-performance-testing) fast. 

I created a simple [application](https://github.com/maseev/disruptor) which sets up two disruptors and measures latency while passing objects between event handlers. Basically, the application fires up two disruptors, one by using WorkerPool (with two event handlers), and another one with one event handler. Then, the main thread publishes 1 million messages (with timestamps) to the first ring buffer. Two event handlers constantly process events from the first ring buffer, set timestamps to the event messages and pass them to the second ring buffer. In the end, we've got a single event handler which retrieves events from the second ring buffer and collects all timestamps in the array list.

Here's what I get when I run the test several times:

```
-----------------------------------------------------------------------------------------------
Minimum PUBLISH -> FIRST RING BUFFER:            2870 ns
Maximum PUBLISH -> FIRST RING BUFFER:            73441059 ns
Average PUBLISH -> FIRST RING BUFFER:            46477426 ns
Minimum FIRST RING BUFFER -> SECOND RING BUFFER: 64 ns
Maximum FIRST RING BUFFER -> SECOND RING BUFFER: 30200760 ns
Average FIRST RING BUFFER -> SECOND RING BUFFER: 5769718 ns
-----------------------------------------------------------------------------------------------
Another one? (type something and hit Enter): a
-----------------------------------------------------------------------------------------------
Minimum PUBLISH -> FIRST RING BUFFER:            1272 ns
Maximum PUBLISH -> FIRST RING BUFFER:            45139608 ns
Average PUBLISH -> FIRST RING BUFFER:            24340161 ns
Minimum FIRST RING BUFFER -> SECOND RING BUFFER: 74 ns
Maximum FIRST RING BUFFER -> SECOND RING BUFFER: 11518529 ns
Average FIRST RING BUFFER -> SECOND RING BUFFER: 2185025 ns
-----------------------------------------------------------------------------------------------
Another one? (type something and hit Enter): a
-----------------------------------------------------------------------------------------------
Minimum PUBLISH -> FIRST RING BUFFER:            269 ns
Maximum PUBLISH -> FIRST RING BUFFER:            24095393 ns
Average PUBLISH -> FIRST RING BUFFER:            4364858 ns
Minimum FIRST RING BUFFER -> SECOND RING BUFFER: 49952 ns
Maximum FIRST RING BUFFER -> SECOND RING BUFFER: 79807127 ns
Average FIRST RING BUFFER -> SECOND RING BUFFER: 47707583 ns
-----------------------------------------------------------------------------------------------
Another one? (type something and hit Enter): a
-----------------------------------------------------------------------------------------------
Minimum PUBLISH -> FIRST RING BUFFER:            193 ns
Maximum PUBLISH -> FIRST RING BUFFER:            32556794 ns
Average PUBLISH -> FIRST RING BUFFER:            10875301 ns
Minimum FIRST RING BUFFER -> SECOND RING BUFFER: 7332523 ns
Maximum FIRST RING BUFFER -> SECOND RING BUFFER: 28520199 ns
Average FIRST RING BUFFER -> SECOND RING BUFFER: 18535076 ns
-----------------------------------------------------------------------------------------------
```

To be honest, these numbers are bit disappointing compared to those from the Disruptor performance page. I expected the result would be much better because I simply have no heavy logic in the event handlers (the only thing I do is set timestamps and publish messages to the next ring buffer).
There's definitely something wrong here. Am I missing something?

About hardware/OS:
CPU: Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
RAM: 16 GB
OS: Linux evilmachine 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

You can build and run the project yourself. Grab the code from [here](https://github.com/maseev/disruptor). Build it with ``` mvn clean assembly:assembly ```. Run it with ``` java -jar /target/delivery/disruptor.jar ```

**Comment by mikeb01** [comment]
I haven't run the code yet, but I have a couple of comments on the benchmark.

1. You're measuring latency, but running the system to saturation.  If within your test your producer can out pace the consumer(s) then you will run into queuing effects.  If you are interested in measuring latency I would recommend picking a target throughput rate and measuring at that rate.
2.  If you are interested in the best performance remove the working pool and use a single-thread event handler to copy from the first ring buffer to the second.
3.  If you want to understand where the time is going, then I would recommend profiling the test and see where the biggest costs are.

**Comment by maseev** [comment]
Actually, I thought it would be much faster to process events in parallel by using WorkerPool. In the real system, I'm working on, the client sends a gigantic amount of data that can be processed in parallel. 

BTW, documentation [says](https://github.com/LMAX-Exchange/disruptor/wiki/Frequently-Asked-Questions#how-do-you-arrange-a-disruptor-with-multiple-consumers-so-that-each-event-is-only-consumed-once) that if I'd like 3X performance I can use WorkerPool, which processes each event only once. But it also says if you want even better performance you can use that trick with dropping events that don't belong to a particular event handler. 

It seems that the latter approach, for some reason, is much performant than the WorkerPool even though you have to multicast each message to every event handler.

**Comment by mikeb01** [comment]
The difficulty with the WorkerPool is that it you need to have a contended counter to ensure that each Worker see an independent set of events (https://github.com/LMAX-Exchange/disruptor/blob/master/src/main/java/com/lmax/disruptor/WorkProcessor.java#L137).  This limits the scalability of the code.  Especially if this is running as part of a benchmark where the Worker computation is very small.  In this case the benchmark would probably spend most of it's time on the contended compare and set operation.

I'm not sure where that 3X in that FAQ section comes from (probably an old comparison with a queue implementation), but it is quite misleading and I'll remove it.

**Comment by maseev** [comment]
Ok. Let's sum it up. If I understand you correctly, WorkerPool is the best choice if your WorkHandler logic takes quite a lot of time in order to process a single event. On the other if my event processing logic takes very little time, it's better to stay with the so-called stripped EventHandler approach, where you basically multicast events to all event handlers and filter events later. Is that right?

**Comment by mikeb01** [comment]
There are a couple of other things to bear in mind, "quite a lot of time" is not really a strong definition, so with everything performance related you should benchmark with your own application code in place and try various options to find the appropriate solution for your system.  The other area where the WorkerPool can help is if the processing time can have quite a high amount of variability as the load will be distributed across the workers in the pool, where as the "striped" approach can lead to head of line blocking.  Also the WorkHandlers can implement the EventReleaseAware interface that allows the WorkHandler to copy out the data from event then release the sequence before beginning a potentially long computation.  This will also prevent the entire ring buffer being held up behind a single long computation.

**Comment by maseev** [comment]
Wow, I didn't know about EventReleaseAware interface. I mean, I didn't see it in the documentation. It's definitely worth trying to use it and measure the latency. Don't you think this information should be in the project's wiki? I think it would save a lot of time for newcomers.

**Comment by mikeb01** [comment]
Yes, there is still a bit to do documentation to get done, it's on my list.

**Comment by maseev** [comment]
Thanks for your help, Michael.
