### ISSUE TITLE
ByteBuffer wrappers

### ISSUE THREAD

**Issue by mfarrugi** [LMAX-Exchange/disruptor#151]
Has copying passing around wrapped byte buffers been benchmarked? Is this worth looking at? This is the approach the OpenHFT/chronicle libs take. It seems like you would win on copying speed, but maybe not on accessing fields. 

eg.
```
public final class ValueEvent
{
    private ByteBuffer wrapped;   
    public long getLong() { return wrapped.getLong(0); }
}

```
---
On a more careful reading this seems beyond the scope of the library, but I suppose I'm still curious if this has been benchmarked already and/or worth including as an example.

**Comment by mikeb01** [comment]
Not specifically, but it is a good option if you want to support a number of different message types in the same ring buffer.  An example that I implemented for a conference uses that approach: https://github.com/mikeb01/ticketing.  It is a bit dated now, but the principal is reasonably sound.

**Comment by mikeb01** [comment]
Given this is not really an issue, I'm going to close.  Feel free to discuss further on the mailing list.
