### ISSUE TITLE
CPU at 100% when using BlockingWaitStrategy

### ISSUE THREAD

**Issue by dingwa** [LMAX-Exchange/disruptor#155]
Hi,

We are using the Disruptor to send events to various parts of our application, when our server starts sometimes the CPU spikes up and stays at 100%, however in other times the CPU sits idle at 3 - 5% (which is normal).  I would normally see this as something in the application timing or otherwise that would cause this issue.  However I have dug a little deeper into this and run some monitoring tools like jvmtop (https://github.com/patric-r/jvmtop) and it looks like my WorkerPool threads (10 threads) are spinning despite using the BlockingWaitStrategy.  Could this be somewhat related to https://github.com/LMAX-Exchange/disruptor/issues/149?

Environment:
Java: 1.7.0_71
Disruptor: 3.3.4

Below are jstack traces for my threads (only including stacktrace for 1 thread in each usecase for brevity, however all threads show the exact stacktrace):

**Spinning thread causing 100% CPU**
`"Outgoing Worker-thread-9" prio=10 tid=0x00007f2d8d65e800 nid=0x64fd runnable [0x00007f2d7a4c2000]
  java.lang.Thread.State: RUNNABLE
       at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
       at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:144)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
       at java.lang.Thread.run(Thread.java:745)`

**Idle thread causing 3-5% CPU**
`"Outgoing Worker-thread-10" prio=10 tid=0x00007f441d667800 nid=0x7887 waiting on condition [0x00007f4408866000]
  java.lang.Thread.State: WAITING (parking)
       at sun.misc.Unsafe.park(Native Method)
       - parking to wait for  <0x00000007030168c8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
       at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
       at com.lmax.disruptor.BlockingWaitStrategy.waitFor(BlockingWaitStrategy.java:45)
       at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
       at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:144)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
       at java.lang.Thread.run(Thread.java:745)`

I setup the RingBuffer / WorkerPool using the following code:

`this.executorService = Executors.newFixedThreadPool(numberOfOutgoingWorkers, threadFactory);
		
		this.dispatchEventHandlerWorkers = new DispatchEventHandler[numberOfOutgoingWorkers];
		for (int i = 0; i < numberOfOutgoingWorkers; i++) {
			this.dispatchEventHandlerWorkers[i] = new DispatchEventHandler();
		}
		
		this.ringBuffer = RingBuffer.createMultiProducer(DispatchItemHolder.EVENT_FACTORY, dispatchQueueCapacity, new BlockingWaitStrategy());
		SequenceBarrier barrier = this.ringBuffer.newBarrier();
		
		this.workerPool = new WorkerPool<>(this.ringBuffer, barrier, new Slf4jIgnoreExceptionHandler(), this.dispatchEventHandlerWorkers);
		this.workerPool.start(this.executorService);`

The RingBuffer itself is still fully operational.  It is still able to both accept events, and dispatch them via the WorkerPool.  It is just that my WorkerPool threads are spinning.  Is there anything within Disruptor itself that could cause the WorkerPool threads to not honour the WaitStrategy?

**Comment by mikeb01** [comment]
Do you have a cut down example that shows the issue?  There are a couple of cases where this could occur, but I'd like to see your specific case.

**Comment by dingwa** [comment]
Thanks for your quick reply.  Unfortunately this only happens in our production environment and its not something that I can easily reproduce.  The code above is all the code we use to create the RingBuffer and WorkerPool.  Unfortunately I'm not too sure how I could potentially provide a cutdown example at the moment, but its something that we see regularly in just our production environment so I can run some more diagnostics if required.

Do you have any clues on how this could happen from your side to see if it could spark me off?

**Comment by wallacehsh** [comment]
Would you mind tell me what is your OS and hardware ?
I have some memory barrier issue in RH 6.6.

**Comment by dingwa** [comment]
Hardware: Intel Xeon E7, xv/Xeon E5 v2/Core i7
OS: Red Hat 6.7

**Comment by wallacehsh** [comment]
mm... Hardware is similarly( We use HP DL380 gen9), they are all Haswell servers.
We have CPU problem when OS is RH 6.6(first version), cause RH 6.6(first version) have memory barrier issue.
We fix the issue via update the latest hotfix(6.6 latest version is OK ) and upgrade to  RH 6.7.(latest version)

So, My next question is what sub-version is your RH 6.7?

In disruptor, memory barrier is very important, so I just remind you that maybe your OS is issue root cause.

By the way, RH support is so so sucks.

**Comment by dingwa** [comment]
Yes - interestingly, this only happens on our Prod env at a certain part of the day (scheduled daily bounce?!)

Normally all 10 worker threads are blocked as part of the BlockedWaitStrategy, however this morning I saw that only 7/10 threads were blocked, the rest (3) were running as per the associated stacktraces above

Apologies, not quite familar with retrieving the sub-version.  Is this what you're looking for?

Linux version 2.6.32-573.26.1.el6.x86_64 (mockbuild@x86-027.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) ) #1 SMP Tue Apr 12 01:47:01 EDT 2016

**Comment by mikeb01** [comment]
Would it be possible to capture a number of stack traces when the code is stuck at 100%.  The stack trace shown doesn't show where within the BlockWaitStrategy waitFor method is spinning.

**Comment by dingwa** [comment]
Just to make sure I get you what you need, do you want this over time? Or across multiple WorkerPool threads at the same time?  I'm currently using jstack to capture the stacktrace at the moment.  Let me know if there is something else that you want me to use to give you more information.  I'll try to get it for you.

**Comment by mikeb01** [comment]
I think I need multiple results.  I can't see from the stack trace provided exactly where it is spinning.  There are a number of places where this could happen with the referenced method.  I am hoping that this is a timing thing.  If we could see 5-10 jstack traced of the spinning thread that might show up the location of the issue.

It is possible that we are seeing as much detail as we can already (long discussion about safepoints would explain why), but doing the above investigation would help determine that too.

**Comment by dingwa** [comment]
Ok.  I've tried to perform a naive 'while true, jstack, sleep 1' loop, but the traces looked to be exactly the same.  I'll run it again for longer to see if I can generate a slightly different trace for the spinning thread

**Comment by dingwa** [comment]
I have just seen this issue today.  After taking jstacks for 5 minutes without sleeping, the stacktraces for the spinning threads (7 out of 10 in this case) are all the same, but slightly different stacktrace to the original one posted, 

`Outgoing Worker-thread-9" prio=10 tid=0x00007f6c09628000 nid=0x34b1 runnable [0x00007f6bf5c90000]
   java.lang.Thread.State: RUNNABLE
        at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:159)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)`

The standard 'bounce' of the application server 'fixed' the problem again.

Interestingly, running version 3.3.4, the line the stacktraces are on is WorkProcessor.java:159 which points to an end } it seems

**Comment by mikeb01** [comment]
Are you perhaps running the latest from the git repo?

**Comment by dingwa** [comment]
It came via gradlew mavenCentral, which looks like here

http://mvnrepository.com/artifact/com.lmax/disruptor/3.3.4

I've just pulled down the file and the decompiled version's line numbers of the WorkProcessor correlate...

**Comment by dingwa** [comment]
Just some further observations.  I ran the jstack command over a longer period and tried to enact some load on our server.  9 of the 10 threads were in a spinning state, leaving only one thread in a normal blocked state when idle.

However when I login to the system a flurry of messages get sent to the server, in a normal case, this load is distributed amongst the 10 threads.  Looking at today's jstack logs, only the one thread was responding to my login and interaction with the system, whilst all other threads stayed spinning.

Could there be a situation where these spinning threads are almost inaccessible to the WorkerPool itself?  Rogue threads so to speak?

**Comment by mikeb01** [comment]
Can you test again with 3.3.5?

**Comment by dingwa** [comment]
Let me give it a go.  It will take a while unfortunately as it will need to propagate through to the Prod environment.  Thanks!

**Comment by laec** [comment]
It maybe worth getting a stack trace with native frames `jstack -m` to see if you are affected by the following JVM bug:
* [Infinite loop in handle_wrong_method in jmod](https://bugs.openjdk.java.net/browse/JDK-8153134)
* [JVM stuck in SharedRuntime::handle_wrong_method with 100% CPU](https://bugs.openjdk.java.net/browse/JDK-8153342)

**Comment by dingwa** [comment]
I've just had this issue on one of our other environments which has never happened before until today running 3.3.4.  Just had this environment upgraded to 3.3.5 so I guess we'll see what happens here

@laec I've taken a jstack -m, however I'm not exactly too sure what I should be looking for.  Searching for disruptor in the jstack I can only see the following.  Is there anything else that I should be looking for, certain calls etc?

`----------------- 17109 -----------------
0x000000354220b68c      __pthread_cond_wait + 0xcc
0x00007f8559dd95a5      Unsafe_Park + 0x125
0x00007f854b185c39      * sun.misc.Unsafe.park(boolean, long) bci:0 (Interpreted frame)
0x00007f854b1730d8      * java.util.concurrent.locks.LockSupport.park(java.lang.Object) bci:14 line:186 (Interpreted frame)
0x00007f854b1730d8      * java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await() bci:42 line:2043 (Interpreted frame)
0x00007f854b173786      * com.lmax.disruptor.BlockingWaitStrategy.waitFor(long, com.lmax.disruptor.Sequence, com.lmax.disruptor.Sequence, com.lmax.disruptor.SequenceBarrier) bci:38 line:45 (Interpreted frame)
0x00007f854b1738a3      * com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(long) bci:18 line:56 (Interpreted frame)
0x00007f854b1738a3      * com.lmax.disruptor.BatchEventProcessor.run() bci:52 line:124 (Interpreted frame)
0x00007f854b173786      * java.util.concurrent.ThreadPoolExecutor.runWorker(java.util.concurrent.ThreadPoolExecutor$Worker) bci:95 line:1145 (Interpreted frame)
0x00007f854b1730d8      * java.util.concurrent.ThreadPoolExecutor$Worker.run() bci:5 line:615 (Interpreted frame)
0x00007f854b173786      * java.lang.Thread.run() bci:11 line:745 (Interpreted frame)
0x00007f854b16d4e7      <StubRoutines>
0x00007f8559a5c085      _ZN9JavaCalls11call_helperEP9JavaValueP12methodHandleP17JavaCallArgumentsP6Thread + 0x365
0x00007f8559a5aae8      _ZN9JavaCalls4callEP9JavaValue12methodHandleP17JavaCallArgumentsP6Thread + 0x28
0x00007f8559a5adb7      _ZN9JavaCalls12call_virtualEP9JavaValue11KlassHandleP6SymbolS4_P17JavaCallArgumentsP6Thread + 0x197
0x00007f8559a5aed7      _ZN9JavaCalls12call_virtualEP9JavaValue6Handle11KlassHandleP6SymbolS5_P6Thread + 0x47
0x00007f8559ad7ef5      _ZL12thread_entryP10JavaThreadP6Thread + 0xe5
0x00007f8559db592f      _ZN10JavaThread17thread_main_innerEv + 0xdf
0x00007f8559db5a35      _ZN10JavaThread3runEv + 0xf5
0x00007f8559c7c4b8      _ZL10java_startP6Thread + 0x108`
