### ISSUE TITLE
Can't ignore the rest sequencial EventHandler.

### ISSUE THREAD

**Issue by kanmt** [LMAX-Exchange/disruptor#156]
We're using sequencial EventHandler chain, such as "disruptor.handleEventsWith(handlerA).then(handlerB).then( handlerC)." 
     Now,  "handlerB" throws an exception, the Disruptor System can't work anymore, if we didn't define an ExceptionHandler for "handlerB". However, if we do define an ExceptionHandler for Disruptor or "handlerB"--there are no more diff between these two--the event who caused Exception will still be handled by "handlerC". But I think there should be some mechanism to stop all of the rest handlers to process the Event, only for this Event.

**Comment by kanmt** [comment]
![20160603115839](https://cloud.githubusercontent.com/assets/19722592/15768361/a5f540e0-2982-11e6-8e6a-93c4ec4481dc.png)

**Comment by mikeb01** [comment]
This is something that you will need to manage yourself.  The simplest solution would be to include flags on the message for each of the handlers to indicate that processing succeeded.  Then each subsequent handler could check the appropriate flags.

The only thing that passed between the handlers is the sequence number and your event data.  As the event data is opaque to the Disruptor we can't include this information ourselves.

**Comment by kanmt** [comment]
@mikeb01 This is what we done in our system now. But I think why Disruptor not supply mechanism to do such things?
If we have lot of Handlers, Then we need to add an abstract class to check the flag, I dont think it's the best graceful way to handle this problem.

**Comment by mikeb01** [comment]
Because it has a cost.  There would need to be additional data transferred between the event handlers and logic for handling it.  Many users of the Disruptor do not want to pay for a feature that they do not use (like us).  Given that layering that sort of feature on top of the Disruptor is very simple it's not worth adding.
