### ISSUE TITLE
I think "BUFFER_PAD is 128 bytes in RingBuffer" is not necessary.

### ISSUE THREAD

**Issue by zhupengcheng** [LMAX-Exchange/disruptor#158]
in RingBuffer line 51:  
   BUFFER_PAD = 128 / scale;   

 I think 64 is enough~~  is Right? 3ks

**Comment by mikeb01** [comment]
128 is cater for adjacent cache line pre-fetching.  

https://software.intel.com/en-us/articles/optimizing-application-performance-on-intel-coret-microarchitecture-using-hardware-implemented-prefetchers
