### ISSUE TITLE
full gc 

### ISSUE THREAD

**Issue by pengfei-xu** [LMAX-Exchange/disruptor#160]
int conThreadNum = 512;
        int conBufferSize = 1024 * 1024;
        this.concurrentExecutor = Executors.newFixedThreadPool(conThreadNum, new ThreadFactory() {
            final AtomicInteger seq = new AtomicInteger(0);

            public Thread newThread(Runnable r) {
                return new Thread(r, "CommandBus-concurrency-Consumer-" + seq.getAndIncrement());
            }
        });

        this.conDisruptor = new Disruptor<>(
                CommandEvent.COMMAND_EVENT_FACTORY, conBufferSize, this.concurrentExecutor, ProducerType.SINGLE, new BlockingWaitStrategy()
        );
        WorkHandler[] handlers = new WorkHandler[conThreadNum];
        Arrays.fill(handlers, new WorkHandler<CommandEvent>() {

            @Override
            public void onEvent(CommandEvent event) throws Exception {
                handleCommandEvent(event);
            }
        });
        conDisruptor.handleEventsWithWorkerPool(handlers);
        conDisruptor.handleExceptionsWith(new CommandEventExceptionHandler<>("commandBus-Concurrency-Disruptor"));

  public boolean publish(EventEnum cmd, Command event) {
        long seq = conRingBuffer.next();
        try {
            CommandEvent commandEvent = conRingBuffer.get(seq);
            commandEvent.command = event;
            commandEvent.type = cmd;
        } finally {
            conRingBuffer.publish(seq);
            return true;
        }
    }

**Comment by mikeb01** [comment]
Is there a specific question or issue here?

**Comment by pengfei-xu** [comment]
yes , it cause full gc . dump gc see ringBuffer also full . i do not kown where this case  cause it .

**Comment by mikeb01** [comment]
How you application behaves depends a lot on how you are actually producing messages.  E.g. is the rate of message production exceeding the rate at which you consume.  The other things of note is that I don't know what handleCommandEvent is doing.  If this is a CPU bound operation, then creating 512 workers is probably too many, unless you are running on a 512+ core machine.  Even if that operation is IO bound then 512 is probably too high.  You are also creating quite a large buffer (1,000,000+) plus items.  Also how is the Command object being creating.  From this code it would suggest that you are allocating a new one for each publication.  If that is the case, then you should make sure you set the CommandEvent.command field to null after processing the message.  Then I would try reducing the number of works and the size of the ring buffer and seeing how your application behaves.

It is also unclear how big the Command object is.  Given that the ring buffer can hold 1,000,000+ objects you also may simply not have enough memory to hold them all.

**Comment by Diracnote** [comment]
@pengfei-xu 
set the value of event to null after you handle it, distruptor dosent clean it which will stay in memory

**Comment by mikeb01** [comment]
Closing due to lack for further information.

**Comment by pengfei-xu** [comment]
@mikeb01   thanks  . reducing the number of works and the size of the ring buffer  is  ok
