### ISSUE TITLE
Is there a supported way to preserve ordering in a diamond configuration?

### ISSUE THREAD

**Issue by ennerf** [LMAX-Exchange/disruptor#163]
I have a use case where I need to analyze sensor data from binary logs. The decoding of individual data messages is by far the most computationally intensive step, so I'm considering arranging multiple decoders in a diamond configuration, e.g.,

P1 (input) => C1,2,3,4 (decoders) => C5 (analysis)

Since the data needs to be analyzed in order, I was wondering whether there is a supported way to maintain the sequence number of P1 in C5.

Example code:

    public void onEvent(final ValueEvent entry, final long sequence, final boolean onEndOfBatch)
    {
        if ((sequence % numberOfConsumers) == ordinal)
        {
            // Decode message coming from P1
            // ...

            // Publish on C5
            sequence = c5.next(); // <-- I'd like to use the original sequence instead
            event = c5.get(sequence);
            // ... populate event ... 
            c5.publish(sequence);

        }
    }

To me this seems like it'd be a fairly common use case. I've looked through much of the documentation, but couldn't find an appropriate solution. Could you provide some hints on how to best do this? Thank you.

**Comment by SamBarker** [comment]
Ordering will be preserved by default assuming C5 is marked as a downstream handler. As C5 is gated on the min sequence of C1-4. So while C1 is processing the first event C2-4 will increase there sequences however C5 will not be triggered until C1 has completed processing.
