### ISSUE TITLE
How does one wait for all event handlers to fully complete processing after shutdown?

### ISSUE THREAD

**Issue by mattmiller1988** [LMAX-Exchange/disruptor#166]
Version: 3.3.2

It appears that event handlers are not necessarily finished executing when `Disruptor.shutdown()` returns. What is the definitive way to detect when all event handlers have finished execution after the disruptor is shutdown?

As a point of illustration, this unit test sometimes prints 0, and sometimes prints 1:

    public class ShutdownTest {
        volatile int value = 0;

        @Test
        public void shutdownFailure() throws TimeoutException
        {
            Disruptor<Void> disruptor = new Disruptor<>(() -> null, 8, (ThreadFactory) Thread::new);
            disruptor.handleEventsWith(this::updateValue);
            disruptor.start();
            disruptor.getRingBuffer().publishEvent((m, s) -> {});
            disruptor.shutdown(10, TimeUnit.SECONDS);

            System.out.println(value); // Sometimes prints 0, but if updateValue has completed it would be expected to always be 1.
        }

        private void updateValue(Message message, long sequence, boolean endOfBatch)
        {
            value = 1;
        }
    }

What is the correct way of ensuring that "1" is printed, always?

**Comment by mikeb01** [comment]
You can use the LifecycleAware interface to detect shutdown, I've drawn up an [example](https://github.com/LMAX-Exchange/disruptor/blob/master/src/test/java/com/lmax/disruptor/example/WaitForShutdown.java).

**Comment by mattmiller1988** [comment]
Thanks!

**Comment by mattmiller1988** [comment]
It appears that only the first EventHandler in the chain may be LifecycleAware. Later event handlers, if marked LifecycleAware, will not be called.

For example in `disruptor.handleEventsWith(new FirstEventHandler()).then(new SecondEventHandler());`, it should be the `FirstEventHandler` that is `LifecycleAware`. If `SecondEventHandler` is `LifecycleAware`, it does not appear to be called on shutdown.

**Comment by mikeb01** [comment]
I don't see the problem that you mention.  I've updated the example to use two EventHandlers and the onShutdown method is called for both.  Do you have a complete example that shows the problem.

**Comment by mattmiller1988** [comment]
The code below printed "Failures: 46/100" for me. If I switch from using EventHandlers to WorkHandlers, the failure rate drops to 0/100.

    private class ShutdownTest
    {
        private CountDownLatch startupLatch;
        private CountDownLatch shutdownLatch;

        @Test
        public void shutdownFailure() throws TimeoutException, InterruptedException
        {
            int failures = 0;
            for(int i = 0; i < 100; ++i)
            {
                startupLatch = new CountDownLatch(1);
                shutdownLatch = new CountDownLatch(1);

                Disruptor<Void> disruptor = new Disruptor<>(() -> null, 8, (ThreadFactory) Thread::new);
                disruptor.handleEventsWith(new EventHandler1());
                disruptor.handleEventsWith(new EventHandler2());
                disruptor.start();
                disruptor.getRingBuffer().publishEvent((m, s) -> {
                });
                disruptor.shutdown(10, TimeUnit.SECONDS);

                Assert.assertTrue(startupLatch.await(5, TimeUnit.SECONDS));

                if(!shutdownLatch.await(10, TimeUnit.SECONDS))
                {
                    ++failures;
                }
            }

            System.out.println("Failures: " + failures + "/100");
        }

        private class EventHandler1 implements EventHandler<Void>
        {
            @Override
            public void onEvent(Void event, long sequence, boolean endOfBatch) throws Exception
            {
                System.out.println("Event 1");
            }
        }

        private class EventHandler2 implements EventHandler<Void>, LifecycleAware
        {
            @Override
            public void onEvent(Void event, long sequence, boolean endOfBatch) throws Exception
            {
                System.out.println("Event 2");
            }

            @Override
            public void onStart()
            {
                System.out.println("Start 2");
                startupLatch.countDown();
            }

            @Override
            public void onShutdown()
            {
                System.out.println("Shutdown 2");
                shutdownLatch.countDown();
            }
        }
    }

**Comment by mikeb01** [comment]
Move the line `Assert.assertTrue(startupLatch.await(5, TimeUnit.SECONDS));` before the shutdown call.  The shutdown is occurring before the thread has had a chance to start.

**Comment by mattmiller1988** [comment]
That's the primary source of confusion for me, I suppose. In this example, the thread does seem to actually start and handle traffic, but because the shutdown happens so quickly it seems to skip doing the onShutdown method.

The logs from a failed iteration of this test are:
Event 1
Start 2
Event 2

That indicates to me that the threads have already started because:
1. The onStart() is being called.
2. The onEvent() is being called.

Despite these two functions being executed, the onShutdown() is never called when the thread is killed. That's pretty confusing as I would expect after an onStart() you would always see an onShutdown().

This probably won't ever be an issue in production code because it's unlikely people would ever start and stop the disruptor so quickly, but it's a bit of a nuisance in unit testing where you're more likely to be starting and stopping them in quick succession. As you've pointed out, it can be worked around by adding the startup latch and ensuring the startup has finished before the shutdown is initiated.

**Comment by mikeb01** [comment]
It is a source of confusion that I want to fix, but doing it transparently (without API or behaviour change) is tricky and given that it tends to only turn up in unit tests and there is a fairly straight-forward workaround it keeps falling to the bottom of the priority list.

**Comment by mattmiller1988** [comment]
Seems reasonable. Thanks!
