### ISSUE TITLE
A question about cache line padding

### ISSUE THREAD

**Issue by HashZhang** [LMAX-Exchange/disruptor#167]
I see you make cache line padding in RingBuffer.java. Since you have made Bufferpadding for field "Object[] entries" and other fileds are all final, what is the point to make further padding in RingBufferPad:  protected long p1, p2, p3, p4, p5, p6, p7;

**Comment by mikeb01** [comment]
The fields in RingBufferFields are frequently read.  The additional padding is to prevent them from sharing a cache line with some other data that might be written to that would cause a cache miss when that field was read.
