### ISSUE TITLE
Spikes in latency from the moment we put event till we pop event on another thread

### ISSUE THREAD

**Issue by onxonx** [LMAX-Exchange/disruptor#171]
Hello,

We are observing interesting behavior. I do not have a simple compilable code to show. But in our
more complex project here is what we see. There are only 2 threads - 1 Publisher and 1 Consumer. Both
threads don't have a single sleep/wait/lock and run infinite loop. Each thread takes 100% CPU of
pinned core. Both cores are from the same physical CPU. Those cores are isolated from CentOS so
nothing else is running there.

Disruptor:
  Ring buffer has 512 cells.
  
Publisher:
  Publisher posts one event with current System.nanoTime() every 1 ms (i.e. 1000 events per second).
  In addition every 3.4 second the publisher posts 300 events at once as a burst (put 1 by 1 with
  calling "next(),publish()" 300 times).
  
Consumer:
  Consumer is using your com.lmax.disruptor.EventPoller and measures how fast the event got to
  consumer - the time from “event enqueuing” till “event dequeuing”. Consumer collects the "number of
  events", "min interval", "sum of intervals for average" and "max interval".
  Every 1 second the consumer prints the stats, resets stats and ignores the events for next
  1000 ms (by silently draining the ring buffer). So, printouts are printed every 2 seconds

Params:
  -verbose:gc
  -XX:CompileThreshold=1
  -XX:-TieredCompilation
  -XX:+PrintCompilation
  -XX:+PrintFlagsFinal
  -XX:+PrintGCApplicationStoppedTime
  -XX:+PrintGCApplicationConcurrentTime
  -XX:PrintSafepointStatisticsCount=1
  -XX:+PrintSafepointStatistics
  -XX:+UseLargePages
  -XX:LargePageSizeInBytes=2m
  
Output after warm up:
I|2016/08/25 16:21:31.509081|EventReader|Test: count=1001, min=177, avg=247, max=337
I|2016/08/25 16:21:33.509146|EventReader|Test: count=1001, min=181, avg=248, max=359
I|2016/08/25 16:21:35.509215|EventReader|Test: count=1300, min=180, avg=13169, max=93801
I|2016/08/25 16:21:37.509283|EventReader|Test: count=1001, min=184, avg=250, max=339
I|2016/08/25 16:21:39.509346|EventReader|Test: count=1300, min=183, avg=13081, max=93254
I|2016/08/25 16:21:41.509414|EventReader|Test: count=1001, min=180, avg=248, max=358
I|2016/08/25 16:21:43.509483|EventReader|Test: count=1001, min=184, avg=249, max=335
I|2016/08/25 16:21:45.509551|EventReader|Test: count=1001, min=179, avg=250, max=343
I|2016/08/25 16:21:47.509618|EventReader|Test: count=1001, min=182, avg=247, max=416
I|2016/08/25 16:21:49.509684|EventReader|Test: count=1300, min=185, avg=13160, max=93679
I|2016/08/25 16:21:51.509750|EventReader|Test: count=1001, min=177, avg=244, max=312
I|2016/08/25 16:21:53.509820|EventReader|Test: count=1001, min=184, avg=251, max=364
I|2016/08/25 16:21:55.509886|EventReader|Test: count=1001, min=182, avg=249, max=350
I|2016/08/25 16:21:57.509958|EventReader|Test: count=1001, min=184, avg=248, max=317
I|2016/08/25 16:21:59.510021|EventReader|Test: count=1300, min=179, avg=13132, max=93486
I|2016/08/25 16:22:01.510087|EventReader|Test: count=1001, min=182, avg=250, max=326
I|2016/08/25 16:22:03.510154|EventReader|Test: count=1300, min=186, avg=12997, max=92852
I|2016/08/25 16:22:05.510222|EventReader|Test: count=1001, min=179, avg=248, max=360

As you can see every moment when we do burst with additional 300 events, the max time
statistics jump from 300-400ns to 100,000 ns. It is about 300x worse latency during spikes.

Could you share your thoughts if there are any options to avoid that 300x times increase? Is
this due to slow cache coherency of 300 cells and volatile cursors? In our code we cannot
always predict the number of events that publisher is about to put to do "next(N)"
instead of "next(1)" N times.

Thank you,
Alex Malko

**Comment by mikeb01** [comment]
Can you publish your benchmark code?

**Comment by epickrram** [comment]
Hello.
100 microsecond spikes sounds very much like the delay caused by JVM guaranteed safe-points.

Have you looked at the log output from  -XX:+PrintSafepointStatistics? If you see messages like these:

```
20.204: no vm operation 
```

then safepoints could be the culprit.


Can you try running again with the following flag (assuming you're using Hotspot):

```
-XX:+UnlockDiagnosticVMOptions -XX:GuaranteedSafepointInterval=300000
```

More detail is here:
https://epickrram.blogspot.co.uk/2015/08/jvm-guaranteed-safepoints.html

**Comment by onxonx** [comment]
I added the test app here: https://github.com/onxonx/disruptor_latency_test
This test does not show so large spikes when I add the extra 300 events in bursts. It also jumps but reasonably. So, I will continue searching for the difference between this dedicated test and our larger app with the test.

The only suspicious spike is this:

<pre>
1,472,238,476,381 [ConsumerThread]: count=1,001, min=161 ns, avg=219 ns, max=341 ns
1,472,238,478,382 [ConsumerThread]: count=1,300, min=148 ns, avg=207 ns, max=344 ns
1,472,238,480,382 [ConsumerThread]: count=1,001, min=160 ns, avg=362 ns, max=142,178 ns
1,472,238,482,382 [ConsumerThread]: count=1,001, min=160 ns, avg=225 ns, max=320 ns
1,472,238,484,382 [ConsumerThread]: count=1,001, min=169 ns, avg=224 ns, max=339 ns
</pre>

**Comment by onxonx** [comment]
Hi with more tests we found that the spike is not due to disruptor being slow. The spike for "max" with 300 events bursts is only because the consumer is a little slower than publisher - the events backfill. If consuming is 100 ns more expensive than the publishing...then the 300-th event will be processed at least 100*300ns=30,000ns.
