### ISSUE TITLE
Question, why WorkHandler's onEvent don't have endOfBatch as arg?

### ISSUE THREAD

**Issue by wu-sheng** [LMAX-Exchange/disruptor#180]
In `EventHandler`, there is a arg, called endOfBatch. I can use it to batch update or flush.
But when I use `WorkHandler`,  `endOfBatch` is not existed in args list.

Should I use a EventHandler to control multi WorkHandler, let 5 WorkHandlers to write file, and use 1 EventHandler to flush when `endOfBatch` happens.

**Comment by mikeb01** [comment]
The `WorkerPool` doesn't do batching.  There are interesting failure situations that you can get into if one of the `WorkHandler` fails part way through a batch.  It can get to the point were it can't recover.  Personally for writing to a file I would just use a single thread and a single `EventHandler` and use it's batching support to write efficiently.  That's what we do within our exchange.

**Comment by wu-sheng** [comment]
Yes, I run a test today. Even use a multi Disruptor-instance. in order to use multi EventHandler to write file parallel,  it has no help to improve performance. Disk I/O is not so efficient.

**Comment by mikeb01** [comment]
That's consistent with our observations.  Writing is parallel tends to result in contention as the file system level.

**Comment by wu-sheng** [comment]
Yes, previous tests show I/O is not busy enough, at last, I find out that's because my write file buffer is not big enough.
