### ISSUE TITLE
What is going to happen, when disruptor.shutdown called?

### ISSUE THREAD

**Issue by wu-sheng** [LMAX-Exchange/disruptor#182]
If muti threads producers are blocking when disruptor is full, and on comsuming.
At this moment, I call shutdown(), the blocking thread will break blocking? Return with nothing or exception?

**Comment by mikeb01** [comment]
They will remain stuck.  Shutdown will simply shutdown all of the consuming event handlers.

**Comment by wu-sheng** [comment]
```java
public boolean saveRequestSpan(RequestSpan requestSpan) {
        long sequence = requestSpanRingBuffer.next();
        try {
            RequestSpanHolder data = requestSpanRingBuffer.get(sequence);
            data.setRequestSpan(requestSpan);

            HealthCollector.getCurrentHeathReading("StorageListener").updateData(HeathReading.INFO, "RequestSpan stored.");
            return true;
        } catch (Exception e) {
            logger.error("RequestSpan trace-id[{}] store failure..", requestSpan.getTraceId(), e);
            HealthCollector.getCurrentHeathReading("StorageListener").updateData(HeathReading.ERROR, "RequestSpan store failure.");
            return false;
        } finally {
            requestSpanRingBuffer.publish(sequence);
        }
    }
```
Is this will trigger blocking, when Disruptor buffer is full? Should I wait there is no blocking and no producer to this Disruptor, then shutdown the Disruptor? Am I right?

**Comment by mikeb01** [comment]
That will work, the other option would be to use `RingBuffer.tryNext()` and check the heath reading on failure.

**Comment by wu-sheng** [comment]
If `tryNext` returns without a exception, the `requestSpanRingBuffer.get` and `requestSpanRingBuffer.publish` will not block? **Even** between `tryNext`and `requestSpanRingBuffer.get`, `Disruptor.shutdown()` is called by another thread?

Is this safe enough in multi thread scenario?

**Comment by mikeb01** [comment]
That's correct, only the `RingBuffer.next` method will block.

**Comment by wu-sheng** [comment]
Further more, if I always use trynext, and catch exception for buffer full status, will cause performance issue?

**Comment by mikeb01** [comment]
It's reasonably efficient.  The exception is pre-created and does not build a stack trace, so the cost is roughly similar to a longjmp.

**Comment by wu-sheng** [comment]
I use this code to get sequence like `SleepingWaitStrategy`. But is there any more efficient way?
`LockSupport.parkNanos(1L);` seems having a high CPU cost in my application with in a **Stress Test**, because of `parkNanos` may be triggered frequency, and need to wait more than 1 namo.
```java
long sequence;
        while(true) {
            try {
                sequence = requestSpanRingBuffer.tryNext();
                break;
            } catch (InsufficientCapacityException e) {
                LockSupport.parkNanos(1L);
            }
        }
```

**Comment by mikeb01** [comment]
If your stress test is trying publish as fast a possible then it is likely that your buffer will be completely full nearly all of the time.  So you will be falling into the catch box fairly frequently.  The cost of LockSupport.parkNanos(1) will vary from machine to machine.  On 64 bit Linux it tends to be around 10% per thread.

**Comment by wu-sheng** [comment]
Yes, you are right, that is what I have seen in my test report. Any suggestions? And I found `BlockingWaitStrategy` may have a higher performance. How can I implement a BlockingWait in `tryNext` scenario.

And further, I have another thing to discuss:
`handleEventsWithWorkerPool` and `handleEventsWith` will cause new Thread to consume data, yes? And in my use `kill -3` to get all thread, the thread name only display as "Thread-1", "Thread-2"...
It's not friendly. Can I set a threadName or threadName-Prefix for Disruptor's consume threads?

**Comment by mikeb01** [comment]
The Disruptor doesn't have a mechanism for a publisher to do a blocking wait for an available slot.  The signalling cost to too high.  In practice, when your buffers are consistently full there are other performance issues to be addressed (i.e. why are my consumers running so slow) rather than worrying about the CPU cost on publish.  Also in a number of cases we drop messages when they can't be queued so that we don't block our networking threads.

**Comment by mikeb01** [comment]
You could implement the LifeCycle interface and name the thread in the onStart callback.

**Comment by wu-sheng** [comment]
Does EventHandler need to implement interface `LifecycleAware`?

**Comment by mikeb01** [comment]
No, it is optional.  Only if you need callbacks for onStart and onShutdown.

**Comment by wu-sheng** [comment]
I know it's optional. I mean if I need, which class should implement this interface? Evetnhandle, or worker, or both?

**Comment by mikeb01** [comment]
Only EventHandler support LifeCycleAware.  The other option would be to use a ThreadFactory that names the thread after creation.

**Comment by wu-sheng** [comment]
Maybe. I set a eventhandler just for implementing LifeCycleAware, and set workers do what I should do.
Is it Ok?

**Comment by mikeb01** [comment]
For the EventHandlers yes.  I'm not sure what you mean by "and set workers do what I should do".

**Comment by wu-sheng** [comment]
Nothing more, I see your point. Thank you.
