### ISSUE TITLE
Add a WaitStrategy utilising JDK9 Thread.onSpinWait()

### ISSUE THREAD

**Issue by jvz** [LMAX-Exchange/disruptor#183]
[JEP 285](http://openjdk.java.net/jeps/285) adds a neat spin wait hint for native support for PAUSE-like instructions for lower power spin locks. In theory, this could be useful here, but I'm not an expert.

**Comment by mikeb01** [comment]
This would need to sit outside of the current build of the disruptor which is current fixed on jdk 6.  Version 4 of the Disruptor will be JDK 9 specific and will include a WaitStrategy that will support Thread.onSpinWait.

**Comment by mjpt777** [comment]
Azul Zing shall support this hint in versions previous to Java 9 via the following hint. // @giltene

https://github.com/real-logic/Agrona/blob/master/src/main/java/org/agrona/hints/ThreadHints.java

**Comment by giltene** [comment]
I guess that since the Argona Java-version-independent thing (which @mikeb01 originally came up with) relies on MethodHandle, or requires Java SE 7 or later. Maybe we can do something that will load on Java 6 using a reflection based detection of MethodHandles?

**Comment by jvz** [comment]
Would accessing this reflectively be too much of a performance impact? I've benchmarked using `new Foo()` versus `Foo.class.getConstructor().newInstance()` and they were pretty close, but I'm not sure about using `MethodHandle` or even the old `Method` version.

**Comment by giltene** [comment]
I'm not suggesting accusing reflectively, just detecting whether or not MethodHandle is available reflectively. I've put together an example of how this can be made to work across Java SE 6/7/8/9 here: https://github.com/giltene/GilExamples/tree/master/SpinWaitTest/src/main/java/org/performancehints

The challenge is that (for this to work with Java 6) SpinHints.java needs to be compiled with -target 1.6, while SpinHintsMT.java must be compiled with -target 1.7 or later, both in the same Agrona jar. My maven-foo is not up to that yet.

**Comment by giltene** [comment]
The "trick" is that although SpinHintsMH.class must be version 51 or higher (so cannot be loaded in Java SE 6), it would only be loaded if SpinHints.class determined (reflectively) that java.lang.invoke.MethodHandle exists. So on Java 6 that class never comes into scope and no runtime errors occur. I've verified this my manually compiling the classes with the different target versions and running on both Java 8 and Java 6.

**Comment by mikeb01** [comment]
I'll dig into this in more detail.  JDK 9 also adds support for multi-version jars, which may also be useful here.

**Comment by mikeb01** [comment]
Fixed in commit d713cd8.
