### ISSUE TITLE
High CPU Usage with SleepingWaitStrategy on Linux/CentOS

### ISSUE THREAD

**Issue by daipech** [LMAX-Exchange/disruptor#190]
SleepingWaitStrategy use LockSupport.parkNanos(1L) to sleep thread, but in some Linux platform with FUTEX, this cause high CPU Usage. In my case, 2 sleeped pool-thread used 20%+ on 4 core i5 CPU (JAVA 1.8.0_92 64 bit).

IMHO, LockSupport.parkNanos maybe use posix mutex, and in Linux with FUTEX(Fast User-space muTEX) it's maybe directly return without enter kernel system call.

**Comment by mikeb01** [comment]
Are you running a 32 or 64 bit JVM?

**Comment by daipech** [comment]
64bit JVM / 64bit CentOS Release 6.5 / Kernel: Linux 2.6.32-431.e16.x86_64
BTW, I change parkNanos to Thead.Sleep(), and everything is OK.

**Comment by mikeb01** [comment]
Around 20% CPU usage for SleepingWaitStrategy is about what we see.  All user space polling wait strategies (busy spin, yield, sleeping) will use some degree of CPU time.  The lowest CPU usage implementation is the BlockingWaitStrategy.  You need to decide what set of CPU cost trade offs you want to make against your desired latency.  E.g. using Thread.sleep(1) will give you a median latency somewhere in the region of 500 to 1000 µs, where as LockSupport.parkNanos(1) will be somewhere around 50 to 100 µs.

**Comment by mikeb01** [comment]
This is one of the reasons that we made the WaitStrategy an interface and allow the user to plug in one of the supplied implementations or use their own.

**Comment by daipech** [comment]
very thank you for your reply
