### ISSUE TITLE
WaitStrategy is not respected In MultiProducerSequencer when producer has called next() but not publish()

### ISSUE THREAD

**Issue by agsha** [LMAX-Exchange/disruptor#193]
The following patch demonstrates the issue: 
The RingBuffer has been initialized with BlockingWaitStrategy
The producer has called next() but not publish()
Yet, the BatchEventProcessor keeps printing "busy spinning" instead of blocking

````
diff --git a/src/main/java/com/lmax/disruptor/BatchEventProcessor.java b/src/main/java/com/lmax/disruptor/BatchEventProcessor.java
index 6b1711f..2c4edac 100644
--- a/src/main/java/com/lmax/disruptor/BatchEventProcessor.java
+++ b/src/main/java/com/lmax/disruptor/BatchEventProcessor.java
@@ -121,6 +121,7 @@ public final class BatchEventProcessor<T>
             {
                 try
                 {
+                    System.out.println("busy spinning");
                     final long availableSequence = sequenceBarrier.waitFor(nextSequence);
 
                     while (nextSequence <= availableSequence)
diff --git a/src/perftest/java/com/lmax/disruptor/sequenced/ThreeToOneSequencedThroughputTest.java b/src/perftest/java/com/lmax/disruptor/sequenced/ThreeToOneSequencedThroughputTest.java
index a3aac27..f2e0c09 100644
--- a/src/perftest/java/com/lmax/disruptor/sequenced/ThreeToOneSequencedThroughputTest.java
+++ b/src/perftest/java/com/lmax/disruptor/sequenced/ThreeToOneSequencedThroughputTest.java
@@ -25,7 +25,7 @@ import java.util.concurrent.Future;
 
 import com.lmax.disruptor.AbstractPerfTestDisruptor;
 import com.lmax.disruptor.BatchEventProcessor;
-import com.lmax.disruptor.BusySpinWaitStrategy;
+import com.lmax.disruptor.BlockingWaitStrategy;
 import com.lmax.disruptor.RingBuffer;
 import com.lmax.disruptor.SequenceBarrier;
 import com.lmax.disruptor.support.ValueAdditionEventHandler;
@@ -80,9 +80,9 @@ import com.lmax.disruptor.util.DaemonThreadFactory;
  */
 public final class ThreeToOneSequencedThroughputTest extends AbstractPerfTestDisruptor
 {
-    private static final int NUM_PUBLISHERS = 3;
+    private static final int NUM_PUBLISHERS = 1;
     private static final int BUFFER_SIZE = 1024 * 64;
-    private static final long ITERATIONS = 1000L * 1000L * 20L;
+    private static final long ITERATIONS = 1L;
     private final ExecutorService executor =
         Executors.newFixedThreadPool(NUM_PUBLISHERS + 1, DaemonThreadFactory.INSTANCE);
     private final CyclicBarrier cyclicBarrier = new CyclicBarrier(NUM_PUBLISHERS + 1);
@@ -90,7 +90,7 @@ public final class ThreeToOneSequencedThroughputTest extends AbstractPerfTestDis
     ///////////////////////////////////////////////////////////////////////////////////////////////
 
     private final RingBuffer<ValueEvent> ringBuffer =
-        createMultiProducer(ValueEvent.EVENT_FACTORY, BUFFER_SIZE, new BusySpinWaitStrategy());
+        createMultiProducer(ValueEvent.EVENT_FACTORY, BUFFER_SIZE, new BlockingWaitStrategy());
 
     private final SequenceBarrier sequenceBarrier = ringBuffer.newBarrier();
     private final ValueAdditionEventHandler handler = new ValueAdditionEventHandler();
diff --git a/src/perftest/java/com/lmax/disruptor/support/ValuePublisher.java b/src/perftest/java/com/lmax/disruptor/support/ValuePublisher.java
index a875402..67c6d4b 100644
--- a/src/perftest/java/com/lmax/disruptor/support/ValuePublisher.java
+++ b/src/perftest/java/com/lmax/disruptor/support/ValuePublisher.java
@@ -45,7 +45,9 @@ public final class ValuePublisher implements Runnable
                 long sequence = ringBuffer.next();
                 ValueEvent event = ringBuffer.get(sequence);
                 event.setValue(i);
-                ringBuffer.publish(sequence);
+                //ringBuffer.publish(sequence);
+                System.out.println("next() but not published");
+
             }
         }
         catch (Exception ex)
````

**Comment by mikeb01** [comment]
This will most likely occur when the publisher has called next a sufficient number of times, such that the the buffer is full.  Once the next code notices that it has hit the wrap point, it will do a pre-emptive notification of the event handlers (in case they have stalled for some unforeseen reason).  This will wake the blocking threads and cause them to spin and wait until publish is called.

I would consider this to be a bug in the calling code.  A publishing thread should not call `next()` a second time before calling `publish()`.  This does put a fair be of responsibility onto users if they choose to use that form of publication.  If the user is less confident in ensuring that their code will safely always call `publish()` when required, then they can use the `EventTranslator` interface methods, which handle this complexity internally.

**Comment by agsha** [comment]
The problem occurs even if `next()` is always succeeded by `publish()`.
The issue is that the `cursor` value is visible to `waitFor()` immediately after calling `next()`.
It should only be visible/updated after calling `publish()`

**Comment by mikeb01** [comment]
Only if the threads are woken in the interim.  If the threads are in a parked state before `next()` is called, this will only happen when the buffer hits the wrap point.  If the threads are not already parked then keeping them spinning is a better than parking and re-waking as the time between `next()` and `publish()` should be short, certainly shorter than the 10s of µs required to park and wake a thread.

The difficultly if making the cursor value visible in the publish call is ordering it correctly.  This tends result in algorithms that are either very slow or burn significantly more CPU on publication than the spinning caused by publishing the cursor value early and using the secondary check availableBuffer.
