### ISSUE TITLE
Question: Disruptor Dependency Graph/Gating with SequenceBarrier

### ISSUE THREAD

**Issue by matthewdowney** [LMAX-Exchange/disruptor#195]
### Goal

I'm trying to create a dependency relationship between handlers that's somewhat circular, and I can't quite figure out how to get it right. What I want to achieve is a variation of `producer -> [handlers 1-3] -> handler 4`.

So, `disruptor.handleEventsWith(h1, h2, h3).then(h4);`. But I have the additional requirements that 

1. While handlers 1-3 do process messages in parallel, none of them begins to process the next message until they have all finished the previous message.
2. After the first message, handlers 1-3 wait for handler 4 to have finished the most recent message before processing the next message.

The equivalent execution logic using a single event handler could be:

```java
    disruptor.handleEventsWith((event, sequence, endOfBatch) -> {
      Arrays.asList(h1, h2, h3).parallelStream()
            .forEach(h -> h.onEvent(event, sequence, endOfBatch));
      h4.onEvent(event, sequence, endOfBatch);
    });
```

### Context

The design context is that handlers 1-3 each update their own state according to the message and that after a message is processed by each of the three they are in a consistent state. Handler 4 then runs some logic based on the state updated by handlers 1-3. So handler 4 should only see consistent states for the data structures maintained by 1-3, which means that handlers 1-3 should not process the next message until handler 4 has finished.

(Though the goal is definitely to use the Disruptor to manage the concurrency, rather than `java.util.Stream`.)

Not sure if it matters, but it's also the case that handler 4's logic can be broken into two parts, one requiring that none of handlers 1-3 are being updated and the next requiring only that the first part of handler 4 has finished. So handlers 1-3 can be processing a message while the second part of handler 4 is still executing.

Is there a way to accomplish this? Or maybe my design is flawed? I feel like there should be a way to do this via `SequenceBarrier` but I don't quite understand how to implement this custom barrier. For handlers 1-3, I think I'd like to make a barrier with the logic `handlers[1:3].lastProcessedSequence() == handlers[4].lastProcessedSequence()`, but I'm not sure where to put that logic.

Thanks!

**Comment by codeaholics** [comment]
How big is the state maintained by handlers 1-3? Is it small enough that it can be copied onto the message as it passes through?

**Comment by mikeb01** [comment]
> Is there a way to accomplish this? Or maybe my design is flawed?

Flawed is probably too strong a word, but the design does include elements that I would avoid.  It sounds like the handlers are sharing mutable state across threads, hence your requirement to gate handlers 1-3 on handler 4 completing.  I would look to make the shared state immutable or as @codeaholics mentions pass the state as part of the event between handlers.

If changing that is not possible then I suspect using the Disruptor is probably not the best tool for your problem.  I would probably look at a simple loop through the input data, using fork/join to handle the parallel portion (handlers[1-3]) and getting the result and doing the work of handler[4] inline.

**Comment by matthewdowney** [comment]
@codeaholics  @mikeb01 Thanks for the responses guys!

> How big is the state maintained by handlers 1-3? Is it small enough that it can be copied onto the message as it passes through?

It's fairly large. We're maintaining data from several exchanges, so we have large order books as well as smaller structures to represent wallet balances, user orders, etc. The general idea is that handlers 1-3 update state according to the message and that handler 4 sends out pub-sub style updates to any clients who may have subscribed depending on the message type. Our goal is that this message processing code maintains state in sync with the remote exchanges and acts as a local proxy, and that client code can always observe the state of the remote exchange via the locally replicated state.

> If changing that is not possible then I suspect using the Disruptor is probably not the best tool for your problem. I would probably look at a simple loop through the input data, using fork/join to handle the parallel portion (handlers[1-3]) and getting the result and doing the work of handler[4] inline.

Yeah that makes sense. Do you think it still makes sense to use the Disruptor over a standard library blocking queue--and just keep the logic you were talking about in one handler?

**Comment by mikeb01** [comment]
> Yeah that makes sense. Do you think it still makes sense to use the Disruptor over a standard library blocking queue--and just keep the logic you were talking about in one handler?
It's hard to say what the best solution is without seeing the whole problem.  The best I can suggest is pick one, implement and test/benchmark to see if it meets your requirements.
