### ISSUE TITLE
Using disruptor as an pipeliner.

### ISSUE THREAD

**Issue by amosbird** [LMAX-Exchange/disruptor#197]
Hello, I'd like to have a ringbuffer like structure that does the following job,

![](https://la.wentropy.com/uJk1.png)

That is, to use a ringbuffer to merge a bunch of sequenced records (1, 2, 3 ...) into one sequence.

**Comment by mikeb01** [comment]
You can build this already with two instances of the Disruptor.  The first fans out to 3 parallel handlers, then each of those publisher sends events to a 2nd instance of the Disruptor.  The single event handler on the 2nd Disruptor would take care of the reordering of events.

**Comment by amosbird** [comment]
> The single event handler on the 2nd Disruptor would take care of the reordering of events.

do you mean I have to manually sort the incoming events? what if there is one missing while the ringbuffer becomes full?

**Comment by mikeb01** [comment]
Actually there is an easier way.  If you have 4 consumers where 3 of them are processing the data in parallel.  A hash on the sequence number is the simplest solution.  Then the 4th consumer can gate on the other 3.

**Comment by amosbird** [comment]
Hmm, I don't follow. If there are two disruptors, which sequence should the 4th consumer gate on? Could you give an simple code snippet of this task. Thanks!

**Comment by mikeb01** [comment]
You would only need a single Disruptor.

**Comment by mikeb01** [comment]
I'll look at a code snippet tomorrow.

**Comment by amosbird** [comment]
I have add a new method to MultiProducerSequencer,

```
    @Override
    public void seq(long seq) {
        if (seq < 0)
        {
            throw new IllegalArgumentException("seq must be >= 0");
        }

        long current;
        do
        {
            current = cursor.get();
            if (seq < current) {
                return;
            }
            long wrapPoint = seq - bufferSize;
            long cachedGatingSequence = gatingSequenceCache.get();

            if (wrapPoint > cachedGatingSequence || cachedGatingSequence > current)
            {
                long gatingSequence = Util.getMinimumSequence(gatingSequences, current);

                if (wrapPoint > gatingSequence)
                {
                    waitStrategy.signalAllWhenBlocking();
                    LockSupport.parkNanos(1); // TODO, should we spin based on the wait strategy?
                    continue;
                }

                gatingSequenceCache.set(gatingSequence);
            }
            else if (cursor.compareAndSet(current, seq))
            {
                break;
            }
        }
        while (true);
    }
```

However this makes all blocking wait strategy useless. Since they only rely on the cursor position. I tried to find a multi-cursor implementation but failed. Is it the correct way to do this? Can we have a multi-cursor, single gating sequence implementation?

**Comment by mikeb01** [comment]
You can do this without modifying the Disruptor.  I'll post a code snippet later today.

**Comment by mikeb01** [comment]
This a way that you can get the behaviour that you want.

**Comment by amosbird** [comment]
Thanks!  But this seems not be able to fully parallel. Will all the parallel handlers be waiting when the join handler is working? And I cannot do pipeline partitioner like this way,

![](https://la.wentropy.com/0FbP.png)

**Comment by mikeb01** [comment]
The parallel handlers won't be waiting while the join handler is running.  The join handler will wait until each  has finished processing a given sequence.  However only one of the handler will actually do the work, the other 2 will skip it.  So the processing is not perfectly parallel, but can work well enough if the work done on each item is higher than the overhead of the Disruptor and reasonably even for each event.

The layout you mention is possible, you would need 3 join handler instances.
```Java
        disruptor.handleEventsWith(
            new ParallelHandler(0, 3),
            new ParallelHandler(1, 3),
            new ParallelHandler(2, 3)
        ).then(
            new JoiningHandler(1),
            new JoiningHandler(2),
            new JoiningHandler(3));
```

**Comment by amosbird** [comment]
cool! if some `JoiningHandler` hangs, will the other two keep going?

**Comment by amosbird** [comment]
Hmm, isn't that going to have a tons of temporary items passing from `ParallelHandler` to `JoiningHandler`?

**Comment by mikeb01** [comment]
Depends on how you implement the result.  You could use a preallocated object and fill it from within the Parallel handler and the Disruptor will reuse the event later on.

The other JoiningHandlers will run in parallel.  However if the JoiningHandler hangs indefinitely then eventually the ring buffer will fill up and block.

**Comment by amosbird** [comment]
ok. Can't quite tell the overhead though. I may have up to 128 partitions and this would lead to 128 JoiningHandlers, which will try to sequence up unnecessary 127 times for every parallel event. And I may need a very large ring buffer...  However, it's illuminating :smile: t

**Comment by mikeb01** [comment]
If the tasks are not doing I/O I would keep the total number of handlers less than the number of available cores.  Obviously benchmarking will determine the most appropriate configuration.  Also if your number of handlers is a power of 2, you can use a mask as the modulo operation.

**Comment by amosbird** [comment]
Well, hmm, isn't there a inter dependency between paralleler and joiner ? If I have 16 logical cores, how about using 16 paralleler and 16 joiner?

**Comment by mikeb01** [comment]
Assuming that you have sufficient data as input you could have all 32 handlers running at the same time.  The interplay between the parallel and joiner handlers is an asynchronous notification, so the parallel handler can move onto processing more events without waiting for the joiner.  Everything is bounded by the size of the buffer though.

**Comment by amosbird** [comment]
hmm, there is a problem. Those joiners may start processing `1:2` before `1:1` which is unacceptable.

**Comment by amosbird** [comment]
Hmm, this architecture turns out to be very slow in real applications,
![](https://la.wentropy.com/dc4A.png)

Jprofiler shows the dependency is too complex to be handled. I also tried a bunch of other wait strategies. It turns out that Sleep strategy is the best for tangled dependency in disruptor, but still quite slow.

**Comment by mjpt777** [comment]
JProfiler is not suitable for this type of profiling. You need to use perf-map-agent, Flight Recorder, or Linux perf.

**Comment by amosbird** [comment]
Thanks. I'll carry some more profilings. But this is indeed running much slower than manually splitted queues. I think small fine-grained waiting barriers is better for this partitioning pipeliner. Or is there a better way to do this in disruptor?

**Comment by amosbird** [comment]
Just did a flamegraph  https://la.wentropy.com/5mvJ   .   This shows nearly 65% of time is consumed by some waiting events.

**Comment by amosbird** [comment]
Further testing shows that single parallel handler's performance is the same with eight parallel handler.

**Comment by mikeb01** [comment]
Are you testing with your real workload or the example that I created?

**Comment by amosbird** [comment]
real workload

**Comment by amosbird** [comment]
oh, the flamegraph is from your example

**Comment by mikeb01** [comment]
Regarding the 8 threads vs 1 thread.  This is not uncommon.  If the amount of work to do per event is quite small, then the overhead of parallelising the workload means there is no overall benefit.  The other common situation is that the workload is memory bound so when running multiple instances in parallel they end up contending on L3 cache and no really reaping the benefit of having additional CPU cores.

Have you tried using an alternative framework for your world load (e.g. Fork/Join)?

**Comment by amosbird** [comment]
yes, a simple fork join with a concurrent linked queue is three times faster. I have tried tuning the task size, varying from 4k to 1M. There isn't a difference though.

**Comment by amosbird** [comment]
and an interestibg fact is, sleeping wait strategy is 80% faster than all the others.

**Comment by mikeb01** [comment]
Not really surprised that Fork/Join is faster.  If your workload works nicely with Fork/Join it is probably not a good fit for the Disruptor.  The Disruptor works best for asynchronous message based services.

The SleepingWaitStrategy is fine when you are hammering it flat out, but if you have no input for a short period of time and the handler needs to idle, you have a long wake up time before it starts processing events again (~60µs).  There is a trade off here between latency and throughput.

**Comment by amosbird** [comment]
Ok. Um, so what's the suggested library that can implement this partitioned pipeliner efficiently?

**Comment by mikeb01** [comment]
Assuming that this is a large batch operation, I would be looking at something using a model similar to fork/join or parallel streams.  In addition to the libraries shipping with the JDK, you also may want to look at the [Goldman Sach's collections](https://github.com/goldmansachs/gs-collections) which has an alternative implementation of parallel streams.
