### ISSUE TITLE
Cannot find a way to stop ringbuffer.

### ISSUE THREAD

**Issue by amosbird** [LMAX-Exchange/disruptor#198]
the disruptor's shutdown method has a comment saying `It is critical that publishing to the ring buffer has stopped before calling this method, otherwise it may never return.`. But I cannot find a way to stop ring buffer.

**Comment by mikeb01** [comment]
There isn't one.  Publishing to the ring buffer is handled by your own code, so you need some way of stopping your application code form publishing.

**Comment by amosbird** [comment]
well, the producer quits after generating 20 million events and disruptor.shutdown() is still blocking. I'm sure all the events have been consumed.

**Comment by mikeb01** [comment]
This will probably be due to your handlers not having finished processing the events.  The shutdown will wait until the handlers have completed processing all 20M events before completing.

**Comment by amosbird** [comment]
hmm, I have to do a executor.shutdown() so that it would exit normally.
