### ISSUE TITLE
Latency Performance

### ISSUE THREAD

**Issue by scottstephens** [LMAX-Exchange/disruptor#200]
Hi,

I've been experimenting with the library and have been unable to reproduce the latency profile described here: https://github.com/LMAX-Exchange/disruptor/wiki/Performance-Results. There are a few things I found odd as I was poking around, and I'm wondering if I'm missing something or perhaps the documentation is out of date. 

The first thing I was confused with is that the documentation describes latency tests being done with a three stage pipeline, but I didn't find any latency tests other than PingPongSequencedLatencyTest. Is that the recommended way to assess latency?

Running that test as it exists in the repo, I got these results:

      PingPongSequencedLatencyTest run 2 Disruptor org.HdrHistogram.Histogram@4c873330
       Value     Percentile TotalCount 1/(1-Percentile)
      1.0020 0.000000000000          1           1.00
      3.2260 0.500000000000    6189611           2.00
      4.2260 0.750000000000    9188965           4.00
      4.5280 0.875000000000   11891852           8.00
      4.5280 0.937500000000   11891852          16.00
      4.5280 0.968750000000   11891852          32.00
      4.5280 0.984375000000   11891852          64.00
      4.8290 0.992187500000   11928176         128.00
      <snip>
      #[Mean    =       3.0852, StdDeviation   =       5.0158]
      #[Max     =     575.9360, Total count    =     12020451]
      #[Buckets =           20, SubBuckets     =        32768]

The first question I had is what units are the results in. From reading the code, I think the results are in microseconds. Am I correct about that? The second weird thing is the total count. The test runs 3,000,000 iterations, so where did we get 12M histogram entities? I believe they come from the Histogram.recordValueWithExpectedInterval method, which includes a means of accounting for unreceived messages. It seems like it would be fine if the typical latency was small compared to the interval between messages, but in this case the interval is a microsecond, which is smaller than the median latency. Switching to the plain recordValue method yields this: 

      PingPongSequencedLatencyTest run 2 Disruptor org.HdrHistogram.Histogram@4c873330
       Value     Percentile TotalCount 1/(1-Percentile)
      1.5090 0.000000000000          1           1.00
      4.5280 0.500000000000    2940042           2.00
      4.5280 0.750000000000    2940042           4.00
      4.5280 0.875000000000    2940042           8.00
      4.5280 0.937500000000    2940042          16.00
      4.5280 0.968750000000    2940042          32.00
      4.5290 0.984375000000    2967321          64.00
      4.8300 0.992187500000    2993271         128.00
      <snip>
     #[Mean    =       4.5274, StdDeviation   =       1.1807]
     #[Max     =    1099.9680, Total count    =      3000001]
     #[Buckets =           20, SubBuckets     =        32768]

As far as I can tell, this looks like a fair latency test. I'm running on a Windows 7 box, with a core i7-4770 (quad core) processor. HyperThreading, speed stepping, and c states are disabled, and I'm using the java configuration options specified in the runme.sh file: -mx128m -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCApplicationStoppedTime -XX:+UseParNewGC -XX:+UseConcMarkSweepGC. I didn't do any pinning of threads or adjustment of interrupt settings, or test on linux.

So my best result is mean latency of ~4.5 microseconds, while the performance page says 52 nanoseconds. Any idea what I'm missing? My intuition says the linux/Windows difference and the thread pinning won't produce a ~100x improvement in median latency.

**Comment by epickrram** [comment]
The Disruptor has a number of different ways of signalling between threads (WaitStrategies). The test you are running has been altered to use the BlockingWaitStrategy, which always uses a j.u.c.Lock/Condition to communicate between producer and consumer threads.

Change the test to use a BusySpinWaitStrategy (lines 78 & 80), and you should get slightly more sensible results. I can't remember the machine setup from when those results were initially published, but to get really decent numbers, you'll want to use some form of thread affinity library to pin the producer/consumer threads to specific cores (and isolate those cores from the rest of the system).

**Comment by mikeb01** [comment]
As to the reason why we use `Histogram.recordValueWithExpectedInterval`, you are best off watching one of Gil Tene's [latency talks](https://www.youtube.com/watch?v=YpBwt-rO07o) around coordinated omission.
