### ISSUE TITLE
some spell mistakes in "Getting Started"

### ISSUE THREAD

**Issue by eXcellme** [LMAX-Exchange/disruptor#201]
>One of the best ways to improve performance in **concurrect** systems is to **ahere** to the Single Writer **Princple**, this applies to the Disruptor. 

One of the best ways to improve performance in **concurrent** systems is to **adhere** to the Single Writer **Principle**, this applies to the Disruptor.

**Comment by mikeb01** [comment]
Cheers, fixed.
