### ISSUE TITLE
How to terminate disruptor gracefully?

### ISSUE THREAD

**Issue by darouwan** [LMAX-Exchange/disruptor#202]
I am using disruptor to send some data to a tcp server, where each processor is a tcp client. This action is wrapped in a Quartz job.  Since buzy_spinning cost too much performance and blocking is too slow,  to save performance, I am trying to shutdown the disruptor thread when every job is done and create a new one when another job is created. I have discovered the Disruptor.shutdown() method, but it seems it just halts processors rather than terminate it. After executing the job several times the halted processor will be so many.   So any other method to terminate the disruptor? Or can I just terminate the processors and restart it later?

**Comment by mikeb01** [comment]
Halting the threads should cause the threads to exit cleanly assuming that your event process is not blocked in some other manner.  To ensure that every is cleaned up, you event processors should implement the LifecycleAware interface and they will be notified when the thread exits.  You can use this to ensure that all of the processors have completed.

Another approach to avoid starting and restarting would be to use a custom wait strategy that can be toggled externally between slow and a fast strategy.  E.g. between a Thread.sleep and a busy spin.  The quartz job cold notify the wait strategy to move into "high performance mode" and the system could switch it back when the job is complete.
