### ISSUE TITLE
RingBuffer.isPublished() incorrect in case of multiple producer RingBuffer

### ISSUE THREAD

**Issue by vbuciuc** [LMAX-Exchange/disruptor#203]
Hi,

RingBuffer.isPublished() returns false for sequences that have been published after the buffer wraps around once when multiple producer.

Here's a sample test case:

```
	@Test
	public void test() {
		RingBuffer<Void> buffer = RingBuffer.createMultiProducer(new EventFactory<Void>() {

			@Override
			public Void newInstance() {
				return null;
			}
		}, 2);
		
		
		buffer.publish(buffer.next());
		
		assertTrue("Sequence 0 should be published!!!", buffer.isPublished(0));

		buffer.publish(buffer.next());
		buffer.publish(buffer.next());

		assertTrue("Sequence 2 should be published!!!", buffer.isPublished(2));
		assertTrue("Sequence 0 should still be published!!!", buffer.isPublished(0));
	}
```

Regards,
Victor.

**Comment by mikeb01** [comment]
There is a long and sordid history* to that method and why it works the way that it does, mostly to do with a hack in one of our applications.  The main issue is that the method is misnamed and badly documented.  The upshot is that you probably shouldn't use that method.  I'm going to deprecate it to discourage its use.

* The method should really be named isAvailable as the use is to determine if a entry can be read for a given sequence.  Once the ring buffer is wrapped past a particular sequence number then the value for that sequence number is no longer is available.  Its use cases are very narrow and if used incorrectly could result in race conditions.

**Comment by vbuciuc** [comment]
I didn't actually need it so it's fine by me.

Regards,
Victor.
