### ISSUE TITLE
API changes report for Disruptor

### ISSUE THREAD

**Issue by lvc** [LMAX-Exchange/disruptor#205]
The review of API changes for the Disruptor library since 3.0.0 version: https://abi-laboratory.pro/java/tracker/timeline/disruptor/

Hope it will be helpful for users and maintainers of the library.

The report is generated for jars found at http://central.maven.org/maven2/com/lmax/disruptor/ according to https://wiki.eclipse.org/Evolving_Java-based_APIs_2.

Thank you.

![disruptor-1](https://user-images.githubusercontent.com/1517837/31113150-840d701a-a820-11e7-9bff-af8db95f77fd.png)

![disruptor-2](https://user-images.githubusercontent.com/1517837/31113151-840da3aa-a820-11e7-8993-c53b2c4eb50f.png)

**Comment by mikeb01** [comment]
Thanks, this is useful.  I'll add a link to the Readme.
