### ISSUE TITLE
Question: volatile or not when define event 

### ISSUE THREAD

**Issue by dingrui37** [LMAX-Exchange/disruptor#210]
When I  define the Event that will carry the data,  I want to know whether I need to add `volatile`  property to the value.   

```
public class SimpleEvent {
   private volatile String value; // volatile  or not?
   public void setValue(String value) {
       this.value = value;
   }
   public String getValue() {
       return value;
   }
}
```

**Comment by mikeb01** [comment]
No it is not required.  The barriers within the Disruptor will ensure that the message is visible when processed by the event handler.
