### ISSUE TITLE
Question:RingBuffer pad

### ISSUE THREAD

**Issue by dingrui37** [LMAX-Exchange/disruptor#211]
I do not understand the following code in the _RingBuffer.java_, who can help explain it? I know the fase sharing problem in sequence implementation, but the following pad is why? Thanks
```
    static
    {
        final int scale = UNSAFE.arrayIndexScale(Object[].class);
        if (4 == scale)
        {
            REF_ELEMENT_SHIFT = 2;
        }
        else if (8 == scale)
        {
            REF_ELEMENT_SHIFT = 3;
        }
        else
        {
            throw new IllegalStateException("Unknown pointer size");
        }
        BUFFER_PAD = 128 / scale; // why? what does this mean?
        // Including the buffer pad in the array base offset
        REF_ARRAY_BASE = UNSAFE.arrayBaseOffset(Object[].class) + (BUFFER_PAD << REF_ELEMENT_SHIFT); // why? what does this mean?
    }
```

**Comment by artyomkorzun** [comment]
The size of a pointer can be 4 or 8 bytes depending on a platform.
To get rid of the false sharing problem we need to pad a header of an array on 128 bytes (2 cache lines). 
BUFFER_PAD is the number of elements (pointers) in an array to skip out.

Simplified code:
```
BUFFER_PAD= 128 / scale; // number of elements in array to skip out 128 bytes
REF_ARRAY_BASE = UNSAFE.arrayBaseOffset(Object[].class) + 128;
```

**Comment by mikeb01** [comment]
It's used to pad the elements in the array away from the length parameter of the array.  So that when the write to one of the array elements occurs it won't share a cache line with the length.

I'll probably remove it for version 3.4 (with VarHandle support) as it messes with bounds checking elision that is available in JDK9.

**Comment by 18814127356** [comment]
@artyomkorzun why 128 bytes instead of 64?

**Comment by 18814127356** [comment]
@artyomkorzun  found answer in #158

**Comment by heycoolzhang** [comment]
> @artyomkorzun found answer in #158

thank you, i have the same question
