### ISSUE TITLE
how to set the number of consumer thread?

### ISSUE THREAD

**Issue by legatoo** [LMAX-Exchange/disruptor#212]
In my scenario, I have to keep the order of msg consuming. In order to get rid of the potential performance issue from single consuming, I create a dispatcher between Kafka and disruptor, dispatches messages to 8 disruptors by a certain rule to get the parallel consuming capability. 

On the disruptor side, I have to allow only one consumer thread to maintain the order. I see constructor `public Disruptor(final EventFactory<T> eventFactory,final int ringBufferSize,final Executor executor,final ProducerType producerType,final WaitStrategy waitStrategy)` accepts an executor which I can use `fixSizeThreadPool` to control consumer number, but it is deprecated. In the new constructor, I have to pass a threadFactory to disruptor.

My question:  what is the best practice to control consumer thread num? Do I have to implement custom threadFactory?

**Comment by mikeb01** [comment]
The Disruptor will create 1 thread per event handler, so the thread factory give the user options around how a thread should be created, e.g. thread naming, daemon mode, CPU affinity etc.

The executor approach was deprecated as a lot of users would pass fixed thread pools a size too small to support the appropriate number of threads and as a result the Disruptor would hang waiting for consumer that would never run.  Hence passing an Executor encouraged the wrong approach and understanding.

**Comment by legatoo** [comment]
Thanks, Mike, this part is clear.
may I ask another question, is it safe to share an EventHandler through multiple disruptors?

**Comment by mikeb01** [comment]
No, if the EventHandler has mutable state you will have multiple threads updating the same instance.  I would always create a new instance for each Disruptor.
