### ISSUE TITLE
MultiProducer BlockingWaitStrategy performance regression caused by 5c5a33850 

### ISSUE THREAD

**Issue by sbohrer** [LMAX-Exchange/disruptor#213]
We have a workload that uses a MultiProducer RingBuffer with BlockingWaitStrategy.  We have many producer threads that publish events to the buffer and a few threads that consume the events.  Recently we updated our disruptor version to 3.3.7 and noticed a massive performance slowdown.  I've bisected this back to commit 5c5a33850e8b7259f1ccf8bd7a213bf16035e309 "Signal the wait strategy if on next if the buffer is full."  Reverting this commit restores our original performance.

One other interesting piece of information is that we have some machines with an older Linux distribution running with a 4.4.x kernel and some machines with a newer Linux distribution running with a 4.9.x kernel.  Java version is 1.8.0_72 in both cases.  Interestingly with the exact same workload, only the newer Linux distribution machines exhibit the slowdown.  I have not tried upgrading kernels on the old Linux distribution machines to see if the kernel difference is what is causing the slowdown or if it is some other system library.

What problem was 5c5a33850e8b7259f1ccf8bd7a213bf16035e309 "Signal the wait strategy if on next if the buffer is full." trying to solve?

**Comment by mikeb01** [comment]
I was trying to fix an issue that was observed in log4j with some additional belt and braces, but it turned out to be a bug in log4j not the Disruptor.  It probably isn't required.  I'll revert the change for the next release.

You could try using the tryNext/tryPublishEvent and retry on failed publish, which will avoid the additional call to signal the lock in the BlockingWaitStrategy.

**Comment by sbohrer** [comment]
I've tested with 3.3.7 spinning calling tryNext() until it succeeds and it works, but it seems like an ugly hack.  I think I would prefer if the commit was reverted if you don't think it is actually needed.

**Comment by mikeb01** [comment]
Fixed in b84be41.
