### ISSUE TITLE
SleepingWaitStrategy causing 100% CPU with one consumer

### ISSUE THREAD

**Issue by matthewrj** [LMAX-Exchange/disruptor#219]
I am using [opencensus](https://github.com/census-instrumentation/opencensus-java), a metrics and tracing library that uses the disruptor internally. When my application is idle I experience 100% CPU which I have traced to the single disruptor consumer thread.

I am experiencing this on both my Ubuntu box and in the cloud.
Ubuntu box:
Ubuntu 17.10
Linux version 4.13.0-17-generic (buildd@lcy01-amd64-011) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3)) #20-Ubuntu SMP Mon Nov 6 10:04:08 UTC 2017
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

Cloud os: https://cloud.google.com/container-optimized-os/docs/

I have created a minimal project that reproduces the issue: https://github.com/matthewrj/opencensus-bug/tree/master

Forcing the Opencensus library to use BlockingWaitStrategy by class path patching makes the CPU usage go to 0%.

**Comment by mikeb01** [comment]
Could you post a stack trace showing the high CPU thread?  Do you know what the event handler set up looks like?  If one of the event handler is gated on one that is blocked (or exited due to error), then you can see 100% CPU in the dependent handler.

**Comment by matthewrj** [comment]
```
"OpenCensus.Disruptor-0" #14 daemon prio=5 os_prio=0 tid=0x00007fcfc6222800 nid=0x3a5a runnable [0x00007fcf9d397000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
        at com.lmax.disruptor.SleepingWaitStrategy.applyWaitMethod(SleepingWaitStrategy.java:82)
        at com.lmax.disruptor.SleepingWaitStrategy.waitFor(SleepingWaitStrategy.java:55)
        at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:124)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
Here is the set up code: https://github.com/census-instrumentation/opencensus-java/blob/master/impl/src/main/java/io/opencensus/impl/internal/DisruptorEventQueue.java

**Comment by mikeb01** [comment]
It looks like parkNanos(1) now produces a busy spin.  Increasing it to parkNanos(100) sees the CPU use drop off.

**Comment by matthewrj** [comment]
Thank you for the fast turnaround!

**Comment by bogdandrutu** [comment]
Thanks @mikeb01 for the fix. Is it possible to release this changes before 3.4.0?

**Comment by mikeb01** [comment]
I'll include it in 3.4.0 and 3.3.9.

**Comment by bogdandrutu** [comment]
@mikeb01 Do you have an estimate for these releases?

**Comment by bogdandrutu** [comment]
@mikeb01 just saw the artifacts. Thanks.

**Comment by Stephenkk204** [comment]
@mikeb01 I also encounter this issue. my disruptor is disruptor-3.4.2. I am using SleepingWaitStrategy. please help to check it.

follwoing is the stack trace:
"Thread-9157" #40808 prio=6 os_prio=0 tid=0x0000aaaae200d000 nid=0xca2f runnable [0x0000ffff6a059000]
   java.lang.Thread.State: TIMED_WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
	at com.lmax.disruptor.SleepingWaitStrategy.applyWaitMethod(SleepingWaitStrategy.java:92)
	at com.lmax.disruptor.SleepingWaitStrategy.waitFor(SleepingWaitStrategy.java:65)
	at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
	at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:148)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- <0x000000073a233c00> (a java.util.concurrent.ThreadPoolExecutor$Worker)

**Comment by strange111** [comment]
> 
> 
> @mikeb01 I also encounter this issue. my disruptor is disruptor-3.4.2. I am using SleepingWaitStrategy. my application is idle I experience about 100% CPU. please help to check it.
> 
> follwoing is the stack trace:
> "Thread-9157" #40808 prio=6 os_prio=0 tid=0x0000aaaae200d000 nid=0xca2f runnable [0x0000ffff6a059000]
> java.lang.Thread.State: TIMED_WAITING (parking)
> at sun.misc.Unsafe.park(Native Method)
> at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:338)
> at com.lmax.disruptor.SleepingWaitStrategy.applyWaitMethod(SleepingWaitStrategy.java:92)
> at com.lmax.disruptor.SleepingWaitStrategy.waitFor(SleepingWaitStrategy.java:65)
> at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
> at com.lmax.disruptor.WorkProcessor.run(WorkProcessor.java:148)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> 
> Locked ownable synchronizers:
> - <0x000000073a233c00> (a java.util.concurrent.ThreadPoolExecutor$Worker)

Hi @Stephenkk204 , could you please tell me what java version are you using and on which OS?
We are having exactly the same issue with this same version of disruptor(3.4.2).
Thanks alot!
BR,
Strange

**Comment by Stephenkk204** [comment]
jdk: OpenJDK Runtime Environment (build 1.8.0_212)
OS: suse 12
mikeb01 recommend experimenting with specifying the sleepTimeNs on the SleepingWaitStrategy to see if larger values will allow the thread to idle

**Comment by strange111** [comment]
Thanks for the fast reply.
We are having the same issue  on : 
OS: SLES 15 with Java vesion: 1.8.0_221-b11. But on the other hand, we have tried to do same execution on OS: Ubuntu 16.04.6 LTS with same java version and this error did not show up. Maybe this information helps you somehow.
BR,
Strange

**Comment by strange111** [comment]
> 
> 
> jdk: OpenJDK Runtime Environment (build 1.8.0_212)
> OS: suse 12
> mikeb01 recommend experimenting with specifying the sleepTimeNs on the SleepingWaitStrategy to see if larger values will allow the thread to idle

@Stephenkk204 thanks for the fast reply.
We are having the same issue on :
OS: SLES 15 with Java vesion: 1.8.0_221-b11. But on the other hand, we have tried to do same execution on OS: Ubuntu 16.04.6 LTS with same java version and this error did not show up. Maybe this information helps you somehow.
BR,
Strange

**Comment by rogerhu** [comment]
Per https://github.com/LMAX-Exchange/disruptor/issues/463#issuecomment-2181358499 should parkNanos(1) be adjusted as well? Seeing similar issues in our stack traces.
