### ISSUE TITLE
SleepingWaitStrategy identified as hotspot

### ISSUE THREAD

**Issue by rlindooren** [LMAX-Exchange/disruptor#220]
This is not a bug report but a question about the expected behaviour of the `SleepingWaitStrategy` component.

I was profiling an application, using Yourkit, that our team built. And I noticed that a thread `OpenCensus.Disruptor-0` used CPU time perhaps a bit more than I would expect it to.
That lead me to https://github.com/census-instrumentation/opencensus-java/issues/801 and I updated our application to make use of OpenCensus 0.12.2 which includes the fix from https://github.com/LMAX-Exchange/disruptor/issues/219

When profiling our application again, the `SleepingWaitStrategy` is still reported as a hotspot by Yourkit.

I added a screenshot from Yourkit, it shows the hotspots of our idle application over a period of about 5 minutes:

<img width="1421" alt="yourkit-disruptor-hotspot" src="https://user-images.githubusercontent.com/703192/36779817-868cf8e0-1c71-11e8-8e62-d15715a83566.png">

My question is: is this expected behaviour?

**Comment by mikeb01** [comment]
Fixed in 3.3.9 and 3.4.0.  It turns out that newer versions of Linux interpret (the underlying syscall of) LockSupport.parkNanos(n) as a busy spin if n is sufficiently small.  We've increased it to 100 and that lowers the CPU usage in our testing.  I've also made the SleepingWaitStrategy take a constructor arg of the sleep time if our new default value still causes issues.

**Comment by rlindooren** [comment]
To be complete: the screenshot I attached is from a profiling session when making use of version 3.3.9. Going to the code of `SleepingWaitStrategy` I can see it includes the `sleepTimeNs` change you describe (I was already aware of this change because of https://github.com/LMAX-Exchange/disruptor/issues/219).
Since the issue is already closed I then just assume the high invocation count is expected behaviour.

**Comment by rlindooren** [comment]
No problem. Thanks for your answers.
