### ISSUE TITLE
100% cpu even when application is idle

### ISSUE THREAD

**Issue by legatoo** [LMAX-Exchange/disruptor#221]
I created 10 disruptor, each one is configured as below:

```
disruptor = new Disruptor<>(
            new GeQMsgFactory(),
            this.ringbufferSize,
            new SingleThreadFactory(),
            ProducerType.SINGLE,
            new YieldingWaitStrategy()
        );
```
the reason I created 10 disruptor is that I wan to dispatch msg to difference queue with single thread consume to maintain the order. when the application is idle, I notice the cpu usage is 100%. and the jstack shows 10 disruptor threads are using cpu. My computer is  8core centos7.

```
"Thread-27" #191 prio=5 os_prio=0 tid=0x00007f0b6e4d5800 nid=0x31f2 runnable [0x00007f0a3f0ef000]
   java.lang.Thread.State: RUNNABLE
        at java.lang.Thread.yield(Native Method)
        at com.lmax.disruptor.YieldingWaitStrategy.applyWaitMethod(YieldingWaitStrategy.java:57)
        at com.lmax.disruptor.YieldingWaitStrategy.waitFor(YieldingWaitStrategy.java:39)
        at com.lmax.disruptor.ProcessingSequenceBarrier.waitFor(ProcessingSequenceBarrier.java:56)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by epickrram** [comment]
`YieldingWaitStrategy` is quite CPU-intensive, as it is designed for low-latency message passing.

You can significantly reduce the CPU-time used by using the `BlockingWaitStrategy`, at the cost of higher latency.

**Comment by legatoo** [comment]
@epickrram thanks for your advice, I will try `BlockingWaitStrategy `. Do you have any benchmark on how much latency `BlockingWaitStrategy ` will cost?

**Comment by epickrram** [comment]
You should perform your own testing using realistic data on target hardware. Any other numbers are just hand-waving..
