### ISSUE TITLE
BlockingWaitStrategy CPU 100%

### ISSUE THREAD

**Issue by gumandy** [LMAX-Exchange/disruptor#222]
BlockingWaitStrategy
`while ((availableSequence = dependentSequence.get()) < sequence)
        {
            barrier.checkAlert();
        }`
when pre consumer is too slow to satisfy current consumer， cpu 100%

**Comment by mikeb01** [comment]
Yes this will happen.  If your dependent stage is quite expensive then you should consider separating the work load into 2 Disruptors and have the "pre consumer" publish to the 2nd ring buffer that has the "current consumer" as it's sole consumer.
