### ISSUE TITLE
Ringbuffer can't put msg when excption occur in handler

### ISSUE THREAD

**Issue by saviolee** [LMAX-Exchange/disruptor#223]
When excption occur in handler, the default exceptionHandler just log error and re-throw the exception. This would cause the status of that slot incorrect, and the ringbuffer would be unavailable when provider comes to that slot.

**Comment by mikeb01** [comment]
The default exception handler takes the most conservative approach as the default behaviour, i.e. stopping on failure.  We felt that quietly skipping over exceptions and continuing to process messages as a default behaviour would less desirable.  However you are free to write and use your own exception handler to implement the behaviour appropriate to your application.
