### ISSUE TITLE
Dead and stale Download links

### ISSUE THREAD

**Issue by toddjonker** [LMAX-Exchange/disruptor#224]
I'm finding it hard to determine what's the latest code release, and find its documentation.

  1. Some GitHub pages have a "download" link <https://github.com/LMAX-Exchange/disruptor/wiki/Downloads> that is dead and redirects to the wiki Home page.  I've found this problem on these pages:
      * http://lmax-exchange.github.io/disruptor/
          * The very first link on the page
          * Another under "Great What do I do next?"
      * https://github.com/LMAX-Exchange/disruptor/wiki/Getting-Started

  2. The "Maven Central" link near the top of [Getting Started](https://github.com/LMAX-Exchange/disruptor/wiki/Getting-Started) issues a search that lists a bunch of code from other projects, and it's not clear which is "official".

  4. [A recent post to the Google group](https://groups.google.com/forum/#!topic/lmax-disruptor/ZfepCTA2wbM) announces 3.4.1 and 3.3.10 but doesn't mention the correct Maven dependency coordinates.  Looking at the search linked above, it appears to be `com.lmax:disruptor` but guessing at this strikes me as dangerous.

  5. The [Dependency management using maven central repository](https://github.com/LMAX-Exchange/disruptor/wiki/Using-Disruptor-In-Your-Project) section documents a different groupId, 
`com.googlecode.disruptor`.

  6. The link at https://github.com/LMAX-Exchange/disruptor/wiki/Using-Disruptor-In-Your-Project works, pointing at https://code.google.com/archive/p/disruptor/downloads ... but that page is stale, since the last release there is 2.10.3.

  3. The [Change Log](https://github.com/LMAX-Exchange/disruptor/wiki/Change-Log) also stops at 2.10.3

  7. The published [API Docs](http://lmax-exchange.github.io/disruptor/docs/index.html) don't have a release version, so it's not clear whether that's up to date; the copyright line of "2011 - 2014" suggests that it's stale too.

Regardless, I'm looking forward to trying out this library for my project. Thanks for releasing it!

**Comment by mikeb01** [comment]
Cheers.
1) Deleted references to the downloads page.  All maven central all the time :-).
2) Updated search parameters to include group id.
3) Will remember for next time.
4) Deleted page, no more useful than looking at maven and misleading when not kept up to date.
5) Deleted page, misleading.
6) Deleted page, changelog is in README.md
7) Updated.

**Comment by toddjonker** [comment]
Thanks for the quick fix!  As a minor follow-up, there's not an easy-to-discover link to the Google group from the wiki.  It would be nice to have some of those important links in the readme.
