### ISSUE TITLE
Provide javadoc for `TimeoutBlockingWaitStrategy`

### ISSUE THREAD

**Issue by turbanoff** [LMAX-Exchange/disruptor#229]
All `WaitStrategy` implementations has very useful javadoc except `TimeoutBlockingWaitStrategy`. It would be nice to have it :)

**Comment by nithinuppalapati1989** [comment]
Also one question, does it employ busy wait in waitFor method. Will it consume CPU cycles when it is executing waitFor method?

**Comment by initiala69** [comment]
I am actually trying out TimeoutBlockingWaitStrategy and I can confirm it does consume CPU cycles.  Profiling the app shows most time spent on com.lmax.disruptor.TimeoutBlockingWaitStrategy.waitFor()

**Comment by nithinuppalapati1989** [comment]
But is it the elapsed time or actual CPU time you are talking about?

**Comment by initiala69** [comment]
Actually apologies I forgot to set the timeout on one of my ring buffers so the default must have been very small, causing the high CPU consumption.  I have now set the timeout to a few seconds and CPU usage (according to Linux "top" command) is much much lower now
