### ISSUE TITLE
BUFFER_PAD << REF_ELEMENT_SHIFT always 128 ?

### ISSUE THREAD

**Issue by jiacai2050** [LMAX-Exchange/disruptor#233]
Source code can be found [here](https://github.com/LMAX-Exchange/disruptor/blob/master/src/main/java/com/lmax/disruptor/RingBuffer.java#L53), it seems that `BUFFER_PAD << REF_ELEMENT_SHIFT` is always equal to 128, if so why not use literal directly?

**Comment by mikeb01** [comment]
Good point.  @nitsanw I think you wrote the original patch.  We seem effectively dividing then multiplying by the same value?

**Comment by nitsanw** [comment]
No idea... it's been a while. I agree it seems odd.

**Comment by amoswxz** [comment]
@jiacai2050  Do you understand?

**Comment by mikeb01** [comment]
I've had a bit more of a look through the code and I think I understand why it is the way it is.  One of the benefit of the current implementation is that there is only one numeric literal value.  So if the value of 128 is changed (e.g. to 256) the rest of the calculation will remain correct.  So on balance I think leaving the implementation as is, would be best.
