### ISSUE TITLE
Modularize Disruptor JAR

### ISSUE THREAD

**Issue by Jeff-G** [LMAX-Exchange/disruptor#234]
Add a module-info.java file to the project, in order to provide official support for Java 9+.  Without this, users are unable to run jlink against dependent Java code.

**Comment by mikeb01** [comment]
I have some outstanding work to support JDK 9 with a multi-version jar.  That is stuck behind some internal work to update out build system.  When that is available I'll look at the module-info.java.  I want to continue to support older JDKs for a period of time.  If you are familiar with Java modules and want to contribute, that would be welcomed.

**Comment by Jeff-G** [comment]
I'm not 100% certain what packages you want to be part of the public API, but I would recommend something similar to the following:

    // module-info.java, added to disruptor/src/main/java/
    module com.lmax.disruptor {
        requires java.logging;
        requires java.management;
        requires jdk.unsupported; // This provides sum.misc.Unsafe

        exports com.lmax.disruptor;
        // Also export com.lmax.disruptor.dsl and com.lmax.disruptor.util,
        // if they are part of the public interface
    }

**Comment by mikeb01** [comment]
How would that work if I wanted to do a build that would still work with JDK 7.

**Comment by Jeff-G** [comment]
I have read from a number of sources that module-info.java *should* be ignored by Java 8.  Nowhere could I find a claim for what happens when a modular JAR is used with Java 7.  I would probably just add it in and test in all versions of Java that you intend to support.

**Comment by Jeff-G** [comment]
I have tested with the module file indicated above in JDK 11, and it appears to work when used with Log4j2.  I have also discovered that there are some tools (Eclipse IDE and the Javadoc utility) that don't fully support multi-release JAR files.  If you convert this to a multi-release JAR file, please also add the following to the manifest file in the JAR:

Automatic-Module-Name: com.lmax.disruptor

**Comment by mikeb01** [comment]
Multi-release jars currently break our build tool, which is using a legacy version of ASM.  I'm working on updating it, but it is queued behind a number of Yak shaving exercises.  I'll look at including this once we start supporting JDK 9+.

**Comment by skay2k** [comment]
Analysing disruptor-3.3.2.jar  with jdeps shows some incompatibilities with JDK 11 ; do you know if a new release is comming ? :

`disruptor-3.4.2.jar -> jdk.unsupported
   com.lmax.disruptor.MultiProducerSequencer          -> sun.misc.Unsafe                                    JDK internal API (jdk.unsupported)
   com.lmax.disruptor.RingBufferFields                -> sun.misc.Unsafe                                    JDK internal API (jdk.unsupported)
   com.lmax.disruptor.Sequence                        -> sun.misc.Unsafe                                    JDK internal API (jdk.unsupported)
   com.lmax.disruptor.util.Util                       -> sun.misc.Unsafe                                    JDK internal API (jdk.unsupported)
   com.lmax.disruptor.util.Util$1                     -> sun.misc.Unsafe                                    JDK internal API (jdk.unsupported)

Warning: JDK internal APIs are unsupported and private to JDK implementation that are
subject to be removed or changed incompatibly and could break your application.
Please modify your code to eliminate dependence on any JDK internal APIs.
For the most recent update on JDK internal API replacements, please check:
https://wiki.openjdk.java.net/display/JDK8/Java+Dependency+Analysis+Tool

JDK Internal API                         Suggested Replacement
----------------                         ---------------------
sun.misc.Unsafe                          See http://openjdk.java.net/jeps/260`

**Comment by mikeb01** [comment]
Have you tried the jdk-varhandles branch?

**Comment by yilmazorhan** [comment]
Hello,
varhandles branch seems fine.  Can you release alpha/beta version? So we can test it.
Thanks
