### ISSUE TITLE
WorkPool when thread num less than handler num, producer and consumers blocked!

### ISSUE THREAD

**Issue by vonzhou** [LMAX-Exchange/disruptor#235]
The demo code is [https://github.com/vonzhou/javase-concourse/blob/master/src/main/java/com/vonzhou/learn/javase/disruptor/MultiConsumer4.java](url)

thread num < work handler num, when RingBuffer is full, producer and consumer blocked on wait strategy.

**Comment by mikeb01** [comment]
That is correct, you must have at least one thread per consumer and one for each worker in the pool.  This is why using an Executor is deprecated.  You should use a ThreadFactory.  This will ensure that you will have enough threads.
