### ISSUE TITLE
not best practices for multi thread consumer?

### ISSUE THREAD

**Issue by terryzhu** [LMAX-Exchange/disruptor#237]
I just want to replace the ArrayBlockingQueue by Disruptor.
My scenario is just need a MPMC queue.

I've read [Performance Results](https://github.com/LMAX-Exchange/disruptor/wiki/Performance-Results).
It says 4-7X faster than ABQ.
I've also read some guides, the [common guide](https://github.com/LMAX-Exchange/disruptor/wiki/Getting-Started) doesn't fit my requirements because I want an event to be consumer by only one of the consumer, but the guide is SPSC.

I knew someone suggested the [WorkerPool](https://github.com/LMAX-Exchange/disruptor/issues/150), [WorkerPool](https://github.com/LMAX-Exchange/disruptor/issues/150)
And I've also test a 2-layer 12-thread-consumers WorkerPool(MacBookPro 2.3 GHz Intel Core i5 java version "1.8.0_181"),produce 100M simple object by single producer.It's performance is almost same as ABQ.

```
Disruptor:
Single Produer (Publish 100M EventA) -> disruptor with 12-thread-consumers WorkerPool (transfer to EventB) -> 12-thread-consumers WorkerPool

ABQ:
Single Produer (put 100M EventA to ABQ) -> 12 threads take(transfer to EventB and put into another ABQ) -> 12 threads ABQ take
```

EventA and EventB and transfer is simple which we can consider they are not the bottleneck
If I replace 12-thread-consumers with single thread EventHandler(for Disruptor scenario), and replace 12 threads with 1 thread(for ABQ scenario), the Performance of Disruptor is 5X faster than ABQ

So my question is:
Is the discurptor only suitable for SPSC/MPSC/Multicast/Diamond, not suitable for MPMC?

**Comment by mikeb01** [comment]
The WorkHandler is an option, but if your use case is best served by a MPMC queue and doesn't require other features of the Disruptor, e.g. you don't the multiple producer consumers to be part of a graph of dependencies, then you may want to look at a queue from [agrona](https://github.com/real-logic/agrona) or [JC Tools](https://github.com/JCTools/JCTools).
