### ISSUE TITLE
How is it possible to partition event handling process on a slow consumer scenario while maintaining thread affinity?

### ISSUE THREAD

**Issue by sj-jafari** [LMAX-Exchange/disruptor#240]
I have a scenario in an online order management system, on which I receive messages from an external resource, save them in a disruptor and handle them with a single consumer. 
The consuming process is rather slow due to db calls and etc, making the whole message processing system to perform poorly. A solution could be paralellizing the event handling process by defining multiple consumers and balance the load among them. The only problem is that some messages have to be processed in order (for example messages of a customer or messages with the same ID). 
Is it possible to direct messages with some specific characteristic to the same consumer thread (could be called thread affinity)?

**Comment by MendelMonteiro** [comment]
You can implement the dispatching logic in your handlers. As each handler will see all the messages sent to the Disruptor you have to decide which are ignored.
As a very simple example if you have an ID and two event handlers one could ignore all the even IDs and the other could ignore all the odd ones.
