### ISSUE TITLE
Can the number of consumers be greater than the number of threads?

### ISSUE THREAD

**Issue by brucelwl** [LMAX-Exchange/disruptor#241]
I set the queue length to 8 and created five consumer objects, but fixed the number of thread pools to 2, and I wanted to deliver 100 pieces of data. As a result, when I delivered the eighth piece of data (starting at zero), the program went into a dead loop. Why, but it worked fine when the number of consumers was less than or equal to the thread data?

 @Test
    public void test1() throws InterruptedException {

        RingBuffer<Order> ringBuffer = RingBuffer.create(ProducerType.MULTI,
                Order::new, 8, new YieldingWaitStrategy());

        SequenceBarrier sequenceBarrier = ringBuffer.newBarrier();

        int consumerCount = 5;

        MyConsumer[] consumers = new MyConsumer[consumerCount];

        for (int i = 0; i < consumerCount; i++) {
            consumers[i] = new MyConsumer("c_" + i);
        }

        WorkerPool<Order> workerPool = new WorkerPool<>(ringBuffer, sequenceBarrier, new WorkerPoolExceptionHandler(), consumers);

        ringBuffer.addGatingSequences(workerPool.getWorkerSequences());
        workerPool.start(Executors.newFixedThreadPool(2));

        int producerCount = 1;
        CyclicBarrier cyclicBarrier = new CyclicBarrier(producerCount, () -> {
            System.out.println("start");
        });

        for (int i = 0; i < producerCount; i++) {
            Producer producer = new Producer(ringBuffer);
            new Thread(() -> {
                try {
                    cyclicBarrier.await();
                    for (int j = 0; j < 100; j++) {
                        String uuid = UUID.randomUUID().toString();
                        producer.sendData(uuid);
                    }
                } catch (InterruptedException | BrokenBarrierException e) {
                    e.printStackTrace();
                }
            }).start();
        }
        Thread.sleep(150000000);
        System.out.println("task count: " + consumers[0].getCount());

    }

**Comment by MendelMonteiro** [comment]
Each consumer that you provide to the `WorkerPool` will create an associated `WorkProcessor` inside the `WorkerPool` and when the pool is started each `WorkProcessor` will be run.  The `run()` method of the `WorkProcessor` is a blocking method that will wait for the next sequence and then forward the event to the `EventHandler` when it is available.

You are essentially trying to start 8 blocking methods with only 2 threads.

This begs the question, why are you trying to have more consumers than threads?  Are you doing asynchronous IO in your consumer?

**Comment by brucelwl** [comment]
Thank you very much for your reply. I've found the reason. The reason is that when the producer delivers data to the queue, it decides whether the next delivery sequence is smaller than the current minimum consumption sequence number, and only if it is smaller, it will continue to deliver. But when there are more than one consumers, the excess consumption sequence number is always - 1, so live The producer has been blocking and waiting. In the end, I would like to ask if disruptor is suitable for asynchronous IO operation.

**Comment by brucelwl** [comment]
> Each consumer that you provide to the `WorkerPool` will create an associated `WorkProcessor` inside the `WorkerPool` and when the pool is started each `WorkProcessor` will be run. The `run()` method of the `WorkProcessor` is a blocking method that will wait for the next sequence and then forward the event to the `EventHandler` when it is available.
> 
> You are essentially trying to start 8 blocking methods with only 2 threads.
> 
> This begs the question, why are you trying to have more consumers than threads? Are you doing asynchronous IO in your consumer?

Thank you very much for your reply. I've found the reason. The reason is that when the producer delivers data to the queue, it decides whether the next delivery sequence is smaller than the current minimum consumption sequence number, and only if it is smaller, it will continue to deliver. But when there are more than one consumers, the excess consumption sequence number is always - 1, so live The producer has been blocking and waiting. In the end, I would like to ask if disruptor is suitable for asynchronous IO operation.

**Comment by MendelMonteiro** [comment]
That's right, a sequence will only be released once all the consumers have finished processing the event associated with it.  And as you have essentially 6 consumers that will never run, the initial sequences will never be released.
