### ISSUE TITLE
Lost data issue

### ISSUE THREAD

**Issue by baisijian** [LMAX-Exchange/disruptor#243]
I Use One Producer and muti comsumer, if remove producer sleep, and use small buffer size, the data will be lost. I want to know what cause the problem, thanks

code is

public class A {
    public static void main(String[] args) throws InterruptedException {

        LongEventFactory longEventFactory = new LongEventFactory();

        int bufferSize = 8;

        RingBuffer<LongEvent> ringBuffer = RingBuffer.createSingleProducer(longEventFactory, bufferSize);

        SequenceBarrier sequenceBarrier = ringBuffer.newBarrier();

        WorkHandler<LongEvent>[] workHandlers = new WorkHandler[3];
        for (int i = 0; i <= 2; i++) {
            workHandlers[i] = new LongEventHandler();
        }

        WorkerPool<LongEvent> workerPool = new WorkerPool<LongEvent>(ringBuffer, sequenceBarrier, new ExceptionHandle(), workHandlers);
        ExecutorService executor = Executors.newFixedThreadPool(3);

        workerPool.start(executor);

        for (int x = 0; x < 100; x++) {
            long sequence = ringBuffer.next();
            try {
                LongEvent event = ringBuffer.get(sequence);
                event.setValue(x);
        
            } finally {
                ringBuffer.publish(sequence);
            }
        }
        //workerPool.halt();
        //executor.shutdown();
    }
}

execute result:

pool-1-thread-3 Event：17
pool-1-thread-1 Event：16
pool-1-thread-2 Event：18
pool-1-thread-1 Event：92
pool-1-thread-3 Event：75
pool-1-thread-1 Event：94
pool-1-thread-2 Event：93
pool-1-thread-1 Event：96
pool-1-thread-3 Event：95
pool-1-thread-1 Event：98
pool-1-thread-2 Event：97
pool-1-thread-1 Event：92
pool-1-thread-3 Event：99
pool-1-thread-1 Event：94
pool-1-thread-2 Event：93
pool-1-thread-1 Event：96
pool-1-thread-3 Event：95
pool-1-thread-1 Event：98
pool-1-thread-2 Event：97
pool-1-thread-1 Event：92
pool-1-thread-3 Event：99
pool-1-thread-1 Event：94
pool-1-thread-2 Event：93
pool-1-thread-1 Event：96
pool-1-thread-3 Event：95
pool-1-thread-1 Event：98
pool-1-thread-2 Event：97
pool-1-thread-1 Event：92
pool-1-thread-1 Event：94
pool-1-thread-3 Event：99
pool-1-thread-1 Event：95
pool-1-thread-2 Event：93
pool-1-thread-1 Event：97
pool-1-thread-3 Event：96
pool-1-thread-1 Event：99
pool-1-thread-1 Event：93
pool-1-thread-2 Event：98
pool-1-thread-1 Event：94
pool-1-thread-3 Event：92
pool-1-thread-1 Event：96
pool-1-thread-2 Event：95
pool-1-thread-1 Event：98
pool-1-thread-3 Event：97
pool-1-thread-1 Event：92
pool-1-thread-2 Event：99
pool-1-thread-1 Event：94
pool-1-thread-3 Event：93
pool-1-thread-1 Event：96
pool-1-thread-2 Event：95
pool-1-thread-1 Event：98
pool-1-thread-3 Event：97
pool-1-thread-1 Event：92
pool-1-thread-2 Event：99
pool-1-thread-1 Event：94
pool-1-thread-3 Event：93
pool-1-thread-1 Event：96
pool-1-thread-2 Event：95
pool-1-thread-1 Event：98
pool-1-thread-3 Event：97
pool-1-thread-1 Event：92
pool-1-thread-2 Event：99
pool-1-thread-1 Event：94
pool-1-thread-3 Event：93
pool-1-thread-1 Event：96
pool-1-thread-2 Event：95
pool-1-thread-1 Event：98
pool-1-thread-3 Event：97
pool-1-thread-1 Event：92
pool-1-thread-2 Event：99
pool-1-thread-1 Event：94
pool-1-thread-3 Event：93
pool-1-thread-1 Event：96
pool-1-thread-2 Event：95
pool-1-thread-1 Event：98
pool-1-thread-3 Event：97
pool-1-thread-1 Event：92
pool-1-thread-2 Event：99
pool-1-thread-2 Event：95
pool-1-thread-1 Event：94
pool-1-thread-3 Event：93
pool-1-thread-1 Event：97
pool-1-thread-2 Event：96
pool-1-thread-1 Event：99
pool-1-thread-3 Event：98
pool-1-thread-1 Event：93
pool-1-thread-2 Event：92
pool-1-thread-1 Event：95
pool-1-thread-3 Event：94
pool-1-thread-1 Event：97
pool-1-thread-2 Event：96
pool-1-thread-1 Event：99
pool-1-thread-3 Event：98
pool-1-thread-1 Event：93
pool-1-thread-2 Event：92
pool-1-thread-1 Event：95
pool-1-thread-3 Event：94
pool-1-thread-1 Event：97
pool-1-thread-2 Event：96
pool-1-thread-1 Event：99
pool-1-thread-3 Event：98

**Comment by mikeb01** [comment]
You've missed adding the gating sequences to the ring buffer:
```
    WorkerPool<LongEvent> workerPool = new WorkerPool<LongEvent>(ringBuffer, sequenceBarrier, new ExceptionHandle(), workHandlers);
    ringBuffer.addGatingSequences(workerPool.getWorkerSequences());
```
Or even better, use the Disruptor class which is less error prone.
```
        WorkHandler<LongEvent>[] workHandlers = new WorkHandler[3];
        for (int i = 0; i <= 2; i++)
        {
            workHandlers[i] = new LongEventHandler();
        }
        Disruptor<LongEvent> disruptor = new Disruptor<>(LongEvent.FACTORY, 8, DaemonThreadFactory.INSTANCE);
        disruptor.handleEventsWithWorkerPool(workHandlers);

        RingBuffer<LongEvent> ringBuffer = disruptor.start();
```

**Comment by baisijian** [comment]
thanks
