### ISSUE TITLE
Need to reset event when translateTo occur exception in RingBuffer.translateAndPublish?

### ISSUE THREAD

**Issue by luoxn28** [LMAX-Exchange/disruptor#244]
If translateTo occur exception in RingBuffer.translateAndPublish，like this:
```java
private <A> void translateAndPublish(EventTranslatorOneArg<E, A> translator, long sequence, A arg0)
{
    try
    {
        // exception occur, this event is not ok
        translator.translateTo(get(sequence), sequence, arg0);
    }
    finally
    {
        sequencer.publish(sequence);
    }
}
```
If occur exception, this event is incomplete, may it's old data，need reset this it？like this：
```java
private <A> void translateAndPublish(EventTranslatorOneArg<E, A> translator, long sequence, A arg0)
{
    try
    {
        translator.translateTo(get(sequence), sequence, arg0);
    }
    catch (Exception e) {
        resetElementAt(sequence);
        throw e;
    }
    finally
    {
        sequencer.publish(sequence);
    }
}

protected final void resetElementAt(long sequence) {
    entries[BUFFER_PAD + (int) (sequence & indexMask)] = eventFactory.newInstance();
}
```

**Comment by mikeb01** [comment]
Personally I would do the reset in the EventHandler after the event is being processed.  In the case of an exception you will need to leave some information on the event that will indicate that the event has been processed correctly, so if an exception occurs, that information will indicate that the data is not complete so the handle will discard the data, but can still reset the state of the event object.

**Comment by luoxn28** [comment]
As you say with this handling, flexibility is better for developers.
