### ISSUE TITLE
Does disruptor supports conflation queue

### ISSUE THREAD

**Issue by jainhj** [LMAX-Exchange/disruptor#248]
I want to publish the price updates to my consumers. I have lot of consumers whch might slow down my producer. Also, I only need latest price. So want to use conflation. Does disruptor supports that.

**Comment by juddgaddie** [comment]
Something like this https://www.lmax.com/blog/staff-blogs/2013/03/07/the-coalescing-ring-buffer/ ?

**Comment by jainhj** [comment]
Thanks juddgaddie and mikeb01. I will check if CoalescingRingBuffer would help me out. Could see that there is a limitation of single consumer?
