### ISSUE TITLE
How to use ProducerType.MULTI and ProducerType.SINGLE, is there any guideline for us?

### ISSUE THREAD

**Issue by eric-chao** [LMAX-Exchange/disruptor#249]
How to use ProducerType.MULTI and ProducerType.SINGLE, is there any guideline for us?

Does MULTI type perform better than SINGLE???

I have a producer with multi-producer and five pipelined consumers, which process with WorkerPool.

like below:

        // disruptor = new Disruptor<>(eventFactory, BUFFER_SIZE, Executors.newCachedThreadPool(), ProducerType.SINGLE, new SleepingWaitStrategy());
        disruptor = new Disruptor<>(eventFactory, BUFFER_SIZE, DaemonThreadFactory.INSTANCE, ProducerType.MULTI, new SleepingWaitStrategy());

        FileDBEventHandler[] fileDBEventHandlers = new FileDBEventHandler[BATCH_SIZE];
        MetaCacheEventHandler[] metaCacheEventHandlers = new MetaCacheEventHandler[BATCH_SIZE];
        MessageQueueEventHandler[] messageQueueEventHandlers = new MessageQueueEventHandler[BATCH_SIZE];
        UploadLogHandler uploadLogHandlers[] = new UploadLogHandler[BATCH_SIZE];
        FileSplitEventHandler fileSplitEventHandlers[] = new FileSplitEventHandler[BATCH_SIZE];

        for (int i = 0; i < BATCH_SIZE; i++) {
            fileSplitEventHandlers[i] = new FileSplitEventHandler();

            fileDBEventHandlers[i] = new FileDBEventHandler(studentQuestionDao);

            metaCacheEventHandlers[i] = new MetaCacheEventHandler(uploadRecordDao, studentQuestionDao);

            messageQueueEventHandlers[i] = new MessageQueueEventHandler();

            uploadLogHandlers[i] = new UploadLogHandler();
        }

        LOGGER.info("添加线程handler开始");

        disruptor.setDefaultExceptionHandler(new UploadExceptionHandler(jobExecutionLogDao, emailAlarm));

        disruptor.handleEventsWithWorkerPool(fileSplitEventHandlers)
                .thenHandleEventsWithWorkerPool(fileDBEventHandlers)
                .thenHandleEventsWithWorkerPool(metaCacheEventHandlers)
                .thenHandleEventsWithWorkerPool(messageQueueEventHandlers)
                .thenHandleEventsWithWorkerPool(uploadLogHandlers);

which ProducerType should I use?

Any help could be appreciated!

**Comment by mikeb01** [comment]
You should use ProducerType.MULTI (the default) unless you know for certain that there is only a single producer thread accessing the disruptor, in which case ProducerType.SINGLE will provide a performance boost.
