### ISSUE TITLE
Suggestion for optimal disruptor use with Multiple producer sequenced pipeline

### ISSUE THREAD

**Issue by dhaval24** [LMAX-Exchange/disruptor#250]
@mikeb01 I have a sequenced pipelining scenario - 

Multiple producer (publishes) -> Ringbuffer -> C1 -> C2 -> C3 (publishes to) -> Output Ringbuffer-> C1(consumes and sends to wire)

I am looking for a recommended Disruptor configuration for optimal performance with minimal CPU impact.

Currently in my prototype each of this consumers are `EventHandlers` and are pipelined with Disruptor using `handleEventWith()` method. My understanding is that Disrputor creates 1 thread per consumer in this case. 

However, I also see that there is `handleEventsWithWorkerPool()` method which takes `WorkHandlers`. Is this meant to have a ThreadPool of worker threads for each of the consumer, and each event/job would be processed by a thread from ThreadPool for each consumer. Is my understanding correct here?

What is the recommendation to be used here in scenario like above?

Also what is the best suggestion for error handling for each consumer. 

Thanks in advance!

**Comment by dhaval24** [comment]
In the above prototype - I have 4 producer threads, creating objects 100000 objects each as fast as they can in a loop. 

The C1 and C2 consumers modify the object in the buffer, and C3 finally deserializes the object to json and puts it to output buffer. In the consumer of output buffer I am batching the items using https://mechanical-sympathy.blogspot.com/2011/10/smart-batching.html and then flushing them to disk. 

The end to end throughput I am getting in this case is around 40K items/second, which seems to be low as per the performance results of disruptor. Do you have any suggestions to improve it.

**Comment by ocoanet** [comment]
In a standard setup, I would advise you to try to reduce you ring buffers count, or to reduce you event handlers count: Do you really need that extra RingBuffer? Can you write your events to disk in C3? Can you merge C1 and C2?

However, because you are writing your events to disk, I wonder if I/O is not already the bottleneck of your prototype. Did you profile your application? What is the throughput if you comment or disable the processing in the output ring buffer?

If I/O is the bottleneck, then you have an I/O problem, not a Disruptor problem. If your I/O is disk based I suppose that you could reduce the frequency of flushing to disk, especially if by flushing you mean fsync. If your target application is going to be network based, I think that you should already use a network sender in your prototype because the performance characteristics and flushing mechanisms are quite different.

> I have 4 producer threads, creating objects 100000 objects each as fast as they can

I suppose that you mean *publishing* objects? You should be using the events from your ring buffer and not creating new ones to avoid putting pressure on the GC.

> C3 finally deserializes the object to json and puts it to output buffer

If you merge serializing and sending, maybe you can serialize into the send buffer and avoid the creation of temporary strings or byte buffers. This optimization could be interesting if the serialization part was really fast compared to the send part, but even then it would have to be measured very carefully.

Hope this helps.

**Comment by dhaval24** [comment]
> In a standard setup, I would advise you to try to reduce you ring buffers count, or to reduce you event handlers count: Do you really need that extra RingBuffer? Can you write your events to disk in C3? Can you merge C1 and C2?

Currently my buffer count is set to 32K. I can try and play around with values to see how this effects performance. As far as do I really need the output RingBuffer? May be not. I just had it to hold string type objects which, and attach ExceptionHandler to it so that if event fails to flush on I/O then it can be placed back in buffer for retry. May be there can be a better way for retrying.

> However, because you are writing your events to disk, I wonder if I/O is not already the bottleneck of your prototype. Did you profile your application? What is the throughput if you comment or disable the processing in the output ring buffer?

I haven't really yet profiled the application, but I added some timing logs, and I see that IO / batching is pretty fast. If I remove one of the intermediate handlers which is just creating random UUIDs in loop to simulate some heavy compute work, I get much more throughput. However, in my real scenario I would have some of these handlers doing heavy compute and mutate the object in Ringbuffer so I wanted to simulate it. 

> If I/O is the bottleneck, then you have an I/O problem, not a Disruptor problem. If your I/O is disk based I suppose that you could reduce the frequency of flushing to disk, especially if by flushing you mean fsync. If your target application is going to be network based, I think that you should already use a network sender in your prototype because the performance characteristics and flushing mechanisms are quite different.

By flushing I meant writing json to disk in batches. 

> 
> > I have 4 producer threads, creating objects 100000 objects each as fast as they can
> 
> I suppose that you mean _publishing_ objects? You should be using the events from your ring buffer and not creating new ones to avoid putting pressure on the GC.

Yes I meant publishing to ringbuffer. Well, in the current scenario, I tried to follow the wiki on the repo and had EventTranslator which just updates the ringbuffer object with the new object. 

> > C3 finally deserializes the object to json and puts it to output buffer
> 
> If you merge serializing and sending, maybe you can serialize into the send buffer and avoid the creation of temporary strings or byte buffers. This optimization could be interesting if the serialization part was really fast compared to the send part, but even then it would have to be measured very carefully.
> 
> Hope this helps.

**Comment by dhaval24** [comment]
@mikeb01 To answer some of your questions - 

I want to use Disruptor in Application Insights SDK (Real application). This SDK is responsible for collecting Telemetry user application such as metrics, traces and logs (via Log4j / Logback appenders).

The SDK has a processor pipeline where there can be multiple clients which produce Telemetry Events. each events goes through a series of processing, eventually getting serialized in Json String, batched, gziped and posted to endpoint. 

With the above scenario in mind I would like to have - 

1. Ability to have high throughput atleast around 50K events/second on an average. 
2. Consume as less CPU as possible - As a telemetry system is expected not to consume a lot of resources.
3. Power - honestly that is something I am not very concerned right now.

I have mentioned 50K events/second is because, the number of stages in the pipeline is something that is ultimately not in my control (as per how the project is designed). A user of the library can extend an interface and plug in his own stage in the pipeline. Therefore, my assumption here is that it is very hard to provide consistent performance gurantees of library of such sort. However, my attempt would be to provide some performance consistency under commonly used pipeline processing stages. 

By default there are definitely more than 5 stages in processing, so in my prototype I kind of wanted to mimic it. 

I read through different wait strategies and clearly BusySpin will definitely eat a lot more resources, as it keeps doing some work while the thread is waiting to avoid cold start etc. surely it would reduce latency, but then increase on CPU.

I think Yielding Wait strategy for 1st disruptor and Blocking on second might make the most sense, but I might be wrong. 

If it helps to just put the prototype on Github then I will do that to give some more context. May be my usage of disruptor is incorrect. 

Thanks for all the help till now.

**Comment by MendelMonteiro** [comment]
If latency is not a concern but CPU usage is I would recommend only using Blocking wait strategies and having as few event handlers as possible.

**Comment by mikeb01** [comment]
I would second what @MendelMonteiro has commented.  Having a pipeline of event handlers will consume more CPU as when a new event arrives (regardless of blocking strategy) the handlers further down the chain will busy wait until event has been processed by the other handlers.  While a short period of time it will be higher CPU.  Also having fewer event handlers reduces the number CPUs that your code will try to run on.

**Comment by dhaval24** [comment]
@mikeb01 and @mikeb01 thanks for your comments here. I will try to see how the performance improves by reducing handlers and using blocking strategy. 

I managed to put together the prototype on the Github https://github.com/dhaval24/Disruptor-Event-Flow if it helps to gain more insights.

**Comment by mikeb01** [comment]
I'm going to close this one now.  If you run into specific issues please raise them.  If you have more general discussion feel free to post to the mailing list.
