### ISSUE TITLE
Suggesting a being able to access the disruptor from the ring buffer

### ISSUE THREAD

**Issue by abubakarm94** [LMAX-Exchange/disruptor#252]
It'll be great to be able to access the disruptor from the ring buffer (through a getter method).

for example: ringbuffer.getDisruptor()

**Comment by mikeb01** [comment]
The RingBuffer is unaware of the Disruptor when constructed as the we have a unidirectional relationship from Disruptor to RingBuffer and not the other way around.  I don't think there is enough value to warrant adding circular dependency.
