### ISSUE TITLE
how can I make it faster?

### ISSUE THREAD

**Issue by backtradercn** [LMAX-Exchange/disruptor#254]
Hi
I have made an easy performance test about disruptorCpp [ https://github.com/backtradercn/Disruptor-cpp.git ] compare with this  java version
the cppversion  is 20% faster than java version.

where can I do to make the java version more quickly?

cpp:
use time:83668015
use time:98489800
use time:97859152
use time:101087060
use time:97742993
use time:100811823
use time:95195866

java:

use time:127348555
use time:119971322
use time:131763572
use time:122484001
use time:115917636

paste:
###################java version code:###############################
import com.lmax.disruptor.*;
import com.lmax.disruptor.dsl.Disruptor;
import com.lmax.disruptor.dsl.ProducerType;
import com.lmax.disruptor.util.DaemonThreadFactory;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

class TestEvent{
    Integer id;
    String msg;
}

class TestEventHandler implements EventHandler<TestEvent> {
    private static long _actuallyProcessed = 0;
    @Override
    public void onEvent(TestEvent event, long sequence, boolean endOfBatch)
            throws Exception {
        _actuallyProcessed++;
        System.out.println("_actuallyProcessed:" + _actuallyProcessed);
    }

    static void print()
    {
        System.out.println("_actuallyProcessed:" + _actuallyProcessed);
    }
}

class TestEventFactory implements EventFactory<TestEvent> {
    @Override
    public TestEvent newInstance() {
        return new TestEvent();
    }
}

public class TestDruptor {
    private Disruptor<TestEvent> disruptor;
    private TestEventHandler handler;
    private RingBuffer<TestEvent> ringbuffer;
    private ExecutorService executor;

    public TestDruptor(int bufferSize, TestEventHandler handler) {
        this.handler = handler;
        executor = Executors.newSingleThreadExecutor();
        disruptor = new Disruptor<TestEvent>(new TestEventFactory(), bufferSize, DaemonThreadFactory.INSTANCE,
                ProducerType.SINGLE, new BusySpinWaitStrategy());
    }

    @SuppressWarnings("unchecked")
    public void start() {
        disruptor.handleEventsWith(handler);
        disruptor.start();
        ringbuffer = disruptor.getRingBuffer();
    }

    public void publish(int data) throws Exception {
        long seq = ringbuffer.next();
        try {
            TestEvent evt = ringbuffer.get(seq);
            evt.id = (data);
        } finally {
            ringbuffer.publish(seq);
        }
    }

    public static void main(String[] args) throws Exception {
        TestDruptor d = new TestDruptor(1024, new TestEventHandler());
        d.start();
        for (int i = 0; i < 2000000; i++)
        {
            d.publish(i);
        }
        long average = 0;
        for(int loop =0; loop<100; loop++)
        {
            long start_nano = System.nanoTime();
            for (int i = 0; i < 2000000; i++)
            {
                d.publish(i);
            }
            long end_nano = System.nanoTime();
            average +=end_nano - start_nano;
        }

        System.out.println("use time:" +(average/100));
    }
}

######################Cpp version ###################

struct testEvent
{
    int64_t id{ 0 };
    std::string str;
};

class Worker : public Disruptor::IWorkHandler< testEvent >
{
public:
    explicit Worker() {}

    void onEvent(testEvent& event) override
    {
        //std::cout << " _actuallyProcessed:" << _actuallyProcessed;
        _actuallyProcessed++;
    }

    void print()
    {
        std::cout << "_actuallyProcessed:" << _actuallyProcessed << std::endl;
    }
private:
    int32_t _actuallyProcessed{ 0 };
};

class Producer
{
public:
    Producer(std::int32_t ringBufferSize, std::int32_t workerCount)
    {
        m_ringBufferSize = ringBufferSize;
        m_workerCount = workerCount;
        
        m_ptrTaskScheduler = std::make_shared<Disruptor::ThreadPerTaskScheduler>();
        
        m_ptrDisruptor = std::make_shared< Disruptor::disruptor<testEvent>>([]() { return testEvent(); } ,
            m_ringBufferSize,
            m_ptrTaskScheduler,
            Disruptor::ProducerType::Single,
            std::make_shared<Disruptor::SpinWaitWaitStrategy>()
            );
        
        for (size_t i = 0; i < m_workerCount; i++)
        {
            m_workers.push_back(std::make_shared< Worker >());
        }
        
        m_ptrDisruptor->handleEventsWithWorkerPool(m_workers);
    }

    ~Producer()
    {
        stop();
    }

    void start()
    {
        m_ptrTaskScheduler->start();
        m_ptrDisruptor->start();
    }

    void push(const testEvent &event)
    {
        auto ringBuffer = m_ptrDisruptor->ringBuffer();
        auto nextSequence = ringBuffer->next();
        (*ringBuffer)[nextSequence] = event;
        ringBuffer->publish(nextSequence);
    }

protected:
    void stop()
    {
        m_ptrDisruptor->shutdown();
        m_ptrTaskScheduler->stop();
    }

private:
    std::shared_ptr<Disruptor::ThreadPerTaskScheduler> m_ptrTaskScheduler;
    std::shared_ptr<Disruptor::disruptor<testEvent> > m_ptrDisruptor;
    std::vector<std::shared_ptr<Disruptor::IWorkHandler<testEvent> > > m_workers;
    std::int32_t m_ringBufferSize{ 1024 };
    std::int32_t m_workerCount{ 1 };
    std::int32_t m_schedulerCount{ 1 };
};

void testDisruptor()
{

    Producer producer(1024, 1);
    producer.start();
    testEvent e;
    
    int64_t average = 0;
    for (int loop = 0; loop < 100; loop++)
    {
        int64_t start_nano = std::chrono::duration_cast<std::chrono::nanoseconds>(
            std::chrono::steady_clock::now().time_since_epoch()
            ).count();
        for (size_t i = 0; i < 2000000; i++)
        {
            e.id = i;

            producer.push(e);
        }
        int64_t end_nano = std::chrono::duration_cast<std::chrono::nanoseconds>(
            std::chrono::steady_clock::now().time_since_epoch()
            ).count();

        average += (end_nano - start_nano);
    }
    std::cout << "use time:" << std::to_string(average / 100) << std::endl;

}

**Comment by epickrram** [comment]
In your Java `EventHandler`, you are writing a message to `stdout` on every event, whereas in the C++ version, this line is commented out.

**Comment by backtradercn** [comment]
that line  is commented out, or else it must be  more  slower.

**Comment by mikeb01** [comment]
Both the cpp version and Java version are not compiling.  Would it be possible to create a working github project so I can replicate your test.  What version of the JDK are you using?  Which compiler and version are you using and associated compile options?  Which implementation of the CPP Disruptor are you using?

**Comment by backtradercn** [comment]
for the cpp, pls look at : https://github.com/backtradercn/backtraderCpp.git
for the java, pls use https://github.com/LMAX-Exchange/disruptor.git itself's lib to create a demo java project.

**Comment by mikeb01** [comment]
The above links are not that useful.  I was hoping that you would be able to post working code for the benchmarks that you ran so that I can replicate the issue as you saw it.  The code from the original post isn't the actual benchmark you ran as it doesn't compile and included console messages that wouldn't of been in place when you actually ran the benchmark.  Unless you can provide full working code for the benchmarks and build scripts along with compiler and runtime versions used, I can't really help.

I could re-write a set of benchmarks, but there is a good chance I wouldn't be testing the same thing that you were.

**Comment by mikeb01** [comment]
Closing, due to lack of additional information.
