### ISSUE TITLE
Huge batches and gating sequences

### ISSUE THREAD

**Issue by ocoanet** [LMAX-Exchange/disruptor#255]
The `BatchEventProcessor` only advances the gating sequence at the end of the batch. This is a nice optimization because it avoids increasing the sequence value for every event. In addition, it allows the event handler to "own" the event instances until the end of the batch.

https://github.com/LMAX-Exchange/disruptor/blob/045c524cf9562ab65000203ac23d0991b448c97a/src/main/java/com/lmax/disruptor/BatchEventProcessor.java#L165-L172

However, when an event handler is quite slow, it can create very large batches. In this case, advancing the sequence barrier at the end of the batch can prevent the events from being available for the following handlers. It can also make a ring buffer appear full, although most of the events have already been processed.

I understand that this situation can clearly be considered precarious and that the best solution might be to improve the event handler throughput. But the fact that this problem can make very large ring buffers appear full is quite disturbing.

Would it be of any interest to introduce an optional maximum batch size to avoid large batches?

**Comment by mikeb01** [comment]
This is not an uncommon problems and there is a mechanism for dealing with it.  Have a look at the [early release example](https://github.com/LMAX-Exchange/disruptor/blob/master/src/test/java/com/lmax/disruptor/example/EarlyReleaseHandler.java).  It allows for releasing a sequence before a full batch is complete, but it is flexible in that it can be based on any criteria.  Fix max batch size, DB commit, disk flush, etc.

**Comment by ocoanet** [comment]
Thank you for adding the code example!

**Comment by ocoanet** [comment]
One last question: I suppose that increasing the gating sequence for every event on the last event handler should not impact performance thanks to the sequence caches in sequencers.

Can you confirm that?

**Comment by mikeb01** [comment]
For the publishers there will be negligible impact, in fact given that the buffer will advertise more space being available sooner, it is likely that the publisher side cache of the sequence will be invalidated less frequently.
