### ISSUE TITLE
How to add/remove handlers dynamically with disruptor 3

### ISSUE THREAD

**Issue by adamretter** [LMAX-Exchange/disruptor#256]
I have the pattern whereby a number of events are produced by multiple threads, I then need to transform these events, and then dispatch them to a number of consumers.

The consumers need to be dynamically added and removed from the system at runtime.

I was thinking of using 2 ring buffers. We would receive the events on the first ring-buffer, and have a single consumer which transforms them, and places the transformed events on the second rind-buffer. We would then have a number of consumers on the second ring-buffer that receive events.

I can't quite figure out how to dynamically add and remove consumers at run-time. I have tried this:

```java
    private final Disruptor<LockAction> outgoingDisruptor = new Disruptor<>(LockAction::new, RING_BUFFER_SIZE, DaemonThreadFactory.INSTANCE);
    private final RingBuffer<LockAction> outgoingRingBuffer;
    private final SequenceGroup outgoingSequenceGroup = new SequenceGroup();
    private final Map<LockEventListener, BatchEventProcessor<LockAction>> outgoingListenersWithProcessors = new NonBlockingHashMap<>();


   this.outgoingRingBuffer = outgoingDisruptor.start();


    public void registerListener(final LockEventListener lockEventListener) {
        final SequenceBarrier barrier = outgoingRingBuffer.newBarrier();
        final EventHandler<LockAction> handler = (event, sequence, endOfBatch) -> lockEventListener.accept(event);
        final BatchEventProcessor<LockAction> processor = new BatchEventProcessor<>(outgoingRingBuffer, barrier, handler);
        processor.getSequence().set(barrier.getCursor());
        outgoingSequenceGroup.add(processor.getSequence());
        processor.getSequence().set(outgoingRingBuffer.getCursor());
        outgoingListenersWithProcessors.put(lockEventListener, processor);
        processor.run();

        // notify the listener that it was registered
        lockEventListener.registered();
    }

    public void deregisterListener(final LockEventListener lockEventListener) {
        final BatchEventProcessor<LockAction> processor = outgoingListenersWithProcessors.remove(lockEventListener);
        processor.halt();
        outgoingSequenceGroup.remove(processor.getSequence());

        // notify the listener that it was deregistered
        lockEventListener.unregistered();
    }
```

However, when I call `registerListener` at runtime it always blocks on `processor.run` and never proceeds from there.

What am I doing wrong here?

**Comment by mikeb01** [comment]
The `processor.run()` method contains an infinite loop and is designed to be called from within a new thread.  You will need to create a new thread and use the processor as the `Runnable` for that thread.

There is probably an outstanding feature to add dynamic add/remove to the Disruptor DSL.  I'll have a bit of a dig into that next week.  The one feature with this code is that the batch event processor that you've added dynamically won't be visible to the Disruptor instance so methods like `Disruptor.halt()` may not do the right thing.

**Comment by adamretter** [comment]
@mikeb01 Okay thanks for the feedback, I will give the threading thing a try...
I look forward to having this easily manageable from the DisruptorDSL :-)

**Comment by Rookiexu** [comment]
Maybe you can refer to my project https://github.com/Rookiexu/disruptorDynamicConsumer

**Comment by superyuuki** [comment]
Any progress on this?

**Comment by Palmr** [comment]
> Any progress on this?

None in the Disruptor project itself.

There is @Rookiexu 's project linked above which does it, and we'd welcome a pull request too. Otherwise this feature may continue to stay on the backlog for a while yet.

**Comment by grumpyjames** [comment]
As per the previous comment - we've not needed this functionality, and so it hasn't been implemented. We would consider pull requests that worked towards it, but we suspect that for this particular issue, that is not imminently happening. Thus, this issue shall be closed.
