### ISSUE TITLE
Is there a way to judge whether all the events have been consumed?

### ISSUE THREAD

**Issue by caixinning** [LMAX-Exchange/disruptor#257]
Is there a way to judge whether all the events have been consumed?  Similar to the BlockingQueue.isEmpty() method. I want to add some business logic when consumers are idle.
Looking forward to your reply.

**Comment by MendelMonteiro** [comment]
Do you want to know from a producing or consuming thread?  What kind of logic do you want to add?

**Comment by caixinning** [comment]
> Do you want to know from a producing or consuming thread? What kind of logic do you want to add?

1. Producing thread.
2. e.g. Make a dump in a stable state.

**Comment by MendelMonteiro** [comment]
If you want to know from a producing thread you can use the `remainingCapacity()` and `getBufferSize()` methods on the `RingBuffer` to see if any entries are still pending in the ring buffer.  Note that it is just an indication of the remaining capacity due to data races.

**Comment by caixinning** [comment]
> If you want to know from a producing thread you can use the `remainingCapacity()` and `getBufferSize()` methods on the `RingBuffer` to see if any entries are still pending in the ring buffer. Note that it is just an indication of the remaining capacity due to data races.

Thanks very much, I saw these methods.  Literally understood, RingBuffer<Event> reuse events, so I am not sure the above method returns capacity of idle events or  NULL(never handled events)?

**Comment by MendelMonteiro** [comment]
All the events are created when the `RingBuffer` is instantiated so I'm not sure what you refer to when you say "NULL(never handled events)"?

**Comment by mikeb01** [comment]
From the publisher thread, check the [example](https://github.com/LMAX-Exchange/disruptor/blob/master/src/test/java/com/lmax/disruptor/example/WaitForProcessing.java).  You can use the Disruptor to find the sequence for a specific consumer or use the remaining capacity from the RingBuffer.  Both will work, but which to use will depend on your use case.
