### ISSUE TITLE
when producer's cursor overflow, BlockingWaitStrategy#waitFor is there a dead cycle?

### ISSUE THREAD

**Issue by ph3636** [LMAX-Exchange/disruptor#260]
when producer's cursor overflow, BlockingWaitStrategy#waitFor is there a dead cycle?

When there is a situation：
producer's cursor is cursorSequence.get() will equal (Long.MAX_VALUE + 1 = -9223372036854775808),
but consumer's sequence expect  (Long.MAX_VALUE - 1 = 9223372036854775806) 

The following conditions will never be met
=========================================================
if (cursorSequence.get() < sequence)
        {
            synchronized (mutex)
            {
                while (cursorSequence.get() < sequence)
                {
                    barrier.checkAlert();
                    mutex.wait();
                }
            }
        }

        while ((availableSequence = dependentSequence.get()) < sequence)
        {
            barrier.checkAlert();
            ThreadHints.onSpinWait();
        }
===========================================================

**Comment by mikeb01** [comment]
At 1B events per second, this will take roughly 270 years to occur. So we don't worry about it.
