### ISSUE TITLE
Seems TimeoutBlockingWaitStrategy not working

### ISSUE THREAD

**Issue by lubinson** [LMAX-Exchange/disruptor#261]
Maybe I misunderstand the TimeoutBlockingWaitStrategy meaning. I thought TimeoutBlockingWaitStrategy will release the producer thread when the ringbuffer is full after waiting for a time period, e.g. 3 sec.  But now the behavior looks producer is waiting still. 

When I debug the code, I found the process is waiting on below code `MultiProducerSequencer` which you already have an comments on `TODO`:
```
        do
        {
            current = cursor.get();
            next = current + n;

            long wrapPoint = next - bufferSize;
            long cachedGatingSequence = gatingSequenceCache.get();

            if (wrapPoint > cachedGatingSequence || cachedGatingSequence > current)
            {
                long gatingSequence = Util.getMinimumSequence(gatingSequences, current);

                if (wrapPoint > gatingSequence)
                {
                    LockSupport.parkNanos(1); // TODO, should we spin based on the wait strategy?
                    continue;
                }

                gatingSequenceCache.set(gatingSequence);
            }
            else if (cursor.compareAndSet(current, next))
            {
                break;
            }
        }
        while (true);
```
So I am thinking is this code don't consider any waiting strategy we choose?

My intention is to not block producer threads even we can drop some messages if the ringbuffer is full. But we hope to let waiting strategy to do so, not to check ringbuffer size by ourselves and also need to maintain some timeout, etc.
 
I am using JDK 11 docker image. 

Thanks.

**Comment by mikeb01** [comment]
The `TimeoutBlockingWaitStrategy` is designed for cases where the `EventHandler` needs a periodic callback when the buffer is empty.  To deal with the case where you want to avoid blocking when the publisher is full then look at the `tryNext`/`tryPublishEvent` methods.

**Comment by lubinson** [comment]
@mikeb01 
Thanks for the correction. Actually the producer side also needs similar wait strategy in order to not block front end threads.  Do you have a sample to use `tryNext/tryPublishEvent` in a timeout manner? 

Thanks.

**Comment by grumpyjames** [comment]
We don't appear to have such a sample, regrettably, but we trust that in the intervening three years a method to do this without need for a sample may have been discovered.
