### ISSUE TITLE
How to control the speed of producers？

### ISSUE THREAD

**Issue by qq297910962** [LMAX-Exchange/disruptor#264]
How to get the number of outstanding tasks? If consumers consume too slowly, I want to control the production speed of producers.Does the disruptor have this function? Or how can I achieve it myself?

**Comment by MendelMonteiro** [comment]
The producers will know when the ring buffer is full as they will either block when calling `next()` or 
 when calling `tryNext()` an `InsufficientCapacityException` will be thrown.  The producers can then back-off/retry, drop or implement any other strategy for dealing with producer/consumer imbalance.  This concept is called back-pressure.

**Comment by mikeb01** [comment]
You can also used `RingBuffer.hasAvailableCapacity` to estimate whether the ring buffer would block given a specified number of messages.
