### ISSUE TITLE
some puzzle about Sequence.set(final long value)

### ISSUE THREAD

**Issue by uvletter** [LMAX-Exchange/disruptor#265]
I'm studying  disruptor recently and  I found some code  puzzled me:

 ##### SingleProducerSequencer.java
```java
   /**
     * @see Sequencer#publish(long)
     */
    @Override
    public void publish(long sequence)
    {
        cursor.set(sequence);
        waitStrategy.signalAllWhenBlocking();
    }
```
`Sequence.set(final long value)` uses `UNSAFE.putOrderedLong(this, VALUE_OFFSET, value)` underlying, which's semantics is put a Store/Store barrier between this write and any previous
 store, but have no guarantees about the visibility from other thread. However the event processor  alway runs in another thread, the waitFor method uses sequencer's  cursor to ensure there're some events to consume. So how to explain it, is `cursor.setVolatile` more reasonable here?

Forgive my pool English. Hoping you got it :-)

**Comment by mikeb01** [comment]
A store/store barrier is sufficient in this case as all we need to guarantee is that the message data is stored to "memory"* before the update to the sequence value.  A setVolatile is only required if we are reading and writing concurrent data on the same thread, in our case we are only writing.

On the reading thread we only need a load/load barrier to ensure that the message data is read from "memory" after the sequence is read.  So in the situation where the reading thread sees the sequence value increment the message data will be visible as the data ordering is transitive.  I.e. if storing the message data happens before updating the sequence and updating the sequence happens before the new sequence is read and reading the message data happens after the sequence is read, we can infer that writing the message data happens before the message data is read.

* "memory" in this instance is the abstract notion of memory, not physical ram.
