### ISSUE TITLE
Heavy CPU load when the queue is full, and more producer threads than cores

### ISSUE THREAD

**Issue by carterkozak** [LMAX-Exchange/disruptor#266]
We use disruptor in the log4j2 project, resulting in behavior here: https://issues.apache.org/jira/browse/LOG4J2-2606

Steps to reproduce:
1. The disruptor queue is completely filled
2. Many producer threads creating events as quickly as they can
3. The disruptor consumer thread processes relatively slowly (writing to disk, more slowly than events are created)

In this case, we see 100% CPU utilization regardless of the disruptor WaitStrategy. I'm curious if this is expected behavior.

We attempt a `tryEnqueue` before invoking a blocking enqueue if configured to do so. We could synchronize around the blocking enqueue to reduce load in this case when the queue is completely full without sacrificing performance when there is space.

I'd appreciate any advice you could provide, thanks!

**Comment by carterkozak** [comment]
Benchmarks to reproduce this issue here: https://github.com/apache/logging-log4j2/pull/269#issue-280445317

**Comment by remkop** [comment]
@carterkozak On the log4j2 mailing list you [mentioned](https://lists.apache.org/thread.html/3ff848a3199dd5bb9959caf1dc6a257315979ffd4b3c0a69c1b781f8@%3Cdev.logging.apache.org%3E) that you encountered this in a production setup, not just in a benchmark. Can you provide more details about the setup where the issue happened?

* number of cores on the machine
* number of active application threads
* version information: Disruptor version, Log4j 2 version, Java version, OS version

Also, the default WaitStrategy used by Log4j is `TimeoutBlockingWaitStrategy`. Was this the WaitStrategy that was used when you encountered the issue? Have you tried other WaitStrategies in production or in the benchmarks?

**Comment by carterkozak** [comment]
Yes, we used the default `TimeoutBlockingWaitStrategy`. In my benchmarks I have tried using all the other wait strategies we provide without significant difference in performance or CPU usage.

I've encountered this a few times on different services, normally when there is a sharp uptick in logging rate, or around midnight when all logs roll and there is a heavy sustained logging rate.

Cores: 8
Application threads: ~200
OS: CentOS 6
Disruptor 3.4.2
log4j2 2.11.2
java: 8u202

**Comment by remkop** [comment]
When the logs roll over, is Log4j configured to compress them, or is that done by a separate process?
(I can't remember if logging is blocked during a rollover...)

**Comment by carterkozak** [comment]
Log4j is confgured to compress them, however that executes on another thread pool to avoid blocking logging. The only blocking action is to move (or failing that, copy) the file to a temporary non-compressed rolled location, and create a new file to begin logging to. Compressing the rolled file contributes to CPU load in the interim, but doesn't block the background thread.

**Comment by mikeb01** [comment]
I think on some of the newer Linux kernels the `LockSupport.parkNano(1)` that we using inside the blocking `next()` call degrade to a no-op and result in a busy wait.  One simple thing to try would be to write your own simple loop using the try method.

```
while (!ringBuffer.tryPublish(...))
{
    LockSupport.parkNanos(1000);
}
```

I'll push a code change that does this by default internally.  BTW my personal recommendation is to always used one of the `try...` methods and define your own action when publishing fails.  Eventually I want to remove the blocking method call from the Disruptor.

If that fails then your approach of taking out a lock after the first publish failure should work too.

As an aside, we use the Disruptor ourselves for logging, but we never block the application thread.  We also used the `try...` methods and on failure we CAS a flag to indicate the publishing failure.  If the flag was not already set previously we write an error to stderr to indicate the ring buffer was full (clearing the flag on a successful publish).  We then drop the log message.  Incrementing a counter on failure is also useful here as well.

**Comment by carterkozak** [comment]
Thank you for the information @mikeb01.

In local testing (admittedly on OSX, not linux) I see significant performance improvement using `LockSupport.parkNanos(1_000_000L)` over `1000L` and even `100_000L`, however at that point I think a mutex would be better. Given our use case, I/O, the background thread should always be slower than enqueue operations, so synchronizing around the enqueue (or potentially a retry loop in the future) doesn't seem too terrible when we need to block application threads (note: this would only apply when the queue is full, and has rejected the `try`, there would be no synchronization involved in the fast path). I'm curious of your thoughts @remkop.

> As an aside, we use the Disruptor ourselves for logging, but we never block the application thread. We also used the try... methods and on failure we CAS a flag to indicate the publishing failure. If the flag was not already set previously we write an error to stderr to indicate the ring buffer was full (clearing the flag on a successful publish). We then drop the log message. Incrementing a counter on failure is also useful here as well.

Our default configuration does not allow events to be discarded, as you might imagine that would be problematic for audit uses. We support configurable behavior when the ringbuffer is full, including a `Discard` path which sounds identical to what you have described:
https://github.com/apache/logging-log4j2/blob/e741549928b2acbcb2d11ad285aa84ee88728e49/log4j-core/src/main/java/org/apache/logging/log4j/core/async/DiscardingAsyncQueueFullPolicy.java#L51
