### ISSUE TITLE
I hava some problems in using disruptor 

### ISSUE THREAD

**Issue by leebingqi** [LMAX-Exchange/disruptor#267]
Hi,
I hava some problems in using disruptor .
The structure of my project is that when an order request is generated, it is first sent to RabbitMQ, and then to disruptor after RabbitMQ consumers get the data. But when I tested with jemeter, I sent 100 order requests, RabbitMQ consumers received 100 requests, but disruptor only handled 95% of the requests. I don't know why? I have tested it many times and lost data every time.

**Comment by SamBarker** [comment]
That implies to me that the event handlers you have attached to the ring buffer are not keeping up with the requests. 

You don't mention what publication method you are using. The blocking option will wait for space in the ring buffer, the non blocking `tryPublish` will return a boolean indicating if they were able to publish the event.

**Comment by leebingqi** [comment]
I am using Disruptor in SpringBoot:

```

```
> @Service
> public class QueueHelper implements DisposableBean, InitializingBean {
> 
>     private int handlerCount = 4;
>     private int bufferSize = 1024 * 1;
> 
>     private Disruptor<QueueEvent> disruptor;
>     private QueueEventProcucer queueEventProcucer;
> 
> 
>     @Override
>     public void destroy() throws Exception {
> 
>         shutdown();
>     }
> 
>     @Override
>     public void afterPropertiesSet() throws Exception {
> 
>         start();
>     }
>     public QueueHelper() {
> 
>     }
> 
>     public QueueHelper(int handlerCount, int bufferSize) {
>         this.handlerCount = handlerCount;
>         this.bufferSize = bufferSize;
>     }
> 
>     private void start()
>     {
>         //Executor executor = Executors.newCachedThreadPool();
> 
>         QueueEventFactory factory = new QueueEventFactory();
> 
>         //
>         disruptor = new Disruptor<QueueEvent>(
>                 factory, bufferSize, DaemonThreadFactory.INSTANCE, ProducerType.SINGLE, new BlockingWaitStrategy());
> 
>         WorkHandler<QueueEvent>[] workHandlers = new WorkHandler[handlerCount];
>         for (int i = 0; i < handlerCount; i++) {
>             workHandlers[i] = new QueueEventHandler();
>         }
> 
>         disruptor
>                 .handleEventsWithWorkerPool(workHandlers)
>                 .then(new ClearingEventHandler());
> 
>         //clearingEventHandlers.toArray(new [clearingEventHandlers.size()]);
> 
>         disruptor.setDefaultExceptionHandler(new QueueEventExceptionHandler());
> 
> 
>         RingBuffer<QueueEvent> ringBuffer = disruptor.start();
> 
> 
>         queueEventProcucer = new QueueEventProcucer(ringBuffer);
> 
>     }
>     public void shutdown()
>     {
>         doHalt();
>     }
>     private void doHalt()
>     {
>         disruptor.shutdown();
>     }
> 
>     public void SendMessageToHandler(List<BusQueMQmessage> quedata)
>     {
>         queueEventProcucer.SendMessage(quedata);
>     }
> 
>     public int getHandlerCount() {
>         return handlerCount;
>     }
> 
>     public void setHandlerCount(int handlerCount) {
>         this.handlerCount = handlerCount;
>     }
> 
>     public int getBufferSize() {
>         return bufferSize;
>     }
> 
>     public void setBufferSize(int bufferSize) {
>         this.bufferSize = bufferSize;
>     }
> }
```

```
And,This is **QueueEventProcucer**

> public class QueueEventProcucer {
> 
>     private final RingBuffer<QueueEvent> ringBuffer;
> 
>     public QueueEventProcucer(RingBuffer<QueueEvent> ringBuffer) {
>         this.ringBuffer = ringBuffer;
>     }
> 
>     private static final EventTranslatorOneArg<QueueEvent,List<BusQueMQmessage>>
> 
>             TRANSLATOR_ONE_ARG =
> 
>             new EventTranslatorOneArg<QueueEvent, List<BusQueMQmessage>>() {
> 
> 
>         @Override
>         public void translateTo(QueueEvent queueEvent, long l, List<BusQueMQmessage> quedata) {
>             queueEvent.setQuedata(quedata);
>         }
>     };
> 
>     public void SendMessage(List<BusQueMQmessage> quedata)
>     {
>         ringBuffer.publishEvent(TRANSLATOR_ONE_ARG,quedata);
>     }
> }
> 
This is **QueueEventHandler** :

```
> public class QueueEventHandler  implements WorkHandler<QueueEvent>,EventHandler<QueueEvent> {
> 
>     private org.slf4j.Logger logger = LoggerFactory.getLogger(this.getClass());
> 
>     public QueueEventHandler() {
>     }
> 
>     @Override
>     public void onEvent(QueueEvent queueEvent, long l, boolean b) throws Exception {
>         this.onEvent(queueEvent);
>     }
>     @Override
>     public void onEvent(QueueEvent queueEvent) throws Exception {
> 
>         System.out.println("consumer");
>         System.out.println(queueEvent.getQuedata().toString());
>     }
> }
```

**Comment by SamBarker** [comment]
I don't know much about spring boot, however a quick google suggests that the service can be called from multiple threads at once, so I would be changing to use a `ProducerType.MULTI` at the very lest. 

`QueueEventProcessor` uses the blocking publish call so will wait for space in the buffer. I'd make sure via logging that all events have completed their publish before saying they are missing.

**Comment by leebingqi** [comment]
I changed the type to  `ProducerType.MULTI` ， now it's working properly. Thank you very much ^_^!
