### ISSUE TITLE
How to expose RingBuffer remaining capacity as a JMX bean?

### ISSUE THREAD

**Issue by gaurav9822** [LMAX-Exchange/disruptor#269]
1.Is it possible to monitor the remaining capacity of the ringbuffer using tools like JMX?
2.If not, then can this property be exposed, so that the application can monitor the ringbuffer capacity at the run-time?

**Comment by mikeb01** [comment]
There isn't JMX bean supplied with the Disruptor, but the information is available via `RingBuffer::remainingCapacity`.
