### ISSUE TITLE
Seems SingleProducer is not threadsafe

### ISSUE THREAD

**Issue by sucesserli** [LMAX-Exchange/disruptor#271]
version:3.4.2
In our project  we try to integrate rocketmq with disruptor.
To get high throughput , we use singleton producer with singleproducer disruptor. 
I got unrespected result:

- In mq consumer we get correct message.

2019-07-31 00:24:29.148 [ConsumeMessageThread_18] ERROR - consume message :orderid:871837820type:2 price: 0.0007552600 id:900059 time:1564503869148
2019-07-31 00:24:29.148 [ConsumeMessageThread_1] ERROR  - consume message :orderid:871837727type:2 price: 0.1289000000 id:900057 time:1564503869148

As you can see the id value of orderid:871837727 is 900057.

2. But in the event handler  we get wrong message.
the message we write into mongo with jounalhandler  is :

"_id": "ObjectId("5d406f3d7306df6f351b7352")"
"createdate": "NumberLong(1564503869134)"
"orderid": "871837727"
"id": 900059
"ftype": 2
"prize": "0.0007552600"
"size": "372.0000000000"

You can see the id changed to 900059 so does the price field.

- OrderEventProducer :
``` java
public class OrderEventProducer {
    private final RingBuffer<MQEntrust> ringBuffer;

    public EntrustEventProducer(RingBuffer<OrderEvent> ringBuffer)
    {
        this.ringBuffer = ringBuffer;
    }
    public void onData(OrderEvent bb)
    {
        long sequence = ringBuffer.next();  // Grab the next sequence
        try
        {
            OrderEvent event = ringBuffer.get(sequence); // Get the entry in the Disruptor
            // for the sequence
            event.setCreatedate(bb.getCreatedate());
            event.setOrderid(bb.getFentrustid());
            event.setFsource(bb.getFsource());
            event.setFstatus(bb.fstatus);
            event.setId(bb.ftradeid);
            ... ... 

        }
        finally
        {
            ringBuffer.publish(sequence);
        }
    }
```
-  disruptor 
``` java 
public class OrderDisruptor {
    private static volatile OrderDisruptor instance;
    private static Disruptor<OrderEvent> disruptor;
    private static OrderEventProducer producer;
    private int buffersize = 32768;


    private OrderDisruptor() {
        init();
    }
    private void init() {

        disruptor = new Disruptor<OrderEvent>(OrderEvent::new,buffersize, Executors.defaultThreadFactory(),ProducerType.SINGLE,new YieldingWaitStrategy());
        disruptor.handleEventsWith(new OrderJournalHandler()).then(new OrderEventHandler());
        disruptor.start();
        producer = new EntrustEventProducer(disruptor.getRingBuffer());
    }
    public EntrustEventProducer getProducer() {

        if (producer ==  null )
        {
            synchronized (OrderEventProducer.class) {
                if (producer == null) {
                    producer = new OrderEventProducer(disruptor.getRingBuffer());
                }
            }
        }
        return producer;
    }
    public static OrderDisruptor getInstance() {
        if (instance == null ) {
            synchronized (OrderDisruptor.class) {
                if (instance == null ) {
                    instance = new EntrustDisruptor();
                }
            }
        }
        return instance;
    }
``` 
The singleproducer ringbuffer is not thread safe? When I need to use disrupter with MQ I can only use the multiproducer or I push all messages to my ConcurrentLinkedQueue then poll them into disruptor in a single new thread.

**Comment by SamBarker** [comment]
As you've worked out the `SingleProducer` is not designed to be shared between threads. The single in the name really refers to the thread count. The performance drop between `single` and `multi` producers should be a lot smaller than the costs of adding a new data structure between the MQ threads and the disruptor.

**Comment by sucesserli** [comment]
@SamBarker  Thanks a lot. I will use multi producers in this scenario.
··· java 
disruptor = new Disruptor<OrderEvent>(OrderEvent::new,buffersize, Executors.defaultThreadFactory(),ProducerType.MULTI,new YieldingWaitStrategy());
···
