### ISSUE TITLE
disruptor动态添加消费者

### ISSUE THREAD

**Issue by sglu** [LMAX-Exchange/disruptor#272]
如题，我想动态的添加消费者的数量

**Comment by mikeb01** [comment]
[Example of dynamically adding a handler](https://github.com/LMAX-Exchange/disruptor/blob/master/src/test/java/com/lmax/disruptor/example/DynamiclyAddHandler.java)

**Comment by Rookiexu** [comment]
You can refer to my project https://github.com/Rookiexu/disruptorDynamicConsumer
