### ISSUE TITLE
break off eventhandler

### ISSUE THREAD

**Issue by levou** [LMAX-Exchange/disruptor#275]
example handers  a->b->c-d; how to break off handler chain when execute b.(means when  b ,then break off)

**Comment by mikeb01** [comment]
I'm sorry I don't understand what you mean by "break off".

**Comment by levou** [comment]
> I'm sorry I don't understand what you mean by "break off".

means discontinue

**Comment by mikeb01** [comment]
I sorry, I'm still unclear about what you are trying to achieve.

**Comment by ocoanet** [comment]
@levou If you want to stop processing the event, you can just flag your events and ignore flagged events in the following handlers.

**Comment by levou** [comment]
@ocoanet Thank you. I know what you mean. I also think about it. I just don't want the handler to be called after the link is interrupted. Every handler is a thread resource, and even empty calls are a waste.

**Comment by ocoanet** [comment]
Well, because the underlying data-structure is a preallocated ring-buffer, you cannot really remove the event. And your event handler thread is probably already woken up by the wait strategy and waiting to process the event. I do not think that there is a better option.

**Comment by ennerf** [comment]
I haven't used it in a while, but if I remember right you could use an `EventPoller`. That way you control the thread yourself and you can terminate it whenever you want. Just remember to remove the gating sequence so you don't block everything.

The [PullWithBatchedPoller.java](https://github.com/LMAX-Exchange/disruptor/blob/master/src/test/java/com/lmax/disruptor/example/PullWithBatchedPoller.java#L30-L59) looks like a good starting point.

**Comment by levou** [comment]
@ocoanet @ennerf thanks.

**Comment by mikeb01** [comment]
Closing as there does seem to be any further issue.
