### ISSUE TITLE
SingleProducerSequencer

### ISSUE THREAD

**Issue by 573742376** [LMAX-Exchange/disruptor#280]
@Override
    public long next(int n)
    {
        if (n < 1 || n > bufferSize)
        {
            throw new IllegalArgumentException("n must be > 0 and < bufferSize");
        }

        long nextValue = this.nextValue;

        long nextSequence = nextValue + n;
        long wrapPoint = nextSequence - bufferSize;
        long cachedGatingSequence = this.cachedValue;

        if (wrapPoint > cachedGatingSequence || cachedGatingSequence > nextValue)
        {
            cursor.setVolatile(nextValue);  // StoreLoad fence

            long minSequence;
            while (wrapPoint > (minSequence = Util.getMinimumSequence(gatingSequences, nextValue)))
            {
                LockSupport.parkNanos(1L); // TODO: Use waitStrategy to spin?
            }

            this.cachedValue = minSequence;
        }

        this.nextValue = nextSequence;

        return nextSequence;
    }
=======================================================
cachedGatingSequence > nextValue   :What does that mean? Is that redundant  
Thank you for your help

**Comment by mikeb01** [comment]
We have a method on the RingBuffer called `resetTo` which can be used to force the ring buffer to a specific value.  It is a method that shouldn't be used, but that check is in place to make sure that it doesn't break publishing.

**Comment by 573742376** [comment]
> We have a method on the RingBuffer called resetTo which can be used to force the ring buffer to a specific value.  It is a method that shouldn't be used, but that check is in place to make sure that it doesn't break publishing.

Thank you
