### ISSUE TITLE
BatchEventProcessor should set avaiable sequence as soon as possible

### ISSUE THREAD

**Issue by leonirvanel** [LMAX-Exchange/disruptor#281]
We may fix it as below.

![image](https://user-images.githubusercontent.com/1066849/67202214-abda4600-f43a-11e9-8fae-a4edcc094d51.png)

**Comment by ocoanet** [comment]
The current behaviour is expected. You can work around it if you need to, see [this issue](https://github.com/LMAX-Exchange/disruptor/issues/255).

**Comment by mikeb01** [comment]
This can hurt performance as the available sequence is a shared variable and is constrained to being an ordered write.  As @ocoanet mentions, you can take control of this yourself.
