### ISSUE TITLE
LiteBlockingWaitStrategy can be improvements

### ISSUE THREAD

**Issue by zhuyou1234** [LMAX-Exchange/disruptor#282]
![1571746951(1)](https://user-images.githubusercontent.com/15230000/67285460-2faf3380-f50a-11e9-93e5-7c49da07c9e7.png)

 can postion 1 move to postion  2 should be more available

**Comment by zhuyou1234** [comment]
can postion 1 move to postion 2 should be more available

**Comment by mikeb01** [comment]
Perhaps, but the signalNeeded.getAndSet() provides an important memory fence, so I would want to see more evidence that it doesn't cause a concurrency bug.
