### ISSUE TITLE
How to recovery data when the power breaked or OS shutdown

### ISSUE THREAD

**Issue by wuguangkuo** [LMAX-Exchange/disruptor#283]
I had read the article written by Martin Fowler. The disruptor architecture image like this:
![arch-full](https://user-images.githubusercontent.com/12744778/67946611-ab049980-fc1c-11e9-909d-016f5e59253b.png)

My question is that when the journaler should lag behind the producer, when the power breaked or OS shutdown happen, how to recover the data between the journaler and the producer?

**Comment by mikeb01** [comment]
The short answer is that you don't.  Any messages that are not stored in the journal are to be considered as not being received.  They are the same as any messages that may be inflight over the networks as the OS or system crashes.  The important invariant that needs to be observed is that any message that is applied to the business logic, such the state is changed or a response (or any outbound message) is sent MUST be stored in the journal.  Therefore as long as the message is stored before the business logic is applied we don't need to concern ourselves with those messages that are not stored in the journal.  This does mean in the case of failure that systems sending messages may need to deal with timing out requests for which responses are never received.
