### ISSUE TITLE
The difference between Disruptor constructor and RingBuffer.createSingleProducer()method？

### ISSUE THREAD

**Issue by chenghongzhi** [LMAX-Exchange/disruptor#288]
I'm a noob of Disruptor,I find the following code in the  Disruptor getting started.

```
ExecutorService executorService = new ThreadPoolExecutor(0, Integer.MAX_VALUE,
                60L, TimeUnit.SECONDS,
                new SynchronousQueue<Runnable>());
        int bufferSize = 1024;
        LongEventFactory factory = new LongEventFactory();
        Disruptor<LongEvent> disruptor = new Disruptor<LongEvent>(factory, bufferSize, executorService);
        // Connect the handler
        RingBuffer<LongEvent> ringBuffer = disruptor.getRingBuffer();
```
But,I find others use this method RingBuffer.createSingleProducer() to create RingBuffer.I don't know which is the best way and the difference between A(Disruptor constructor) and B(RingBuffer.createSingleProducer()).

Thank you!

**Comment by mikeb01** [comment]
The Disruptor is like a DSL for constructing instances of the RingBuffer.  It simplifies setting up the relationships between the ring buffer and event handlers.  I would recommend using the Disruptor class unless the setup you want can't be implemented.
