### ISSUE TITLE
Why doesn't  the class MultiProducerSequencer use padded long variables to solve false sharing issue?

### ISSUE THREAD

**Issue by hilaryfrank** [LMAX-Exchange/disruptor#290]
As we know, the class SingleProducerSequencer uses 14 padded long variables to solve false sharing issue. Then why doesn't the class MultiProducerSequencer use the same way to solve false sharing issue as class SingleProducerSequencer does?
Is it because there is no false sharing issue while using class MultiProducerSequencer? or some other reason?

**Comment by mikeb01** [comment]
Technically it does and it doesn't.  The shared value that it uses for the CAS is a Sequence object which already has the padding around it.  The other shared value that is has is the availableBuffer, which is an int[] array the size of the ring buffer.  To pad each of those individual entries would mean making that array 16 to 32 time larger than it already is.  I tested this and there was no discernible performance benefit, so I went with the solution that used the least resources.

**Comment by hilaryfrank** [comment]
Thanks for your answer.
