### ISSUE TITLE
Should setVolatile be necessary?

### ISSUE THREAD

**Issue by zhuchao941** [LMAX-Exchange/disruptor#291]
In version 3.3.6, I found this code in class `SingleProducerSequencer`

```java
        if (wrapPoint > cachedGatingSequence || cachedGatingSequence > nextValue)
        {
            cursor.setVolatile(nextValue);  // StoreLoad fence

            long minSequence;
            while (wrapPoint > (minSequence = Util.getMinimumSequence(gatingSequences, nextValue)))
            {
                waitStrategy.signalAllWhenBlocking();
                LockSupport.parkNanos(1L); // TODO: Use waitStrategy to spin?
            }

            this.cachedValue = minSequence;
        }
```

should setVolatile be necessary? Does it mean that memory visibility cause the behind of the consumers?

**Comment by zhuchao941** [comment]
@mikeb01 i saw u committed the code, can u help me?

**Comment by mikeb01** [comment]
This is there because of a feature that we added in the very early days to allow the dynamic addition of gating sequences to the RingBuffer.  This requires a StoreLoad barrier when updating the sequence.  So strictly for message passing it is not required.

**Comment by zhuchao941** [comment]
> This is there because of a feature that we added in the very early days to allow the dynamic addition of gating sequences to the RingBuffer. This requires a StoreLoad barrier when updating the sequence. So strictly for message passing it is not required.

Could u show me which feature and more detail? I am learning cpu/barrier, and want to figure out why here needs Volatile set

**Comment by mikeb01** [comment]
https://github.com/LMAX-Exchange/disruptor/blob/master/src/main/java/com/lmax/disruptor/AbstractSequencer.java#L81
