### ISSUE TITLE
How do i discard a event in a eventHandlder

### ISSUE THREAD

**Issue by LyLuo** [LMAX-Exchange/disruptor#293]
disruptor.handleEventsWith(a).then(b).then(c);

private void b(CommandEvent event, long sequence, boolean endOfBatch) {
        if(xxx){
            discard this event
            i dont want  c to hand this event
        }
    }

**Comment by ocoanet** [comment]
I think this question was already answered in a previous issue. The feature is not supported by the Disruptor API but you can easily set `event.Discarded = true;` in `b` and ignore discarded events in `c`.

**Comment by mikeb01** [comment]
This is the correct approach.
