### ISSUE TITLE
[Question] Disruptor shutdown

### ISSUE THREAD

**Issue by decebals** [LMAX-Exchange/disruptor#295]
Hi,

I have a task to process in parallel some input binary files and to create text files at output.
Each input file contains records.
```
IN (binary files) -> D1 with FileProcessors (Handlers) -> D2 with RecordProcessors -> OUT (text files)
```
So, I use two disruptors (`D1` and `D2`) with two different processor/handler types (`FileProcessor` and `RecordProcessor`). 
The `FileProcessor` takes an input file, reads the content and obtains a iterable collection of records (`FileReader implements Iterable<Record>`). After this, it publishes  `RecordEvent`s (each event 
 contains `Record` as data) to `D2`.
Everything goes OK except the shutdown disruptors part. I know what  `Disruptor.shutdown` does but for us is not OK to close the data migration process when the disruptors buffers are empty. We want to wait to process all records.
To shutdown the disruptor(s) smoothly I use a counter (`Atomic remainingItems`) that is decremented after an item/event has been processed. When `reimainingRecords` for a file is zero => the file was processed and I call a lifecycle method `endFile(File file)` (do some business). After a file is processed I decrement `remainingFiles` and if the new value is zero => the data processing process is over and I call a lifecycle method `endProcess`.

The problem with the approach described above is that I don't know from the beginning the total number of record from a file (it's an Iterable) and I cannot initialize correctly `reimainingRecords` for a specific file. The brute force (quick and dirty) solution was to prefetch all records in a list to get the size but the solution is not good because I have hundreds of thousands and even millions of record in memory and this only to have a records size to be able to shutdown smoothly the disruptor(s).

Do you see other possible viable solutions (disruptor poll, object pool, ...) ?

**Comment by Palmr** [comment]
Hi, sorry for the delayed reply.
Looking at this now, we think you can call `D1.shutdown(); D2.shutdown()` in your main thread after it has published all events in to `D1`.
It should block the `IN` thread on the first shutdown while it has a backlog of files to process. Once `D1` is drained and finished the main `IN` thread will move on to the second shutdown for `D2` where if the only publishing was from the handlers of `D1`, you know there will be no more input.
