### ISSUE TITLE
Markdown LMAX Documentation

### ISSUE THREAD

**Issue by emilypi** [LMAX-Exchange/disruptor#297]
Hi all, 

It would be great if the [docs](https://github.com/LMAX-Exchange/disruptor/blob/master/docs/Disruptor.docx) could be translated into markdown, so that they render well in browser. Would you mind a PR to that effect?

**Comment by sea36** [comment]
We'd be happy to consider a pull request.

**Comment by ronja-sigurdsdottir** [comment]
Great, will do @sea36

**Comment by emilypi** [comment]
Great, will do thanks @sea36

**Comment by Palmr** [comment]
Documentation had now been moved to ASCIIDoc(tor) rather than markdown. But that also renders will in a browser.
Hopefully that resolves this issue.

**Comment by emilypi** [comment]
Ah, great. Thank you @Palmr! This was still on my radar, but I'm happy someone went ahead with it.
