### ISSUE TITLE
How to customize MultiProducerSequencer?

### ISSUE THREAD

**Issue by SkyeBeFreeman** [LMAX-Exchange/disruptor#301]
When the ringbuffer is full, I want to do some other thing instead of just waiting for the next cursor generating. What can I do?

**Comment by ocoanet** [comment]
You can use `RingBuffer.tryNext` instead of `RingBuffer.next` and implement your own flow control strategy.

**Comment by SkyeBeFreeman** [comment]
> You can use `RingBuffer.tryNext` instead of `RingBuffer.next` and implement your own flow control strategy.

thx~
