### ISSUE TITLE
Multi consumer ringBuffer.next () blocked

### ISSUE THREAD

**Issue by guo2401100247** [LMAX-Exchange/disruptor#303]
public static void init() {
        //创建RingBuffer
        ringBuffer = RingBuffer.create(ProducerType.MULTI, new EventFactory<ConductAudits>() {
            @Override
            public ConductAudits newInstance() {
                return new ConductAudits();
            }
        },64,new YieldingWaitStrategy());
        //通过ringbuffer创建屏障
        SequenceBarrier barrier = ringBuffer.newBarrier();
        //创建消费者组
        LogBatchHandler[] consumers = new LogBatchHandler[10];
        for (int i=0;i<consumers.length;i++){
            consumers[i] = new LogBatchHandler();
        }
        //构建消费者工作池
        WorkerPool<ConductAudits> workerPool = new WorkerPool<ConductAudits>(
                ringBuffer,
                barrier,
                new EventExceptionHandle(),
                consumers);
        //设置多个消费者的sequence序号
        ringBuffer.addGatingSequences(workerPool.getWorkerSequences());
        //启动workpoll
        ExecutorService pool = Executors.newFixedThreadPool(12);
        workerPool.start(pool);
        if (ringBuffer!=null){
            LogCache.ringBuffer.put("ringBuffer",ringBuffer);
            logger.debug("Disruptor容器启动成功！");
        }else {
            logger.debug("Disruptor容器启动失败！");
        }
    }

   Problem description：
   If used in this way
   LogBatchHandler[] consumers = new LogBatchHandler[10];
   ExecutorService pool = Executors.newFixedThreadPool(12);
  
   result：obtain ringBuffer.next () is normal
   LogBatchHandler[] consumers = new LogBatchHandler[12];
   ExecutorService pool = Executors.newFixedThreadPool(10);
   result：
   obtain ringBuffer.next () is abnormal

conclusion：
Executors.newFixedThreadPool () The parameter of must be greater than the parameter of new logbatchhandler []

**Comment by sea36** [comment]
This is expected behaviour.

You are instructing the ringbuffer to gate on all the workers, but aren't providing enough threads to run them all.

Once the ringbuffer would wrap and overwrite unprocessed data, next() will start blocking.

**Comment by guo2401100247** [comment]
Ok thanks

发件人: Sam Adams [mailto:notifications@github.com]
发送时间: 2020年9月2日 16:30
收件人: LMAX-Exchange/disruptor
抄送: 郭家林; Author
主题: Re: [LMAX-Exchange/disruptor] Multi consumer ringBuffer.next () blocked (#303)


This is expected behaviour.

You are instructing the ringbuffer to gate on all the workers, but aren't providing enough threads to run them all.

Once the ringbuffer would wrap and overwrite unprocessed data, next() will start blocking.
