### ISSUE TITLE
WorkProcessor can hang when halted before run

### ISSUE THREAD

**Issue by ocoanet** [LMAX-Exchange/disruptor#308]
I noticed an issue in the `WorkProcessor` state in the .NET Disruptor codebase. I suspect that this issue affects the Java Disruptor as well.

- The `WorkerPool` starts with processors (A) and (B).
- One of the processor thread (A) starts running while the other one (B) is still waiting to be scheduled.
- The running processor processes the events.
- The `WorkerPool` is stopped. `WorkerPool.halt` invokes `WorkProcessor.halt` on (A) and (B). So (B) is halted before it was started.
- The processor thread for (B) gets scheduled. The `WorkProcessor.run` method sets `running` to true and never exits.
- The processor thread for (B) keeps running forever.

This problem is highly unlikely to happen in a production use case but it can happen in the tests that create very short lived disruptors. I think it should be fixed nonetheless.

The problem can be manually reproduced by running the `shouldProvideEventsToWorkHandlers` test multiple times:
```java
public class IssueTest
{
    @Test
    public void workHandlerIssue() throws Exception
    {
        for (int i = 0; i < 100; ++i)
        {
            DisruptorTest t = new DisruptorTest();
            t.setUp();
            t.shouldProvideEventsToWorkHandlers();
            t.tearDown();
        }
    }
}
```

I see two possible corrections:
- Use multiple values for the running state (IDLE, HALTED, RUNNING) like in the `BatchEventProcessor`.
- Wait for the processors to be effectively running in `WorkerPool.start`.

I can implement the correction in a pull request if needed. I can also write a suitable unit test.

**Comment by Palmr** [comment]
We've been noticing this problem in a couple of short-lived tests from `DisruptorTest` which were failing intermittently with enough regularity for me to exclude those tests from CI while I investigated.

We took a look yesterday and a fix using the tri-state rather than boolean for thread running state seems to be the way to go.
We have a pull request staged and this should get closed shortly I hope.

**Comment by grumpyjames** [comment]
I think we're happy to close at this point. I'm going to open a further issue about the future of WorkProcessor et al - we're not convinced they should be part of the core disruptor jar...
