### ISSUE TITLE
Evict WorkerPool et al from core of disruptor

### ISSUE THREAD

**Issue by grumpyjames** [LMAX-Exchange/disruptor#323]
These classes aren't used internally at LMAX; this makes it very difficult for us to act as maintainers of them. We're also not hugely convinced that using the disruptor in this way is a good fit for the underlying technology. I'm not going to get out the Jurassic Park scientist meme, but I feel I could.

Should we stop including those classes as part of the disruptor in 4.x? I think so...

**Comment by adol001** [comment]
In version 4.x, is there a successor to Disruptor::handleEventsWithWorkerPool? Can multiple consumers cooperate to process a batch of messages? (one message will only be processed by one consumer)

**Comment by denis-adamchuk** [comment]
[FAQ](https://github.com/LMAX-Exchange/disruptor/wiki/Frequently-Asked-Questions) still mentions WorkerPool which is confusing. Consider cleaning-it up.

**Comment by otaviocarvalho** [comment]
@grumpyjames how is that used internally at LMAX? Do you folks cover the standard way of using it somewhere?

**Comment by grumpyjames** [comment]
To be clear: we _don't_ use worker pool at LMAX; that's why we feel uncomfortable supporting it.
