### ISSUE TITLE
Is it possible to implement a resizing ring buffer?

### ISSUE THREAD

**Issue by Bennett-Lynch** [LMAX-Exchange/disruptor#331]
Is it possible to implement a ring buffer that will resize when full (to some maximum capacity)?

For example, perhaps I have a ring buffer that has a difficult-to-predict size, or I simply don't want to be concerned with the constant monitoring and tuning of its size. I want the ring buffer to be as small as possible to minimize wasted memory, but I also cannot afford blocking when it becomes full. In this case, I am willing to pay the expensive cost of resizing since it should happen relatively infrequently (_log n_ times for the lifetime of an application, if we use a doubling strategy).

I would still like to declare a maximum capacity to define some sane upper bound to prevent infinite run-away usage, but I can set that maximum comfortably high, say 100x what I expect the typical size to reach.

Perhaps some type of heuristic could even be used to shrink a ring buffer, to recover from rare bursts.

**Comment by Palmr** [comment]
The Disruptor is made for high performance systems, the kind where low latency and high throughput are the aim of the game.

To resize a ringbuffer on the fly would, if nothing else, require a new set of entries and copying over all the existing entries to the new array. This would require stopping the world on the producer side at least. Other bits to consider would be how sequences would map to the indexed entries in the new buffer and the general side effects of doing this in general.

Any kind of blocking/pause, while ringbuffers are copied, would go against the design principals of the Disruptor and its low-jitter high performance nature.
If you're looking for a resizeable buffer, the Disruptor is probably not the data structure for you.

**Comment by Bennett-Lynch** [comment]
I don't think the Disruptor's goal of high performance needs to be mutually exclusive with the cost of resizing. I may have an application that desires to take advantage of the high performance and throughput that the Disruptor offers but can afford to pay the 1-time cost of resizing. If my application runs for a month, and resizes a few times at the start of its lifecycle, this cost may be acceptable for my particular use case (and I imagine others, who explicitly permit it).
