### ISSUE TITLE
How to improve Disruptor when there are many producers?

### ISSUE THREAD

**Issue by zlp1992** [LMAX-Exchange/disruptor#340]
In my program, it receives a http request and then produces an event to RingBuffer. Since there are 200 thread default in tomcat, that is there are 200 producers. Each thread produces one event at a time then publishes to RingBuffer, in that case cpu usage is high. How to solve this? Here is our possible solution

Using multi RingBuffer and Hash(thread)%RingBufferSize to decide which RingBuffer to publish an event

Any suggestions?

**Comment by Palmr** [comment]
From what I remember of using Tomcat, it has a max limit of 200 worker threads for handling requests, and a queue of up to 100 requests for when 200 workers are all busy. And any further requests while all 200 workers are busy and all 100 queue slots are occupied get 503 responses.

I'm assuming your application is sustaining load like this, ~200 simultaneous connections? All of which are publishing some kind of event to a single ringbuffer which is serviced by one or more consumers?

When saying the "cpu usage is high" have you have already done some CPU profiling? Do you know where exactly the CPU spending its time in your use case?

I wonder if you can tell us more about your setup.
 - What is the size of the ringbuffer?
 - How many consumer threads are there?
 - What `WaitStrategy` are you using?
 - What method are you using to publish events to the ringbuffer?

The ideal way to answer all these questions would be to distill your code in to a small example which exhibits the same behavior.

If your CPU usage is your bottleneck, and the multi-producer part of the disruptor is a problem for you, having multiple ringbuffers may be a solution.
Though it would come at the cost of increased memory use and losing any benefits of keeping all data in one location to keep caches hot. Though with 200 active threads, memory use and keeping caches warm probably aren't a concern.

**Comment by mikeb01** [comment]
You should also check how the consumer is performing.  If it is overwhelmed and the ring buffer is full, then you will see high CPU usage if you are using one of the blocking publish methods.  An alternative is to consider that when the ring buffer is full, then the system is at capacity and should reject new requests.  To do this, use one of the non-blocking `try*` publish methods and if the message fails to publish then reject the request with a `503` http response.

**Comment by zlp1992** [comment]
@Palmr Hi, the size of ringbuffer is 2048 and there is only one consumer thread created by `disruptor.handleEventsWithWorkerPool`, `WaitStrategy` is `BlockingWaitStrategy` since it's  the most conservative with the respect to CPU usage. and we are using `disruptor.getRingBuffer().tryPublishEvents(translator, t)` to publish event. 
Actually, we are replacing `BlockingQueue` with `Disruptor` in `Pinpoint ` 's agent to send span event.

**Comment by zlp1992** [comment]
@mikeb01 Hi, our ring buffer is not full for there is no error throws when publish event. And maybe it's the `CAS` when many producer threads that cost the CPU.

**Comment by Palmr** [comment]
The CAS loop at `com/lmax/disruptor/MultiProducerSequencer.java:185` is very much a likely candidate for high CPU use if you have 200 producers all attempting to publish there will be a lot of contention on the sequence.

There could be potential work done to look at the `MultiProducerSequencer` and see if there's something else we could do there.
The busy-spin CAS loop is perhaps not the ideal pattern for a large number of producers in _some_ cases, such as this one. Typically CPU use is a price worth paying for lower latency, but not for everyone.

Before making any changes we would definitely need a decent benchmark for `MultiProducerSequencer::tryNext`.
This would let us profile and prove our assumptions of where all the CPU time is spent.
It would also be needed to monitor the effects, and potential side-effects, of any changes to this code.

Having 200 producers to a single ringbuffer is probably not the use case that the disruptor has been designed for, so having multiple ringbuffers as you initially suggested might be a more efficient way to avoid this issue.

**Comment by zlp1992** [comment]
Thanks, we will try multiple ringbuffers to see if it works
