### ISSUE TITLE
[Question] Is Disruptor termination-safe

### ISSUE THREAD

**Issue by ratanasov1** [LMAX-Exchange/disruptor#348]
If a Disruptor is placed into shared-memory for IPC, can it be used in a way such that the system moves forward even when a producer crashed/was killed in between the 2-phase commit or a consumer crashed/was killed and never updated its position?

**Comment by sea36** [comment]
No, it isn't.  The disruptor is designed for messaging within a single process.

There are quite a few issues that you would need to address before you could use it in a shared-memory IPC role.

**Comment by ratanasov1** [comment]
Could you give some hints how Disruptor can be used in a shared-memory IPC role? Will it be termination-safe then?

**Comment by MendelMonteiro** [comment]
If you want to do IPC over shared memory I would recommend you look into [Aeron](https://github.com/real-logic/aeron)

**Comment by Palmr** [comment]
> If you want to do IPC over shared memory I would recommend you look into [Aeron](https://github.com/real-logic/aeron)

I would also suggest that.
The Disruptor is just a inter-thread messaging library, it is not made for inter-process messaging.
Aeron is an excellent messaging transport library made for IPC and network based messaging.
