### ISSUE TITLE
ThreadHints.onSpinWait() in BlockingWaitStrategy cause high cpu load sometimes

### ISSUE THREAD

**Issue by KaimingWan** [LMAX-Exchange/disruptor#359]
We use disruptor 3.4.2 and find sometimes the cpu load goes very high and the jstack show that the thread is invoking ThreadHints.onSpinWait() in BlockingWaitStrategy. Now we implement a custom BlockingWaitStrategy and remove this code.

**Comment by KaimingWan** [comment]
Is the following code still will cause high cpu load?  Thread invoke barrier.checkAlert() will occupy cpu for long time. I think this will also cause high cpu load. Am I right?

```java
        while ((availableSequence = dependentSequence.get()) < sequence)
        {
            barrier.checkAlert();
        }
```

**Comment by Palmr** [comment]
I think this is a duplicate of #358 so closing this issue as more discussion happened there already.
