### ISSUE TITLE
Need a release a year ago.

### ISSUE THREAD

**Issue by rgoers** [LMAX-Exchange/disruptor#369]
Log4j 2 has been trying to modularize as JPMS modules for well over a year. We have been stuck because the disruptor hasn't had a release in 3 years, let alone one that simply declared an Automatic Module name in the Manifest. I see you have recently introduced a module-info.java file but that does us no good it if isn't going to be released in the next few weeks. At the very least can you please create a branch of 3.4.2 and add the Automatic module name to the manifest and release that so we can move forward?

See #279. That was 13 months ago.

**Comment by Palmr** [comment]
Unfortunately your comment on #279 wasn't seen as it was made after the PR was closed and it was several months after that before myself and other current maintainers took over working on the disruptor.

It seems like a reasonable ask to have the automatic module name change as a 3.4 release, and that's what we've done this afternoon.

We have just published version 3.4.3 and it should be visible everywhere shortly: https://repo1.maven.org/maven2/com/lmax/disruptor/3.4.3/
