### ISSUE TITLE
Why are SingleProducerSequencer padded with bytes?

### ISSUE THREAD

**Issue by Carmon-Lee** [LMAX-Exchange/disruptor#372]
Since SingleProducerSequencer is meant to been used by only one thread, there seems to be no contention between multi-thread. 
My understanding about false sharing is this: only when multiple threads read or write multiple variables can false sharing happen.
So, why is SingleProducerSequencer designed with padding bytes since it is to be used in single thread situation?
Or rather, my understanding about false sharing is not correct?

Can anybody explain, thanks.

**Comment by eliquinox** [comment]
While your application may be using only one thread (the one that you define), JVM runs other threads in the background (GC thread, for example). The byte padding exists to protect false sharing with those other JVM threads. It is possible that another JVM thread, other than the one you define in your application can be using the bit of memory right next to SingleProducerSequencer (RingBuffer has similar kind of padding, and it is for the same reason). In such scenario, false sharing of a cache line between your application thread and that other JVM threads can create contention and potentially slow down memory access for you application thread.
