### ISSUE TITLE
How to use disruptor on multi producer and multi consumer condition?

### ISSUE THREAD

**Issue by adol001** [LMAX-Exchange/disruptor#377]
I can't find code example, is it to change ProducerType.SINGLE to ProducerType.MULTI, the other is same as one producer and multi consumer condition?
Hope to get some guidance

If using one producer and ProducerType.MULTI, the producer is thread safe？

**Comment by adol001** [comment]
Also hope to get one thread-safe producer and multi consumer condition code example

**Comment by sea36** [comment]
If you are sure that there will only ever be a single thread adding events to the ring buffer then setting ProducerType.SINGLE will improve performance, but it is dangerous to set this if there could be multiple producer threads.

You don't have to change any settings to add multiple consumers taking events off from the ring buffer.
