### ISSUE TITLE
Colored Schema

### ISSUE THREAD

**Issue by KabDeveloper** [LMAX-Exchange/disruptor#379]
Is there a way to update the old schema used on the introduction to a fresh one?

I just made this colored one, do you have ideas about some updates on it ?

![disruptor](https://user-images.githubusercontent.com/34721845/117596935-65dbf480-b13c-11eb-8878-e1f8ae0b1f12.png)

**Comment by grumpyjames** [comment]
Hello again!

I would advise against spending any time improving the existing documentation - our intention is to rewrite most of it as part of the work towards 4.0. That work is probably better done by folks somewhat more familiar with the project.

Side note: I tend to ask, when I read issues, or pull requests:

> is this a substantive change? 

I look at this issue, and I think my answer is no. Really, my primary question is "why?". I'm not sure there is a good answer to that for this change, and there should be :-).

**Comment by KabDeveloper** [comment]
@grumpyjames Thank you ! Looking forward for 4.0, Good Luck !
