### ISSUE TITLE
Add OSGi headers to MANIFEST.MF

### ISSUE THREAD

**Issue by mattrpav** [LMAX-Exchange/disruptor#380]
Apache Karaf (and other OSGi runtimes) that use log4j2 will need the lmax release to include the OSGi header data.

The bnd gradle plugin (v5.3.0) should have no problem auto-generating the correct headers, since the disruptor packaging is straightforward. 

I'd create a PR, but am unfamiliar with gradle.

[Gradle BND plugin](https://github.com/bndtools/bnd/tree/master/biz.aQute.bnd.gradle)

Sample OSGi metadata from LMAX disruptor 3.4.2

```
Bundle-Description = Disruptor - Concurrent Programming Framework
Bundle-DocURL = http://lmax-exchange.github.com/disruptor
Bundle-ManifestVersion = 2
Bundle-Name = Disruptor Framework
Bundle-SymbolicName = com.lmax.disruptor
Bundle-Vendor = LMAX Disruptor Development Team
Bundle-Version = 3.4.2

Require-Capability = 
	osgi.ee;filter:=(&(osgi.ee=JavaSE)(version=1.7))

Export-Package = 
	com.lmax.disruptor;uses:=com.lmax.disruptor.dsl;version=3.4.2,
	com.lmax.disruptor.dsl;uses:=com.lmax.disruptor;version=3.4.2,
	com.lmax.disruptor.util;uses:="com.lmax.disruptor,sun.misc";version=3.4.2
Import-Package = 
	com.lmax.disruptor;version="[3.4,4)",
	com.lmax.disruptor.dsl;version="[3.4,4)",
	com.lmax.disruptor.util;version="[3.4,4)",
	sun.misc
```

**Comment by Palmr** [comment]
Hi @mattrpav , thanks for raising this issue and providing us with some information about how the OSGi metadata looked before and its use in Karaf.

I have taken a look at the bnd plugin as suggested and it seemed fairly trivial to add it to the project and migrate some manual manifest settings to use the bnd plugin.
After making my changes, the manifest looks as follows:

```
Manifest-Version: 1.0
Automatic-Module-Name: com.lmax.disruptor
Bnd-LastModified: 1621097025262
Built-By: nick
Bundle-Description: Disruptor - Concurrent Programming Framework
Bundle-DocURL: http://lmax-exchange.github.com/disruptor
Bundle-ManifestVersion: 2
Bundle-Name: Disruptor Framework
Bundle-SymbolicName: disruptor
Bundle-Vendor: LMAX Disruptor Development Team
Bundle-Version: 4.0.0.SNAPSHOT
Created-By: 11.0.11 (Oracle Corporation)
Import-Package: java.lang,java.lang.invoke,java.lang.reflect,java.secu
 rity,java.util,java.util.concurrent,java.util.concurrent.atomic,java.
 util.concurrent.locks,java.util.function,sun.misc
Private-Package: com.lmax.disruptor,com.lmax.disruptor.dsl,com.lmax.di
 sruptor.util
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=11))"
Tool: Bnd-5.3.0.202102221516
```

These look substantially different to the 3.x branch. The `Bundle-SymbolicName` is changed, the `Import-Package` is considerably different and the `Export-Package` is entirely missing. 

One of the main reasons we initially removed it from the project was because there was nothing in the project, e.g. a test, that would fail when if the bundle information was incorrect.

My main issue with adding this information back is that I'm again left in a position of not having something in the disruptor project that confirms the bundle specification is correct.

Having never worked with OSGi or Bnd/Bndtools before it may take me a while to figure out how best to do this.
If you, or anyone reading this, is more knowledgable when it comes to OSGi and especially how to test a bundle, getting in touch would be appreciated.

**Comment by mattrpav** [comment]
@Palmr sure thing. Can you share the gradle bnd plugin cfg you were using? I'd also be up for hoping on a chat channel to work through it. Shouldn't take more than :20 to :30 min. 

1. Looks like the Private-Package has the values that we'd expect to see in Export-Package
2. The Import-Package has all JDK-owned packages and they (generally) do not need to be specified.
3. Symbolic name change isn't a huge big deal.. but it'd be good to flip it back in case any users are have build tasks around it.

My gradle-n00b scan of the gradle docs, and I think we might need to add something like this:

``
jar {
  bnd('-exportcontents: com.lmax.disruptor,com.lmax.disruptor.dsl,com.lmax.disruptor.util',
    ....)
}
``

ref: [Bnd Gradle Plugin doc](https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/README.md#using-the-latest-development-snapshot-build-of-the-bnd-gradle-plugins)

A quick and dirty OSGi cheatsheet for plain-jane jars 

1. Import any non-JDK packages that your module uses
2. Export packages that your jar creates

Unit testing would mean firing up pax-exam or other osgi-test framework. Probably overkill for a jar with only 3 packages. 

If you download Apache Karaf (v4.3.2) and drop the jar in the deploy/ folder you'll know pretty quick.

1. ./bin/karaf (start karaf in foreground and have the shell)
2. Drop disruptor jar in the deploy/ folder
3. karaf> ls -t 0 (list all bundles)
4. Last bundle in the list is probably the disruptor jar (take note of the number on the left for step #5)
5. karaf> headers $number
6. Review / share output back here 

The text output from #5 should be white/grey. Any colors (red) indicate a java package wiring problem

**Comment by Palmr** [comment]
@mattrpav My changes are here: https://github.com/Palmr/disruptor/commit/22f247fefacfdaa07f49dad3bb785cfaad8503ed
I was going to add some kind of test first before raising a PR.

A chat might be good, there should be an email address on my profile here, send me a message and we should be able to talk :)

**Comment by Palmr** [comment]
My current work is on the `osgi` branch of my fork (https://github.com/Palmr/disruptor/tree/osgi) if you want to try building locally yourself you can take that fork and work on top of it.

@mattrpav I have added the `-exportcontents` as suggested, and have been trying to use Apache Karaf to see how well it has worked, so far with no success.
`-exportcontents` did add the `Export-Package` section to the manifest with good looking values, but no `Import-Package` which the previous Disruptor 3.x jars showed. I tried adding `'-includepackage': 'com.lmax.disruptor.*'` which does add a basic `Import-Package` to the manifest but it's missing version information and shows up red in Apache Karaf.

See https://github.com/Palmr/disruptor/blob/e99ce02a1db2b98d88bf938012a61ecdc317bf7c/build.gradle#L99 for the build file used to generate the jar for the following screenshot.

![image](https://user-images.githubusercontent.com/360183/128609768-6816a15d-b9a4-468f-b01d-f95c49c4313b.png)

I am running Karaf using OpenJDK-11 and notice it also appears to be failing to resolve `java.lang.invoke` and `java.util.function` which is interesting?

If you still have time to chat, I'm still available via email (see my github profile/commits).

**Comment by mattrpav** [comment]
Hi @Palmr -- Yep. I'll pull this down on Monday. Thanks!

**Comment by mattrpav** [comment]
Battled gradle + bnd for a while. Opened issue w/ BND [#4816](https://github.com/bndtools/bnd/issues/4816)

**Comment by mattrpav** [comment]
The fix:

```
     manifest.attributes('Built-By': System.properties.get('user.name'),
             'Automatic-Module-Name': moduleName)
     bnd(
-            '-exportcontents': 'com.lmax.disruptor.*',
-            '-includepackage': 'com.lmax.disruptor.*',
+           '-exportcontents': 'com.lmax.disruptor.*;-noimport:=true',
+            '-noimportjava': 'true',
+            'Import-Package': '!*',
             'Bundle-Name': fullName,
             'Bundle-Vendor': teamName,
             'Bundle-Description': fullDescription,
             'Bundle-DocURL': siteUrl,
-            'Bundle-SymbolicName': moduleName,
+            'Bundle-SymbolicName': moduleName
     )
 }
```

**Comment by mattrpav** [comment]
@Palmr thanks!
