### ISSUE TITLE
I want to persist to hard disk or redis. Is there any way?

### ISSUE THREAD

**Issue by liwenzheng** [LMAX-Exchange/disruptor#393]
I want to persist to hard disk or redis. Is there any way?

**Comment by Palmr** [comment]
If you want this kind of functionality you would have to write it yourself.
You could get something like this with a write to redis before a publish to the ringbuffer.
Then some code to re-prime the ringbuffer in the case of a restart, knowing what sequence was last consumed and reading from redis and publishing any events after that back in to the buffer.
