### ISSUE TITLE
Fix to #227 not present in official releases.

### ISSUE THREAD

**Issue by JakubWagner1019** [LMAX-Exchange/disruptor#402]
The fix to:
https://github.com/LMAX-Exchange/disruptor/issues/227
was marked as 'merged' in 2018. 
Despite this, in 3.4.4 nor in any other version the fix is not present.

**Comment by Palmr** [comment]
This fix will be included in v4 which is hopefully (:crossed_fingers:) going to be release before the end of the year.

**Comment by Palmr** [comment]
This change should be in the 4.0.0.RC1 release, and subsequent releases
