### ISSUE TITLE
Disruptor Throughput and Performance vs Apache kafka

### ISSUE THREAD

**Issue by PanagiotisDrakatos** [LMAX-Exchange/disruptor#403]
Can someone tell me What is an estimation throughput for Disruptor in TPS. I know that apache Kafka can handle around 135,000 messages per second what is the capabilities of Disruptor. Can you tell me an estimation throughput?

**Comment by noakcn** [comment]
你发的邮件我已经收到了。
                                    以上为自动回复邮件

**Comment by MendelMonteiro** [comment]
I think you're comparing apples and oranges here as the Disruptor is used for communicating between threads and Kafka is used for communicating between machines / processes / threads.  Also note that Kafka provides persistence of messages and replay for any late joining consumers whereas the Disruptor does not provide any such functionality.

**Comment by isolgpus** [comment]
I agree with @MendelMonteiro 's  point that this wouldn't be a fair comparison as the features supported by these two libraries are considerably different. But out of curiosity I looked at the reported benchmarks here
https://github.com/LMAX-Exchange/disruptor/wiki/Performance-Results
It looks like depending on the configuration the Disruptor can do up to 23M ops per second.
