### ISSUE TITLE
Something optimize suggestion.

### ISSUE THREAD

**Issue by SteafanMrZhou** [LMAX-Exchange/disruptor#405]
**Describe the bug**
When i studying source code of Disruptor,i find some optimize bugs,so i wana solve it.
eg.No @ Override、No Complete annotation.
Can i fix it? Cause i want be a contributor for Disruptor,thanks.

**Comment by Palmr** [comment]
Yes, please raise a pull request and we will review.

**Comment by Palmr** [comment]
Closing this issue while waiting for a PR to show up

**Comment by SteafanMrZhou** [comment]
@Palmr Hi,I'm so sorry to delay raising a pull request for issue#405,cause i'm very busy a period ago.
Awaiting your review,thanks.
