### ISSUE TITLE
does disruptor support a process graph?

### ISSUE THREAD

**Issue by xiedeacc** [LMAX-Exchange/disruptor#406]
producerA produce eventA ,  handlerA handle eventA then produce eventB,
handlerB handle eventB but need wait until all handlerA finished produce eventB.
does disruptor current api can made this?

**Comment by MendelMonteiro** [comment]
Hi,  dependency graphs are supported by the Disruptor (there is even a DSL built to make configuring them easier)

The docs regarding the graphs are here: https://lmax-exchange.github.io/disruptor/user-guide/index.html#_consumer_dependency_graph and here https://github.com/LMAX-Exchange/disruptor/blob/master/src/docs/asciidoc/en/disruptor.adoc#26-pipelines-and-graphs

In your use case you would create an event type which can contain the data for both `EventA` and `EventB` and then have two handlers where `HandlerB` depends on `HandlerA`.  `HandlerA` can then write data into the event for it to be proccessed by `HandlerB` once `HandlerA` has finished processing the event (i.e. once it exits out of it's `onEvent` method).

**Comment by xiedeacc** [comment]
ok  thanks
