### ISSUE TITLE
[Help] Can consumers act like producers?

### ISSUE THREAD

**Issue by superyuuki** [LMAX-Exchange/disruptor#415]
With actors, i can have any actor talk to another to do concurrency. However, it feels like if i want to use disruptor, i can only have a single producer stage (maybe coming from different producers) but after that goes only to consumers. Is it possible to have a consumer also act as a producer of the same or different type of event?

**Comment by MendelMonteiro** [comment]
Yes, nothing prevents an event handler from publishing events to other Disruptors or even the same Disruptor.
Just be aware of potential deadlocks if the blocking `next()` methods are used to publish the events.  These deadlocks can occur when the destination Disruptor's ring buffer is full and its forward progress relies on the event being being published.
