### ISSUE TITLE
[Question] Two disruptors interacting with one consumer

### ISSUE THREAD

**Issue by superyuuki** [LMAX-Exchange/disruptor#416]
Is this safe?

**Comment by superyuuki** [comment]
Or maybe is there a way to have a disruptor choose what thread/executor to consume on depending on the contents of the event?

**Comment by MendelMonteiro** [comment]
You can have two event handlers registered with a single Disruptor and the handlers can discard any types of events they are not interested in.  Each event handler will run in its own thread.

It would be much clearer if you could post a sample of what you want to accomplish.
