### ISSUE TITLE
use disruptor with multi consumers and get wrong

### ISSUE THREAD

**Issue by AnswerNo2** [LMAX-Exchange/disruptor#419]
disruptor version: 
     
      <dependency>
          <groupId>com.lmax</groupId>
          <artifactId>disruptor</artifactId>
          <version>3.4.3</version>
      </dependency>

java version: 1.8

springboot version:2.5

10 Threads consumer message, after 5minitus later,  an thread occurred:

![image](https://user-images.githubusercontent.com/22674332/162563004-46ee5c0e-3c72-4ab5-9df1-bce25864f715.png)

one thread occurred TIMED_WAITING, and then, disruptor can not consumer messge any more, stopped, 

Notice：i  produced   About 5 messages  per second

@Configuration
public class RingBufferConfiguration {

    @Autowired
    private ApplicationContext applicationContext;

    @Bean
    public RingBuffer<MessageVO> ringBuffer() {
        //  ring buffer size
        int bufferSize = 1024 * 1024;;
        //固定线程数
        int nThreads = 10;
        ExecutorService executor = Executors.newFixedThreadPool(nThreads);

        EventFactory<MessageVO> factory = new EventFactory<MessageVO>() {
            @Override
            public MessageVO newInstance() {
                return new MessageVO();
            }
        };

        // create ringBuffer
        RingBuffer<MessageVO> ringBuffer = RingBuffer.create(ProducerType.SINGLE, factory, bufferSize,  new BlockingWaitStrategy());
        SequenceBarrier barriers = ringBuffer.newBarrier();
        // 10 threads consumer message
        RiskCalculateHandler[] consumers = new RiskCalculateHandler[50];
        RiskCalculateService riskCalculateService = applicationContext.getBean(RiskCalculateService.class);
        AccountChangeHandler accountChangeHandler = applicationContext.getBean(AccountChangeHandler.class);
        for (int i = 0; i < consumers.length; i++) {
            consumers[i] = new RiskCalculateHandler(riskCalculateService, accountChangeHandler);
        }
        WorkerPool<MessageVO> workerPool = new WorkerPool<MessageVO>(ringBuffer, barriers,
                new RiskExceptionHandler(ringBuffer, riskCalculateService), consumers);
        ringBuffer.addGatingSequences(workerPool.getWorkerSequences());
        RingBuffer<MessageVO> ringBufferFinal = workerPool.start(executor);
        return ringBufferFinal;
    }

}

![image](https://user-images.githubusercontent.com/22674332/162563279-3ff0d754-d152-4081-8f08-220a7d21015d.png)

![image](https://user-images.githubusercontent.com/22674332/162563976-23728d2b-23f4-48bc-baf9-25f19d56a01e.png)

How to solve this question ?

**Comment by noakcn** [comment]
你发的邮件我已经收到了。
                                    以上为自动回复邮件

**Comment by grumpyjames** [comment]
The usual cause of that method blocking is that the ringbuffer is full.

I would guess that the consumers are not able to process the events as fast as they arriving. You could check this by adding logging to the consumers to track their progress, or other logging to periodically measure the depth of the ringbuffer.
