### ISSUE TITLE
about Pros and Cons of Disruptor

### ISSUE THREAD

**Issue by HelloTo4x** [LMAX-Exchange/disruptor#422]
Hi, can u tell me what is Pros and Cons of Disruptor in the real world ? thank u so much

**Comment by SteafanMrZhou** [comment]
Have you actually used Disruptor?

**Comment by HelloTo4x** [comment]
it can process a lot of data, doesn't need to lock... but it needs to full of slots on Ring buffer, right ?

**Comment by SteafanMrZhou** [comment]
Disruptor is often used in high concurrency or computing scenarios with extreme requirements for computing speed, such as carrying millions or tens of millions of concurrent requests, and business scenarios that require computing a large amount of data in a short period of time. The data that needs to be calculated may be at the level of 100,000, millions, tens of millions, or even tens of thousands.

From the test cases and results officially given by Disruptor, it can be seen that Disruptor can show extreme advantages in business scenarios with high concurrency and processing large amounts of data.

If your project needs to carry millions or more concurrent requests, or needs to process millions of business data, or even has extreme requirements on the response time of business data, you can consider using Disruptor, I believe it will bring you good experience.

**Comment by SteafanMrZhou** [comment]
You are talking about the size of RingBuffer. This is set according to the actual number of businesses you need to process. There is no fixed number. Here is a value rule for you. This is extracted by me, and according to my The test of my own business, I feel that it is OK:
The reasonable value of RingBufferSize is generally equal to:
1. If the number of your business is exactly equal to the N power of 2, then RingBufferSize is equal to this number;
2. If the number of your business is not equal to the Nth power of 2 and less than 1024, then RingBufferSize is equal to 1024 minus the number of your business, and finally rounded up, and the rule of the Nth power of 2 must be satisfied;
3. If the number of your business is not equal to the Nth power of 2, and is greater than 1024, then RingBufferSize is equal to the number of your business plus 1024, and finally rounded up, and the rule of the Nth power of 2 must be satisfied.
The above are just the value rules that I have summed up in the process of using Disruptor. They do not represent the official Disruptor. For specific use, please refer to the following.

**Comment by HelloTo4x** [comment]
> You are talking about the size of RingBuffer. This is set according to the actual number of businesses you need to process. There is no fixed number. Here is a value rule for you. This is extracted by me, and according to my The test of my own business, I feel that it is OK: The reasonable value of RingBufferSize is generally equal to:
> 
> 1. If the number of your business is exactly equal to the N power of 2, then RingBufferSize is equal to this number;
> 2. If the number of your business is not equal to the N power of 2 and less than 1024, then RingBufferSize is equal to 1024 minus the number of your business, and finally rounded up, and the rule of the N power of 2 must be satisfied;
> 3. If the number of your business is not equal to the N power of 2, and is greater than 1024, then RingBufferSize is equal to the number of your business plus 1024, and finally rounded up, and the rule of the N power of 2 must be satisfied.
>    The above are just the value rules that I have summed up in the process of using Disruptor. They do not represent the official Disruptor. For specific use, please refer to the following.

thank you for your replying. I am not sure about i think. i think: "Disruptor can convert from Multithreads  -> single thread(to avoid locking), and convert single thread -> multithreads again. So usually, they need 2 ring buffer in the architect, is it right ? i am not sure about i think, and thank you, i love China <3

**Comment by SteafanMrZhou** [comment]
No,there will only be one RingBuffer from beginning to end.

**Comment by HelloTo4x** [comment]
> be one RingBuffer from beginning to end.

So how you can convert from Multithreads -> single thread(to avoid locking), and convert single thread -> multithreads again ? Normally, i see some architecture, it usully has 2 ring buffer, i don't make sure i am right. Like this, we will convert from Multithread to single thread to avoid lock... to process business logic, after finishing, we will convert to multithread 
![31-5-2](https://user-images.githubusercontent.com/80832558/171090646-2f7dc745-99b5-481b-ad01-915dc74e4448.jpg)

**Comment by HelloTo4x** [comment]
hi @SteafanMrZhou , can u help me

**Comment by HelloTo4x** [comment]
hi @SteafanMrZhou can u help me

**Comment by SteafanMrZhou** [comment]
> hi @SteafanMrZhou can u help me

I suggest that you sort out your questions and post them together.
