### ISSUE TITLE
What size should I make the ring buffer if you are using a virtual machine without l3?

### ISSUE THREAD

**Issue by crazy-dad** [LMAX-Exchange/disruptor#424]
According to the [FAQ,](https://github.com/LMAX-Exchange/disruptor/wiki/Frequently-Asked-Questions) the size of the ringbuffer is estimated according to the l3 of the CPU, but if you are using a virtual machine, how to estimate the size of the ringbuffer without l3?

**Comment by MendelMonteiro** [comment]
If you are running on a virtual machine that level of performance tuning is probably not relevant.
That being said, you can get an empirical answer by trying different sizes and see which one you get the best performance with.
