### ISSUE TITLE
4.0 GA release

### ISSUE THREAD

**Issue by viragtripathi** [LMAX-Exchange/disruptor#426]
Is there a timeline for 4.0 GA release?

**Comment by viragtripathi** [comment]
Thanks for the quick response. We just wanted to make sure there is enough consensus from the community of its stability since there are breaking changes.

**Comment by einali** [comment]
@Palmr 
Is there an update for estimation?

**Comment by Palmr** [comment]
Hi @einali 

Hopefully soon. I'm waiting on getting the open PRs merged and perhaps a little bug fix here and there.

**Comment by Hc747** [comment]
Hi @Palmr, is this library still in active development? Cheers

**Comment by Palmr** [comment]
@Hc747 Yes, just need to find the time

**Comment by Hc747** [comment]
> @Hc747 Yes, just need to find the time

If I can help with anything, please LMK

**Comment by Hc747** [comment]
Bumping - are there any updates to the status of this project? @Palmr

**Comment by rohitdev** [comment]
Is there a GA release for 4.0 happening soon or some planned timeline ? Its been quite silent here.

**Comment by Palmr** [comment]
![Consider it done](https://media.giphy.com/media/C7Y7Ihbp6jlTZWOpjx/giphy.gif)
