### ISSUE TITLE
Is there performance problems for method[next] in class[MultiProducerSequencer]

### ISSUE THREAD

**Issue by horse20ne** [LMAX-Exchange/disruptor#430]
Is there performance problems for method[next] in class[MultiProducerSequencer] when cursorSequence move from Long.MAX_VALUE to Long.MIN_VALUE?

-----------------------

```
public long next(int n) {
        if (n < 1) {
            throw new IllegalArgumentException("n must be > 0");
        }

        long current;
        long next;

        do
        {
            current = cursor.get();
            next = current + n;

            long wrapPoint = next - bufferSize;
            long cachedGatingSequence = gatingSequenceCache.get();

            if (wrapPoint > cachedGatingSequence || cachedGatingSequence > current)
            {
                ......
            }
            else if (cursor.compareAndSet(current, next))
            {
                break;
            }
        }
        while (true);

        return next;
}
```

- when variable `cursor` move from `Long.MAX_VALUE` to `Long.MIN_VALUE`
- variable `current` would always be less than 0, but variable `cachedGatingSequence` would be greater than 0 before queue becomes empty even if `current - cachedGatingSequence < bufferSize`
- the judgement would cause cpu idle util queue becomes empty
- the same situation to `wrapPoint > cachedGatingSequence`
- Would  `cachedGatingSequence - wrapPoint >= 0`  be better ?

-----------------------------

In my opinion, integral variable operation, for example,  `a - b > 0` is not equal to `a > b` (a = Integer.MIN_VALUE, b = Integer.MAX_VALUE)

**Comment by grumpyjames** [comment]
There might be. I'm not sure that was given much thought. A system processing 1,000,000 events a second would take more than 200,000 years to pass through this boundary.

Do you have a system or circumstance where you expect this to be a problem for you?

**Comment by horse20ne** [comment]
I see. This question I had when reading the source code. However, I had not consider the actual situation.
Thanks for your patience very much.
