### ISSUE TITLE
pictures in doc files are broken

### ISSUE THREAD

**Issue by eddieHRS** [LMAX-Exchange/disruptor#431]
Though it is not a functional bug, but brings bad experience while reading docs.  ^_^

**Comment by swarren12** [comment]
Hi,

Is this all images or only certain ones? 

Are you reading the docs in the browser at https://lmax-exchange.github.io/disruptor/ or generating them locally using the Gradle script?

Thanks

**Comment by eddieHRS** [comment]
> Hi,
> 
> Is this all images or only certain ones?
> 
> Are you reading the docs in the browser at https://lmax-exchange.github.io/disruptor/ or generating them locally using the Gradle script?
> 
> Thanks

i think all pictures are broken. And i generate them locally with a IDEA plugin.  ^_^

More: if i add `:imagesdir: ../../../resources/images/` and change `image::../resources/images/user-guide/models.png[]
` to `image::user-guide/models.png[]` in file `src/docs/asciidoc/en/user-guide/10_using_the_disruptor.adoc`. it works.
