### ISSUE TITLE
Can a new 3.X version be released based on 3.4.4?

### ISSUE THREAD

**Issue by 724027069** [LMAX-Exchange/disruptor#449]
Version 3.4.4 is released in 2021. Can you release a new version without any changes? If the version is not released, people will think that the version is inactive or vulnerabilities cannot be fixed in time. Thank you.

**Comment by Palmr** [comment]
> Can you release a new version without any changes?

Technically, yes. Would we? No.

> If the version is not released, people will think that the version is inactive or vulnerabilities cannot be fixed in time.

I would hope people would only think this if there were any vulnerabilities. If there was a vulnerability in the 3.x version we would release a new version with a fix.

No releases will ever be done for the sake of bumping up a version number.

**Comment by adski31** [comment]
The (test) dependency junit:junit:4.12 is vulnerable as per [Maven Central](https://mvnrepository.com/artifact/junit/junit/4.12). Spin a 3.4.5 with junit 4.13.2 and I bet you'd make a lot of people clamoring for a new revision very happy.

**Comment by Palmr** [comment]
I'd hope anyone who might be using the Disruptor would be able to distinguish between a dependency and a test dependency.

For people impacted by that test dependency having a CVE, that's developers of the 3.x Disruptor branch, I would expect they could read the CVE too and understand it's about the TemporaryFolder rule, which isn't used in any Disruptor tests. So moot.

I think it would likely annoy a lot of people seeing a new release go out with zero functional changes.
