### ISSUE TITLE
Directly replace Fence with the methods setRelease, setVolatile, and getAcquire. No need to set barriers via VarHandle

### ISSUE THREAD

**Issue by chenggwang** [LMAX-Exchange/disruptor#456]
**Describe the bug**
This can't be considered a bug, just some minor use of VarHandle's API instead of fence. It's not a high priority either.

**Expected behavior**
Cleaner code and clearer semantics. Avoid using fences at the application level if possible, unless the existing read/write APIs are not sufficient

**Desktop (please complete the following information):**
 - OS: [windows]
 - Version [win 11]
 - JVM Version [openjdk 17]

**Additional context**
There are two files involved Sequence.java
SequenceVarHandleBarrier.java, read and write methods

**Comment by chenggwang** [comment]
@Palmr By the way . I see that `handleEventsWithWorkerPool` has been removed. Are there any other APIs in the new version that can directly achieve non-duplicate consumption? If not, what should I do?

**Comment by Palmr** [comment]
As mentioned on the PR that followed this: There is seemingly no tangible benefit, and the alternative proposed was already considered.

Closing this issue, though it could be re-opened if something were to change.
