### ISSUE TITLE
In version 4.x, is there a successor to Disruptor::handleEventsWithWorkerPool? Can multiple consumers cooperate to process a batch of messages? (one message will only be processed by one consumer)

### ISSUE THREAD

**Issue by tcmot** [LMAX-Exchange/disruptor#466]
Hi,all.

In version 4.x, is there a successor to Disruptor::handleEventsWithWorkerPool? Can multiple consumers cooperate to process a batch of messages? (one message will only be processed by one consumer)

Thanks all.

**Comment by laulee5135** [comment]
How was it resolved,please.

**Comment by laulee5135** [comment]
> Hi,all.
> 
> In version 4.x, is there a successor to Disruptor::handleEventsWithWorkerPool? Can multiple consumers cooperate to process a batch of messages? (one message will only be processed by one consumer)
> 
> Thanks all.


How was it resolved,please.

**Comment by tcmot** [comment]
> > Hi,all.
> > In version 4.x, is there a successor to Disruptor::handleEventsWithWorkerPool? Can multiple consumers cooperate to process a batch of messages? (one message will only be processed by one consumer)
> > Thanks all.
> 
> Hi @tcmot, How was it resolved,please.

4.x版本以后，官方的意思是去掉了这个特性，不属于核心功能，不想维护。只能把3.x版本中的代码移植到4.x中，我现在还在用3.4版本。

**Comment by tcmot** [comment]
@laulee5135

**Comment by huangjun0124** [comment]
> > > Hi,all.
> > > In version 4.x, is there a successor to Disruptor::handleEventsWithWorkerPool? Can multiple consumers cooperate to process a batch of messages? (one message will only be processed by one consumer)
> > > Thanks all.
> > 
> > 
> > Hi @tcmot, How was it resolved,please.
> 
> 4.x版本以后，官方的意思是去掉了这个特性，不属于核心功能，不想维护。只能把3.x版本中的代码移植到4.x中，我现在还在用3.4版本。

这个有点坑，意思只能用旧版本了

**Comment by tcmot** [comment]
@huangjun0124 
你可以把所有的类拷贝到4.0版本的。
你可以看看我的demo，简单复制了一下，可能不完整。

**Comment by tcmot** [comment]
@huangjun0124 
https://github.com/tcmot/Disruptor2
