### ISSUE TITLE
Another Disruptor

### ISSUE THREAD

**Issue by hl845740757** [LMAX-Exchange/disruptor#472]
I implemented my own version of Disruptor with some design improvements.  

1. I separated the wait strategy from the blocking wait  =>  SequenceBlocker.
2. Allow consumers to use different waiting strategies.
3. Both producers and consumers use SequenceBarrier for coordination => ProducerBarrier + ConsumerBarrier.
4. Dependencies are based on barriers, not sequences.
5. Invert the sequence dependency between barrier and EventProcessor => ConsumerBarrier + ConsumerGroup + EventProcessor.

These ideas may be useful to you. [Disruptor2](https://github.com/hl845740757/disruptor2)
![MyDisruptor](https://github.com/LMAX-Exchange/disruptor/assets/19280199/f714afe4-0538-4228-88ba-0fe6012476a6)

**Comment by Palmr** [comment]
Thanks
