### ISSUE TITLE
I think this framework is great, thank you to the author for their outstanding work. Does this framework have a C++ version?

### ISSUE THREAD

**Issue by iflood** [LMAX-Exchange/disruptor#473]
I think this framework is great, thank you to the author for their outstanding work. Does this framework have a C++ version?

**Comment by Palmr** [comment]
No official c++ version from LMAX, but there's plenty of options to choose from: https://github.com/search?q=disruptor%20c%2B%2B&type=repositories

From a quick skim, I like the looks of https://github.com/lewissbaker/disruptorplus
