### ISSUE TITLE
capacity question

### ISSUE THREAD

**Issue by james-q-arnold** [LMAX-Exchange/disruptor#96]
I have a simple disruptor appliction working.  So far so good.

A question about intended domain.  Is the package suitable for hundreds of event handlers?  My application will have a single event producer, but I expect to have hundreds of event subscribers.  Does the disruptor code have any obvious bottlenecks that would make it unsuitable?

Some suggestions for the documentation.
-  The description of Disruptor.handleEventsWith() does not specifically say new calls add the handler without removing previously registered handlers.
-  The notion of 'batch' as exposed through EventHandler.onEvent is unexplained.
-  The distinction between EventHandler and EventProcessor is unclear.

**Comment by mikeb01** [comment]
I'm going to close this one now.  Please raise separate issues for the tuning options that you would like exposed via the Disruptor DSL.
